import { authenticate } from "./auth";
import { currentAuthority } from "./core";
import type { EventRow } from "./domain";
import { enqueueInvalidation } from "./push";
import { apiError, json, nowIso, readJsonBody, sha256Hex } from "./util";

type Entity="ATTENDANCE_SESSION"|"LABOR_SESSION";
const ATTENDANCE_FIELDS=new Set(["shift","work_choice","pda_serial","user_pick","pack_table","user_pack","state"]),LABOR_FIELDS=new Set(["shift","labor_type","time_marker","state","note","deduct_staff","start_at","end_at"]);
function safePatch(entity:Entity,patch:Record<string,unknown>):Record<string,unknown>{const allowed=entity==="ATTENDANCE_SESSION"?ATTENDANCE_FIELDS:LABOR_FIELDS,out:Record<string,unknown>={};for(const [k,v] of Object.entries(patch))if(allowed.has(k))out[k]=v;return out;}
export async function historicalCorrection(request:Request,env:Env):Promise<Response>{
  const auth=await authenticate(env.DB,env,request);if(!auth)return apiError("UNAUTHORIZED","AUTH",401);if(auth.role!=="SUPERADMIN")return apiError("SUPERADMIN_REQUIRED","PERMISSION",403);
  const b=await readJsonBody<{entity_type:Entity;entity_id:string;reason:string;patch:Record<string,unknown>;target_event_id?:string;idempotency_key:string}>(request),entity=b.entity_type,id=String(b.entity_id||"").trim(),reason=String(b.reason||"").trim(),idem=String(b.idempotency_key||"").trim();if(!["ATTENDANCE_SESSION","LABOR_SESSION"].includes(entity)||!id||reason.length<3||!idem)return apiError("CORRECTION_FIELDS_REQUIRED","VALIDATION",400);
  const prior=await env.DB.prepare("SELECT * FROM events WHERE idempotency_key=?1").bind(idem).first<EventRow>();if(prior)return json({ok:true,duplicate:true,event:prior});
  const table=entity==="ATTENDANCE_SESSION"?"attendance_sessions":"labor_sessions",pk=entity==="ATTENDANCE_SESSION"?"session_id":"labor_id",before=await env.DB.prepare(`SELECT * FROM ${table} WHERE ${pk}=?1`).bind(id).first<Record<string,unknown>>();if(!before)return apiError("CORRECTION_TARGET_NOT_FOUND","VALIDATION",404);const patch=safePatch(entity,b.patch||{});if(!Object.keys(patch).length)return apiError("CORRECTION_PATCH_EMPTY","VALIDATION",400);const after={...before,...patch},a=await currentAuthority(env.DB);if(a.mode!=="SERVICE_PRIMARY")return apiError("SERVICE_NOT_WRITE_AUTHORITY","CONFLICT",409,true);const committed=nowIso(),newVersion=Number(before.version||0)+1,base={event_id:crypto.randomUUID(),event_type:"HISTORICAL_CORRECTION",entity_type:entity,entity_id:id,business_date:String(before.business_date||""),authority_epoch:a.authority_epoch,authority_seq:a.authority_seq+1,service_generation:a.service_generation,base_version:Number(before.version||0),new_version:newVersion,actor_id:auth.login_id,actor_role:auth.role,device_id:auth.device_id,occurred_at:committed,committed_at:committed,payload_json:JSON.stringify({source:"WEB",reason,target_event_id:String(b.target_event_id||""),before,after}),idempotency_key:idem,origin:"WEB_CORRECTION",schema_version:1},event:EventRow={...base,checksum:await sha256Hex(JSON.stringify(base))};
  const sets=Object.keys(patch).map((k,i)=>`${k}=?${i+1}`);sets.push(`version=?${Object.keys(patch).length+1}`,`updated_at=?${Object.keys(patch).length+2}`);const values=[...Object.values(patch),newVersion,committed,id],targetIndex=values.length;try{await env.DB.batch([
    env.DB.prepare(`UPDATE ${table} SET ${sets.join(",")} WHERE ${pk}=?${targetIndex} AND version=?${targetIndex+1}`).bind(...values,Number(before.version||0)),
    env.DB.prepare("UPDATE authority_state SET authority_seq=?1,updated_at=?2 WHERE singleton_id=1 AND authority_epoch=?3 AND authority_seq=?4").bind(event.authority_seq,committed,a.authority_epoch,a.authority_seq),
    env.DB.prepare(`INSERT INTO events(event_id,event_type,entity_type,entity_id,business_date,authority_epoch,authority_seq,service_generation,base_version,new_version,actor_id,actor_role,device_id,occurred_at,committed_at,payload_json,idempotency_key,origin,schema_version,checksum) VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11,?12,?13,?14,?15,?16,?17,?18,?19,?20)`).bind(event.event_id,event.event_type,event.entity_type,event.entity_id,event.business_date,event.authority_epoch,event.authority_seq,event.service_generation,event.base_version,event.new_version,event.actor_id,event.actor_role,event.device_id,event.occurred_at,event.committed_at,event.payload_json,event.idempotency_key,event.origin,event.schema_version,event.checksum),
    env.DB.prepare("INSERT INTO sheet_replication_outbox(event_id,status,next_attempt_at) VALUES(?1,'PENDING',?2)").bind(event.event_id,committed)
  ]);}catch(e){return apiError("CORRECTION_CONFLICT","TRANSIENT",409,true,String(e).slice(0,160));}
  await enqueueInvalidation(env.DB,"day",event.authority_seq,event.business_date);try{const hub=env.REALTIME_HUB.getByName(`business:${event.business_date}`) as unknown as {invalidate(message:Record<string,unknown>):Promise<number>};await hub.invalidate({type:"DAY_CHANGED",business_date:event.business_date,day_revision:event.authority_seq,authority_epoch:event.authority_epoch,authority_seq:event.authority_seq});}catch{}
  return json({ok:true,duplicate:false,event,before,after},201);
}
