import { nowIso, sha256Hex } from "./util";
import { currentAuthority } from "./core";
import { isStableEnvironment, stableSheetBridge } from "./stable_sheet_bridge";
import { requireSheetsCall } from "./quota_budget";

const HEADERS:Record<string,string[]>={
  "Danh mục":["DANH SÁCH NHÂN SỰ_Vị trí chính","DANH SÁCH NHÂN SỰ_Nhà cung cấp","DANH SÁCH NHÂN SỰ_Bộ phận","DANH SÁCH NHÂN SỰ_Site","DANH SÁCH NHÂN SỰ_Kho","DANH SÁCH PDA_Tình trạng","DANH SÁCH USER PICK_Tình trạng","DANH SÁCH BÀN PACK_Tình trạng","DANH SÁCH USER PACK_Tình trạng","RA - VÀO TRONG CA_Loại thao tác","VÀO - RA TRONG CA_Ca","CÔNG NHẬT_Thông tin công nhật","CÔNG NHẬT_Mốc thời gian","CÔNG NHẬT_Trạng thái"],
  "LỊCH SỬ NGHIỆP VỤ":["Ngày","Session ID","Mã nhân viên","Họ tên","Ca","Loại sự kiện","Nhãn sự kiện","Thời gian","Người xử lý","Chi tiết","Event ID","Phạm vi","App Revision"],
  "DANH SÁCH PDA":["Seri PDA","5 số cuối Seri","Tình trạng","Ghi chú"],
  "DANH SÁCH USER PICK":["Số User","User Pick","Tình trạng","Ghi chú"],
  "DANH SÁCH BÀN PACK":["Tên bàn pack","Tình trạng"],
  "DANH SÁCH USER PACK":["Tên bàn pack","User pack","User Pack","Tình trạng"],
  "DANH SÁCH NHÂN SỰ":["Mã nhân viên","Họ và tên","Số điện thoại","Vị trí chính","Nhà cung cấp","Bộ phận","Site","Kho","Ngày bắt đầu làm việc","Ghi chú","Người cập nhật","Thời gian cập nhật"],
  "RA - VÀO TRONG CA":["Ngày","Ca","Mã nhân viên","Họ và tên","Số điện thoại","Nhà cung cấp","Bộ phận","Site","Kho","Vị trí chính","Vị trí trong ca","Seri PDA","User Pick","Bàn Pack","User Pack","Loại thao tác","Ghi chú","Người cập nhật","Thời gian cập nhật","Event ID","App action","App revision"],
  "CÔNG NHẬT":["Ngày","Ca","Mã nhân viên","Họ và tên","Số điện thoại","Nhà cung cấp","Bộ phận","Site","Kho","Vị trí chính","Vị trí trong ca","Thông tin công nhật","Thời gian bắt đầu","Thời gian kết thúc","Mốc thời gian","Trạng thái","Ghi chú","Người cập nhật","Thời gian cập nhật","Event ID","Finish Event ID","App revision","Khấu trừ nhân sự"],
  "Danh sách Admin":["Số User","Password verifier","Tình trạng","Ghi chú","Vị trí","Mail","Logic quyền cơ bản","","Trạng thái tài khoản","Người cập nhật","Thời gian cập nhật"],
};

type Employee={mnv:string;full_name:string;phone:string;main_position:string;supplier:string;department:string;site:string;warehouse:string;start_date:string;note:string};
function visibleDate(iso:string):string{const m=iso.match(/^(\d{4})-(\d{2})-(\d{2})$/);return m&&m[1]&&m[2]&&m[3]?`${m[3]}/${m[2]}/${m[1]}`:iso;}
function visibleTime(iso:string|null|undefined):string{if(!iso)return"";const d=new Date(iso);if(Number.isNaN(d.getTime()))return iso;return new Intl.DateTimeFormat("en-GB",{timeZone:"Asia/Bangkok",day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false}).format(d).replace(",","");}
function a1(name:string,range:string):string{return `'${name.replace(/'/g,"''")}'!${range}`;}
async function token(env:Env):Promise<string>{if(isStableEnvironment(env))return "__STABLE_BOUND_GAS__";const body=new URLSearchParams({client_id:env.GOOGLE_OAUTH_CLIENT_ID,client_secret:env.GOOGLE_OAUTH_CLIENT_SECRET,refresh_token:env.GOOGLE_OAUTH_REFRESH_TOKEN,grant_type:"refresh_token"});const r=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body});const j=await r.json<{access_token?:string;error?:string}>();if(!r.ok||!j.access_token)throw new Error(`GOOGLE_OAUTH:${j.error??r.status}`);return j.access_token;}
function auth(t:string,extra:HeadersInit={}):HeadersInit{return{authorization:`Bearer ${t}`,...extra};}
async function writeTable(env:Env,t:string,name:string,rows:unknown[][]):Promise<void>{
  if(isStableEnvironment(env)){await stableSheetBridge(env,"dr","replace_table",{sheet:name,headers:HEADERS[name]!,rows});return;}
  const id=env.GOOGLE_STAGING_SHEET_ID;
  await requireSheetsCall(env.DB,"WRITE");
  const clear=await fetch(`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(id)}/values/${encodeURIComponent(a1(name,"A:AZ"))}:clear`,{method:"POST",headers:auth(t,{"content-type":"application/json"}),body:"{}"});
  if(!clear.ok)throw new Error(`DR_CLEAR:${name}:${clear.status}`);
  const all=[HEADERS[name]!,...rows];
  for(let i=0;i<all.length;i+=500){const chunk=all.slice(i,i+500),start=i+1,range=a1(name,`A${start}`);await requireSheetsCall(env.DB,"WRITE");const r=await fetch(`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(id)}/values/${encodeURIComponent(range)}?valueInputOption=RAW`,{method:"PUT",headers:auth(t,{"content-type":"application/json"}),body:JSON.stringify({range,majorDimension:"ROWS",values:chunk})});if(!r.ok)throw new Error(`DR_WRITE:${name}:${start}:${r.status}`);}
}
function resourceMeta(raw:string):Record<string,string>{try{return JSON.parse(raw) as Record<string,string>;}catch{return{};}}
function label(type:string):string{return type==="ATTENDANCE_ENTER"?"Vào ca":type==="ATTENDANCE_EXIT"?"Ra ca":type==="RESOURCE_CHANGE"?"Đổi tài nguyên":type==="LABOR_START"?"Bắt đầu công nhật":type==="LABOR_FINISH"?"Kết thúc công nhật":type;}


export async function rebuildGoogleStagingFromD1(db:D1Database,env:Env):Promise<Record<string,unknown>>{
  const drTarget=isStableEnvironment(env)?String(env.DR_TARGET_ID||""):env.GOOGLE_STAGING_SHEET_ID;if(!drTarget||drTarget===env.GOOGLE_SOURCE_SHEET_ID)throw new Error("DR_TARGET_MUST_NOT_BE_PRODUCTION_SOURCE");
  const started=nowIso(),recoveryId=crypto.randomUUID(),authority=await currentAuthority(db);await db.prepare("INSERT INTO recovery_runs(recovery_id,recovery_type,from_generation,to_generation,source_authority_epoch,source_authority_seq,target_authority_epoch,status,started_at,validation_json) VALUES(?1,'GOOGLE_REBUILD_FROM_D1',?2,?2,?3,?4,?3,'RUNNING',?5,'{}')").bind(recoveryId,authority.service_generation,authority.authority_epoch,authority.authority_seq,started).run();
  try{
    const employees=(await db.prepare("SELECT mnv,full_name,phone,main_position,supplier,department,site,warehouse,start_date,note FROM employees ORDER BY mnv").all<Employee>()).results??[],staff=new Map(employees.map(e=>[e.mnv,e]));
    const catalog=(await db.prepare("SELECT namespace,ordinal,value FROM catalog_values ORDER BY namespace,ordinal").all<{namespace:string;ordinal:number;value:string}>()).results??[];const cats=new Map<string,string[]>();for(const c of catalog){const a=cats.get(c.namespace)??[];a[c.ordinal-1]=c.value;cats.set(c.namespace,a);}const catHeaders=HEADERS["Danh mục"]!,catMax=Math.max(0,...catHeaders.map(h=>(cats.get(h)??[]).length)),catRows=Array.from({length:catMax},(_,i)=>catHeaders.map(h=>cats.get(h)?.[i]??""));
    const resources=(await db.prepare("SELECT resource_type,resource_id,status_label,metadata_json FROM resources ORDER BY resource_type,resource_id").all<{resource_type:string;resource_id:string;status_label:string;metadata_json:string}>()).results??[];
    const pdaRows=resources.filter(r=>r.resource_type==="PDA").map(r=>{const m=resourceMeta(r.metadata_json);return[r.resource_id,m["5 số cuối Seri"]??r.resource_id.slice(-5),r.status_label,m["Ghi chú"]??""];});
    const pickRows=resources.filter(r=>r.resource_type==="USER_PICK").map(r=>{const m=resourceMeta(r.metadata_json);return[m["Số User"]??"",r.resource_id,r.status_label,m["Ghi chú"]??""];});
    const tableRows=resources.filter(r=>r.resource_type==="PACK_TABLE").map(r=>[r.resource_id,r.status_label]);
    const packMap=(await db.prepare("SELECT pack_table,shift,user_pack,label,available FROM resource_pack_map ORDER BY pack_table,shift,user_pack").all<{pack_table:string;shift:string;user_pack:string;label:string;available:number}>()).results??[];const packRows=packMap.map(r=>[r.pack_table,r.label,r.user_pack,r.available?"Khả dụng":"Không khả dụng"]);
    const employeeRows=employees.map(e=>[e.mnv,e.full_name,e.phone,e.main_position,e.supplier,e.department,e.site,e.warehouse,e.start_date,e.note,"SERVICE_DR",visibleTime(started)]);
    const events=(await db.prepare("SELECT event_id,event_type,entity_id,business_date,authority_seq,service_generation,actor_id,committed_at,payload_json FROM events ORDER BY authority_epoch,authority_seq").all<{event_id:string;event_type:string;entity_id:string;business_date:string;authority_seq:number;service_generation:string;actor_id:string;committed_at:string;payload_json:string}>()).results??[];
    const attendanceRows:unknown[][]=[],historyRows:unknown[][]=[];for(const e of events){let p:Record<string,unknown>={};try{p=JSON.parse(e.payload_json) as Record<string,unknown>;}catch{}const mnv=String(p.mnv??""),emp=staff.get(mnv),shift=String(p.shift??"");historyRows.push([visibleDate(e.business_date),e.entity_id,mnv,emp?.full_name??"",shift,e.event_type,label(e.event_type),visibleTime(e.committed_at),e.actor_id,String(p.note??p.labor_type??""),e.event_id,"SERVICE_D1",e.service_generation]);if(["ATTENDANCE_ENTER","ATTENDANCE_EXIT","RESOURCE_CHANGE"].includes(e.event_type))attendanceRows.push([visibleDate(e.business_date),shift,mnv,emp?.full_name??"",emp?.phone??"",emp?.supplier??"",emp?.department??"",emp?.site??"",emp?.warehouse??"",emp?.main_position??"",String(p.work_choice??""),String(p.pda_serial??""),String(p.user_pick??""),String(p.pack_table??""),String(p.user_pack??""),label(e.event_type),String(p.note??""),e.actor_id,visibleTime(e.committed_at),e.event_id,e.event_type,e.service_generation]);}
    const labor=(await db.prepare("SELECT labor_id,mnv,business_date,shift,labor_type,time_marker,state,start_at,end_at,note,deduct_staff,start_event_id,finish_event_id,version,updated_at FROM labor_sessions ORDER BY business_date,start_at").all<{labor_id:string;mnv:string;business_date:string;shift:string;labor_type:string;time_marker:string;state:string;start_at:string|null;end_at:string|null;note:string;deduct_staff:number;start_event_id:string;finish_event_id:string|null;version:number;updated_at:string}>()).results??[];const laborRows=labor.map(r=>{const e=staff.get(r.mnv);return[visibleDate(r.business_date),r.shift,r.mnv,e?.full_name??"",e?.phone??"",e?.supplier??"",e?.department??"",e?.site??"",e?.warehouse??"",e?.main_position??"","",r.labor_type,visibleTime(r.start_at),visibleTime(r.end_at),r.time_marker,r.state,r.note,"SERVICE_DR",visibleTime(r.updated_at),r.start_event_id,r.finish_event_id??"",`v${r.version}`,r.deduct_staff?"Có":"Không"];});
    const accounts=(await db.prepare("SELECT login_id,verifier,role,display_name,position,email,status FROM accounts WHERE is_shadow_test=0 ORDER BY login_id").all<{login_id:string;verifier:string;role:string;display_name:string;position:string;email:string;status:string}>()).results??[];const adminRows=accounts.map(a=>[a.login_id,a.verifier,a.status,a.display_name,a.role,a.email,a.role,"",a.status,"SERVICE_DR",visibleTime(started)]);
    const t=await token(env);const tables:[string,unknown[][]][]=[["Danh mục",catRows],["LỊCH SỬ NGHIỆP VỤ",historyRows],["DANH SÁCH PDA",pdaRows],["DANH SÁCH USER PICK",pickRows],["DANH SÁCH BÀN PACK",tableRows],["DANH SÁCH USER PACK",packRows],["DANH SÁCH NHÂN SỰ",employeeRows],["RA - VÀO TRONG CA",attendanceRows],["CÔNG NHẬT",laborRows],["Danh sách Admin",adminRows]];for(const [name,rows] of tables)await writeTable(env,t,name,rows);
    const counts=Object.fromEntries(tables.map(([n,r])=>[n,r.length])),checksum=await sha256Hex(JSON.stringify({authority_epoch:authority.authority_epoch,authority_seq:authority.authority_seq,counts})),done=nowIso(),validation={target_sheet_id:drTarget,production_source_untouched:env.GOOGLE_SOURCE_SHEET_ID!==drTarget,counts,checksum};
    await db.prepare("UPDATE recovery_runs SET status='COMPLETE',completed_at=?1,validation_json=?2 WHERE recovery_id=?3").bind(done,JSON.stringify(validation),recoveryId).run();return{ok:true,recovery_id:recoveryId,authority,validation};
  }catch(e){await db.prepare("UPDATE recovery_runs SET status='FAILED',completed_at=?1,error=?2 WHERE recovery_id=?3").bind(nowIso(),String(e).slice(0,1000),recoveryId).run().catch(()=>undefined);throw e;}
}
