import { strToU8, unzipSync, zipSync } from "fflate";
import { authenticate } from "./auth";
import { apiError, json, readJsonBody, sha256Hex } from "./util";

type Dataset="employees"|"catalogs"|"pda"|"user_pick"|"pack_table"|"user_pack";
type Spec={headers:string[];required:string[]};
const VERSION="2026-08-19-v1";
const SPECS:Record<Dataset,Spec>={
  employees:{headers:["mnv","full_name","phone","main_position","supplier","department","site","warehouse","start_date","note"],required:["mnv","full_name"]},
  catalogs:{headers:["namespace","ordinal","value"],required:["namespace","value"]},
  pda:{headers:["resource_id","status_label","available","metadata_json"],required:["resource_id"]},
  user_pick:{headers:["resource_id","status_label","available","metadata_json"],required:["resource_id"]},
  pack_table:{headers:["pack_table","shift","user_pack","label","status_label","available"],required:["pack_table","shift","status_label"]},
  user_pack:{headers:["resource_id","status_label","available","metadata_json"],required:["resource_id"]},
};
function isDataset(v:string):v is Dataset{return Object.hasOwn(SPECS,v);}
async function requireSuper(request:Request,env:Env):Promise<true|Response>{const a=await authenticate(env.DB,env,request);if(!a)return apiError("UNAUTHORIZED","AUTH",401);if(a.role!=="SUPERADMIN")return apiError("SUPERADMIN_REQUIRED","PERMISSION",403);return true;}
async function checksum(dataset:Dataset):Promise<string>{const s=SPECS[dataset];return sha256Hex(JSON.stringify({version:VERSION,dataset,headers:s.headers,required:s.required}));}
function esc(v:string):string{return v.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&apos;");}
function unesc(v:string):string{return v.replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&amp;/g,"&");}
function colName(n:number):string{let out="";for(let x=n+1;x>0;x=Math.floor((x-1)/26))out=String.fromCharCode(65+(x-1)%26)+out;return out;}
function colIndex(ref:string):number{let n=0;for(const ch of ref.replace(/[^A-Za-z].*$/,""))n=n*26+(ch.toUpperCase().charCodeAt(0)-64);return n-1;}
function sheetXml(rows:string[][]):string{const body=rows.map((row,ri)=>`<row r="${ri+1}">${row.map((v,ci)=>`<c r="${colName(ci)}${ri+1}" t="inlineStr"><is><t xml:space="preserve">${esc(v)}</t></is></c>`).join("")}</row>`).join("");return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>${body}</sheetData></worksheet>`;}

export async function importTemplateXlsx(request:Request,env:Env):Promise<Response>{
  const ok=await requireSuper(request,env);if(ok instanceof Response)return ok;const u=new URL(request.url),dataset=String(u.searchParams.get("dataset")||"");if(!isDataset(dataset))return apiError("IMPORT_DATASET_UNSUPPORTED","VALIDATION",400);const spec=SPECS[dataset],digest=await checksum(dataset);
  const files:Record<string,Uint8Array>={
    "[Content_Types].xml":strToU8(`<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/worksheets/sheet2.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/></Types>`),
    "_rels/.rels":strToU8(`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`),
    "xl/workbook.xml":strToU8(`<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="DATA" sheetId="1" r:id="rId1"/><sheet name="__IMPORT_META" sheetId="2" state="hidden" r:id="rId2"/></sheets></workbook>`),
    "xl/_rels/workbook.xml.rels":strToU8(`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet2.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`),
    "xl/styles.xml":strToU8(`<?xml version="1.0" encoding="UTF-8"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="1"><font><sz val="11"/><name val="Calibri"/></font></fonts><fills count="1"><fill><patternFill patternType="none"/></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/></cellXfs></styleSheet>`),
    "xl/worksheets/sheet1.xml":strToU8(sheetXml([spec.headers])),
    "xl/worksheets/sheet2.xml":strToU8(sheetXml([["key","value"],["template_version",VERSION],["dataset",dataset],["schema_checksum",digest]])),
  };
  const bytes=zipSync(files,{level:6});return new Response(bytes,{status:200,headers:{"content-type":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","content-disposition":`attachment; filename="pick-pack-1291-${dataset}-${VERSION}.xlsx"`,"cache-control":"no-store"}});
}

function decodeShared(xml:string):string[]{const out:string[]=[];for(const m of xml.matchAll(/<si\b[^>]*>([\s\S]*?)<\/si>/g)){let s="";for(const t of m[1]!.matchAll(/<t\b[^>]*>([\s\S]*?)<\/t>/g))s+=unesc(t[1]??"");out.push(s);}return out;}
function parseSheet(xml:string,shared:string[]):string[][]{const rows:string[][]=[];for(const rm of xml.matchAll(/<row\b[^>]*>([\s\S]*?)<\/row>/g)){const cells:string[]=[];for(const cm of rm[1]!.matchAll(/<c\b([^>]*)>([\s\S]*?)<\/c>/g)){const attrs=cm[1]??"",inner=cm[2]??"",ref=/\br="([A-Z]+\d+)"/.exec(attrs)?.[1]??"A1",idx=colIndex(ref),type=/\bt="([^"]+)"/.exec(attrs)?.[1]??"";let value="";if(type==="inlineStr"){for(const t of inner.matchAll(/<t\b[^>]*>([\s\S]*?)<\/t>/g))value+=unesc(t[1]??"");}else{const raw=/<v\b[^>]*>([\s\S]*?)<\/v>/.exec(inner)?.[1]??"";value=type==="s"?shared[Number(raw)]??"":unesc(raw);}while(cells.length<=idx)cells.push("");cells[idx]=value;}rows.push(cells);}return rows;}
function b64Bytes(v:string):Uint8Array{const clean=v.replace(/^data:[^,]+,/,"").replace(/\s/g,"");const raw=atob(clean),out=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out;}
function metaMap(table:string[][]):Record<string,string>{const out:Record<string,string>={};for(const row of table.slice(1)){const k=String(row[0]||"").trim(),v=String(row[1]||"").trim();if(k)out[k]=v;}return out;}

export async function importParseXlsx(request:Request,env:Env):Promise<Response>{
  const ok=await requireSuper(request,env);if(ok instanceof Response)return ok;const b=await readJsonBody<{dataset:string;file_name?:string;file_base64:string}>(request),dataset=String(b.dataset||"");if(!isDataset(dataset))return apiError("IMPORT_DATASET_UNSUPPORTED","VALIDATION",400);if(!String(b.file_name||"").toLowerCase().endsWith(".xlsx"))return apiError("IMPORT_XLSX_EXTENSION_REQUIRED","VALIDATION",400);let bytes:Uint8Array;try{bytes=b64Bytes(String(b.file_base64||""));}catch{return apiError("IMPORT_XLSX_BASE64_INVALID","VALIDATION",400);}if(bytes.length<4||bytes[0]!==0x50||bytes[1]!==0x4b)return apiError("IMPORT_XLSX_ZIP_INVALID","VALIDATION",400);if(bytes.length>8*1024*1024)return apiError("IMPORT_XLSX_TOO_LARGE","VALIDATION",413,false,undefined,{max_bytes:8*1024*1024});
  let zip:Record<string,Uint8Array>;try{zip=unzipSync(bytes,{filter:file=>file.name==="xl/sharedStrings.xml"||file.name==="xl/worksheets/sheet1.xml"||file.name==="xl/worksheets/sheet2.xml"});}catch{return apiError("IMPORT_XLSX_ZIP_INVALID","VALIDATION",400);}
  const sheet=zip["xl/worksheets/sheet1.xml"],metaSheet=zip["xl/worksheets/sheet2.xml"];if(!sheet)return apiError("IMPORT_XLSX_DATA_SHEET_MISSING","SCHEMA",400);if(!metaSheet)return apiError("IMPORT_TEMPLATE_METADATA_MISSING","SCHEMA",409);
  const decoder=new TextDecoder(),shared=zip["xl/sharedStrings.xml"]?decodeShared(decoder.decode(zip["xl/sharedStrings.xml"])):[],table=parseSheet(decoder.decode(sheet),shared),meta=metaMap(parseSheet(decoder.decode(metaSheet),shared)),expectedChecksum=await checksum(dataset);
  if(meta.template_version!==VERSION)return apiError("IMPORT_TEMPLATE_VERSION_STALE","SCHEMA",409,false,undefined,{expected:VERSION,actual:meta.template_version||null});if(meta.dataset!==dataset)return apiError("IMPORT_TEMPLATE_DATASET_MISMATCH","SCHEMA",409,false,undefined,{expected:dataset,actual:meta.dataset||null});if(meta.schema_checksum!==expectedChecksum)return apiError("IMPORT_TEMPLATE_SCHEMA_STALE","SCHEMA",409,false,undefined,{expected:expectedChecksum,actual:meta.schema_checksum||null});
  if(!table.length)return apiError("IMPORT_EMPTY","VALIDATION",400);if(table.length>10001)return apiError("IMPORT_TOO_LARGE","VALIDATION",413);const spec=SPECS[dataset],headers=(table[0]??[]).map(x=>x.trim());if(headers.length!==spec.headers.length||headers.some((h,i)=>h!==spec.headers[i]))return apiError("IMPORT_HEADERS_MISMATCH","SCHEMA",409,false,undefined,{expected:spec.headers,actual:headers});const rows:Record<string,string>[]=[];for(const values of table.slice(1)){const row:Record<string,string>={};let any=false;for(let i=0;i<spec.headers.length;i++){const v=(values[i]??"").trim();row[spec.headers[i]!]=v;if(v)any=true;}if(any)rows.push(row);}return json({ok:true,dataset,template_version:VERSION,schema_checksum:expectedChecksum,headers:spec.headers,row_count:rows.length,rows});
}
