import { authenticate } from "./auth";
import { currentAuthority } from "./core";
import type { AuthContext, EventRow } from "./domain";
import { enqueueInvalidation } from "./push";
import { apiError, json, nowIso, sha256Hex } from "./util";

type Dataset="employees"|"catalogs"|"pda"|"user_pick"|"pack_table"|"user_pack";
type AuditRow={row_no:number;business_key:string;action:string;before_json:string|null;after_json:string};
const RESOURCE_TYPE:Partial<Record<Dataset,string>>={pda:"PDA",user_pick:"USER_PICK",user_pack:"USER_PACK"};
const MAX_CHANGED_ROWS=4000;
const CHUNK_ROWS=500;

function isDataset(x:string):x is Dataset{return ["employees","catalogs","pda","user_pick","pack_table","user_pack"].includes(x);}
async function requireSuper(request:Request,env:Env):Promise<AuthContext|Response>{const a=await authenticate(env.DB,env,request);if(!a)return apiError("UNAUTHORIZED","AUTH",401);if(a.role!=="SUPERADMIN")return apiError("SUPERADMIN_REQUIRED","PERMISSION",403);return a;}
async function meta(db:D1Database,id:string):Promise<{dataset:Dataset;state:string;actor_id:string}|null>{const r=await db.prepare("SELECT dataset,state,actor_id FROM import_batches WHERE import_batch_id=?1").bind(id).first<{dataset:string;state:string;actor_id:string}>();return r&&isDataset(r.dataset)?{dataset:r.dataset,state:r.state,actor_id:r.actor_id}:null;}
function chunks<T>(rows:T[]):T[][]{const out:T[][]=[];for(let i=0;i<rows.length;i+=CHUNK_ROWS)out.push(rows.slice(i,i+CHUNK_ROWS));return out;}

function projectionStatements(db:D1Database,dataset:Dataset,rows:Array<Record<string,unknown>>):D1PreparedStatement[]{
  const raw=JSON.stringify(rows);if(dataset==="employees")return[db.prepare(`INSERT INTO employees(mnv,full_name,phone,main_position,supplier,department,site,warehouse,start_date,note,source_row,source_checksum)
    SELECT json_extract(value,'$.mnv'),json_extract(value,'$.full_name'),json_extract(value,'$.phone'),json_extract(value,'$.main_position'),json_extract(value,'$.supplier'),json_extract(value,'$.department'),json_extract(value,'$.site'),json_extract(value,'$.warehouse'),json_extract(value,'$.start_date'),json_extract(value,'$.note'),0,json_extract(value,'$._checksum') FROM json_each(?1) WHERE 1
    ON CONFLICT(mnv) DO UPDATE SET full_name=excluded.full_name,phone=excluded.phone,main_position=excluded.main_position,supplier=excluded.supplier,department=excluded.department,site=excluded.site,warehouse=excluded.warehouse,start_date=excluded.start_date,note=excluded.note,source_checksum=excluded.source_checksum`).bind(raw)];
  if(dataset==="catalogs")return[db.prepare(`INSERT INTO catalog_values(namespace,ordinal,value,source_checksum)
    SELECT json_extract(value,'$.namespace'),CAST(json_extract(value,'$.ordinal') AS INTEGER),json_extract(value,'$.value'),json_extract(value,'$._checksum') FROM json_each(?1) WHERE 1
    ON CONFLICT(namespace,value) DO UPDATE SET ordinal=excluded.ordinal,source_checksum=excluded.source_checksum`).bind(raw)];
  if(dataset==="pack_table")return[
    db.prepare(`INSERT INTO resource_pack_map(pack_table,shift,user_pack,label,available,source_row,source_checksum)
      SELECT json_extract(value,'$.pack_table'),json_extract(value,'$.shift'),json_extract(value,'$.user_pack'),json_extract(value,'$.label'),CAST(json_extract(value,'$.available') AS INTEGER),0,json_extract(value,'$._checksum') FROM json_each(?1) WHERE 1
      ON CONFLICT(pack_table,shift) DO UPDATE SET user_pack=excluded.user_pack,label=excluded.label,available=excluded.available,source_checksum=excluded.source_checksum`).bind(raw),
    db.prepare(`INSERT INTO resources(resource_type,resource_id,status_label,available,metadata_json,source_row,source_checksum)
      SELECT 'PACK_TABLE',json_extract(value,'$.pack_table'),json_extract(value,'$.status_label'),CAST(json_extract(value,'$.available') AS INTEGER),'{}',0,json_extract(value,'$._checksum') FROM json_each(?1) WHERE 1
      ON CONFLICT(resource_type,resource_id) DO UPDATE SET status_label=excluded.status_label,available=excluded.available,source_checksum=excluded.source_checksum`).bind(raw),
  ];
  const rt=RESOURCE_TYPE[dataset]!;return[db.prepare(`INSERT INTO resources(resource_type,resource_id,status_label,available,metadata_json,source_row,source_checksum)
    SELECT ?2,json_extract(value,'$.resource_id'),json_extract(value,'$.status_label'),CAST(json_extract(value,'$.available') AS INTEGER),COALESCE(json_extract(value,'$.metadata_json'),'{}'),0,json_extract(value,'$._checksum') FROM json_each(?1) WHERE 1
    ON CONFLICT(resource_type,resource_id) DO UPDATE SET status_label=excluded.status_label,available=excluded.available,metadata_json=excluded.metadata_json,source_checksum=excluded.source_checksum`).bind(raw,rt)];
}

async function buildEvent(a:Awaited<ReturnType<typeof currentAuthority>>,auth:AuthContext,dataset:Dataset,key:string,batchId:string,rowNo:number,before:Record<string,unknown>|null,after:Record<string,unknown>,revision:number,seq:number,type:"MASTER_IMPORT_UPSERT"|"MASTER_IMPORT_ROLLBACK"):Promise<EventRow>{
  const committed=nowIso(),base={event_id:crypto.randomUUID(),event_type:type,entity_type:`MASTER_${dataset.toUpperCase()}`,entity_id:key,business_date:"MASTER",authority_epoch:a.authority_epoch,authority_seq:seq,service_generation:a.service_generation,base_version:revision-1,new_version:revision,actor_id:auth.login_id,actor_role:auth.role,device_id:auth.device_id,occurred_at:committed,committed_at:committed,payload_json:JSON.stringify({source:"FILE_IMPORT",import_batch_id:batchId,row_no:rowNo,before,after,reason:type==="MASTER_IMPORT_ROLLBACK"?"IMPORT_BATCH_ROLLBACK":"IMPORT_BATCH_COMMIT"}),idempotency_key:`import:${batchId}:${type}:${rowNo}`,origin:"FILE_IMPORT",schema_version:1};return{...base,checksum:await sha256Hex(JSON.stringify(base))};
}
function eventInsert(db:D1Database,events:EventRow[]):D1PreparedStatement{const raw=JSON.stringify(events);return db.prepare(`INSERT INTO events(event_id,event_type,entity_type,entity_id,business_date,authority_epoch,authority_seq,service_generation,base_version,new_version,actor_id,actor_role,device_id,occurred_at,committed_at,payload_json,idempotency_key,origin,schema_version,checksum)
  SELECT json_extract(value,'$.event_id'),json_extract(value,'$.event_type'),json_extract(value,'$.entity_type'),json_extract(value,'$.entity_id'),json_extract(value,'$.business_date'),CAST(json_extract(value,'$.authority_epoch') AS INTEGER),CAST(json_extract(value,'$.authority_seq') AS INTEGER),json_extract(value,'$.service_generation'),CAST(json_extract(value,'$.base_version') AS INTEGER),CAST(json_extract(value,'$.new_version') AS INTEGER),json_extract(value,'$.actor_id'),json_extract(value,'$.actor_role'),json_extract(value,'$.device_id'),json_extract(value,'$.occurred_at'),json_extract(value,'$.committed_at'),json_extract(value,'$.payload_json'),json_extract(value,'$.idempotency_key'),json_extract(value,'$.origin'),CAST(json_extract(value,'$.schema_version') AS INTEGER),json_extract(value,'$.checksum') FROM json_each(?1)`).bind(raw);}
function outboxInsert(db:D1Database,events:EventRow[]):D1PreparedStatement{const raw=JSON.stringify(events);return db.prepare(`INSERT INTO sheet_replication_outbox(event_id,status,next_attempt_at)
  SELECT json_extract(value,'$.event_id'),'PENDING',json_extract(value,'$.committed_at') FROM json_each(?1)`).bind(raw);}
function auditLink(db:D1Database,batchId:string,links:Array<{row_no:number;event_id:string}>):D1PreparedStatement{const raw=JSON.stringify(links);return db.prepare(`WITH m AS (SELECT CAST(json_extract(value,'$.row_no') AS INTEGER) row_no,json_extract(value,'$.event_id') event_id FROM json_each(?2))
  UPDATE import_row_audit SET canonical_event_id=(SELECT event_id FROM m WHERE m.row_no=import_row_audit.row_no) WHERE import_batch_id=?1 AND row_no IN (SELECT row_no FROM m)`).bind(batchId,raw);}
async function notify(env:Env,dataset:Dataset,revision:number,a:{authority_epoch:number;authority_seq:number;service_generation:string}):Promise<void>{try{await enqueueInvalidation(env.DB,dataset,revision);}catch(e){console.log(JSON.stringify({level:"warn",kind:"fcm_invalidation_enqueue_failed",namespace:dataset,error_class:"TRANSIENT",error:String(e).slice(0,160)}));}try{const hub=env.REALTIME_HUB.getByName("master:global") as unknown as {invalidate(message:Record<string,unknown>):Promise<number>};await hub.invalidate({type:"MASTER_CHANGED",namespace:dataset,revision,authority_epoch:a.authority_epoch,authority_seq:a.authority_seq,service_generation:a.service_generation});}catch(e){console.log(JSON.stringify({level:"warn",kind:"ws_master_invalidation_failed",namespace:dataset,error_class:"TRANSIENT",error:String(e).slice(0,160)}));}}

export async function importCommitAtomic(request:Request,env:Env,id:string):Promise<Response>{
  const auth=await requireSuper(request,env);if(auth instanceof Response)return auth;const m=await meta(env.DB,id);if(!m)return apiError("IMPORT_BATCH_NOT_FOUND","VALIDATION",404);if(m.actor_id!==auth.login_id)return apiError("IMPORT_BATCH_OWNER_MISMATCH","PERMISSION",403);if(m.state==="COMMITTED")return json({ok:true,import_batch_id:id,duplicate:true,state:"COMMITTED"});if(m.state!=="VALIDATED")return apiError("IMPORT_NOT_VALIDATED","CONFLICT",409);
  const [a,revRow,audits]=await Promise.all([currentAuthority(env.DB),env.DB.prepare("SELECT revision FROM revision_state WHERE namespace=?1").bind(m.dataset).first<{revision:number}>(),env.DB.prepare("SELECT row_no,business_key,action,before_json,after_json FROM import_row_audit WHERE import_batch_id=?1 ORDER BY row_no").bind(id).all<AuditRow>()]);if(a.mode!=="SERVICE_PRIMARY")return apiError("SERVICE_NOT_WRITE_AUTHORITY","CONFLICT",409,true);const changed=(audits.results??[]).filter(x=>x.action==="INSERT"||x.action==="UPDATE");if((audits.results??[]).some(x=>x.action==="REJECTED"))return apiError("IMPORT_HAS_REJECTED_ROWS","VALIDATION",409);if(changed.length>MAX_CHANGED_ROWS)return apiError("IMPORT_ATOMIC_LIMIT_EXCEEDED","VALIDATION",413,false,undefined,{max_changed_rows:MAX_CHANGED_ROWS});
  if(!changed.length){await env.DB.prepare("UPDATE import_batches SET state='COMMITTED',committed_at=?1 WHERE import_batch_id=?2 AND state='VALIDATED'").bind(nowIso(),id).run();return json({ok:true,import_batch_id:id,state:"COMMITTED",dataset:m.dataset,revision:revRow?.revision??0,changed:0,event_ids:{}});}
  const revision=(revRow?.revision??0)+1,events:EventRow[]=[],rows:Array<Record<string,unknown>>=[],links:Array<{row_no:number;event_id:string}>=[];let seq=a.authority_seq;
  for(const x of changed){const after=JSON.parse(x.after_json) as Record<string,unknown>,before=x.before_json?JSON.parse(x.before_json) as Record<string,unknown>:null,projection={...after,_checksum:await sha256Hex(JSON.stringify(after))};const e=await buildEvent(a,auth,m.dataset,x.business_key,id,x.row_no,before,after,revision,++seq,"MASTER_IMPORT_UPSERT");events.push(e);rows.push(projection);links.push({row_no:x.row_no,event_id:e.event_id});}
  const stmts:D1PreparedStatement[]=[];const rowChunks=chunks(rows),eventChunks=chunks(events),linkChunks=chunks(links);for(let i=0;i<rowChunks.length;i++){stmts.push(...projectionStatements(env.DB,m.dataset,rowChunks[i]!));stmts.push(eventInsert(env.DB,eventChunks[i]!));stmts.push(outboxInsert(env.DB,eventChunks[i]!));stmts.push(auditLink(env.DB,id,linkChunks[i]!));}
  const at=nowIso();stmts.push(env.DB.prepare("UPDATE authority_state SET authority_seq=?1,updated_at=?2 WHERE singleton_id=1 AND authority_epoch=?3 AND authority_seq=?4").bind(seq,at,a.authority_epoch,a.authority_seq));stmts.push(env.DB.prepare("INSERT INTO revision_state(namespace,revision,updated_at) VALUES(?1,?2,?3) ON CONFLICT(namespace) DO UPDATE SET revision=excluded.revision,updated_at=excluded.updated_at").bind(m.dataset,revision,at));stmts.push(env.DB.prepare("UPDATE import_batches SET state='COMMITTED',committed_at=?1 WHERE import_batch_id=?2 AND state='VALIDATED'").bind(at,id));
  try{await env.DB.batch(stmts);}catch(e){return apiError("IMPORT_COMMIT_CONFLICT","TRANSIENT",409,true,String(e).slice(0,180));}await notify(env,m.dataset,revision,{authority_epoch:a.authority_epoch,authority_seq:seq,service_generation:a.service_generation});return json({ok:true,import_batch_id:id,state:"COMMITTED",dataset:m.dataset,revision,changed:changed.length,event_ids:Object.fromEntries(links.map(x=>[x.row_no,x.event_id]))});
}

export async function importRollbackAtomic(request:Request,env:Env,id:string):Promise<Response>{
  const auth=await requireSuper(request,env);if(auth instanceof Response)return auth;const m=await meta(env.DB,id);if(!m)return apiError("IMPORT_BATCH_NOT_FOUND","VALIDATION",404);if(m.state==="ROLLED_BACK")return json({ok:true,import_batch_id:id,duplicate:true,state:"ROLLED_BACK"});if(m.state!=="COMMITTED")return apiError("IMPORT_NOT_COMMITTED","CONFLICT",409);const audits=(await env.DB.prepare("SELECT row_no,business_key,action,before_json,after_json FROM import_row_audit WHERE import_batch_id=?1 AND action IN ('INSERT','UPDATE') ORDER BY row_no").bind(id).all<AuditRow>()).results??[];if(audits.some(x=>x.action==="INSERT"&&!x.before_json))return apiError("IMPORT_ROLLBACK_INSERT_REQUIRES_EXPLICIT_CORRECTION","CONFLICT",409,false,undefined,{policy:"NO_IMPLICIT_DELETE"});if(audits.length>MAX_CHANGED_ROWS)return apiError("IMPORT_ATOMIC_LIMIT_EXCEEDED","VALIDATION",413,false,undefined,{max_changed_rows:MAX_CHANGED_ROWS});
  const [a,revRow]=await Promise.all([currentAuthority(env.DB),env.DB.prepare("SELECT revision FROM revision_state WHERE namespace=?1").bind(m.dataset).first<{revision:number}>()]);if(a.mode!=="SERVICE_PRIMARY")return apiError("SERVICE_NOT_WRITE_AUTHORITY","CONFLICT",409,true);if(!audits.length){await env.DB.prepare("UPDATE import_batches SET state='ROLLED_BACK',rolled_back_at=?1 WHERE import_batch_id=?2 AND state='COMMITTED'").bind(nowIso(),id).run();return json({ok:true,import_batch_id:id,state:"ROLLED_BACK",dataset:m.dataset,revision:revRow?.revision??0,corrected:0});}
  const revision=(revRow?.revision??0)+1,events:EventRow[]=[],rows:Array<Record<string,unknown>>=[];let seq=a.authority_seq;for(const x of audits){const before=JSON.parse(x.before_json!) as Record<string,unknown>,after=JSON.parse(x.after_json) as Record<string,unknown>,projection={...before,_checksum:await sha256Hex(JSON.stringify(before))};events.push(await buildEvent(a,auth,m.dataset,x.business_key,id,x.row_no,after,before,revision,++seq,"MASTER_IMPORT_ROLLBACK"));rows.push(projection);}
  const stmts:D1PreparedStatement[]=[];const rowChunks=chunks(rows),eventChunks=chunks(events);for(let i=0;i<rowChunks.length;i++){stmts.push(...projectionStatements(env.DB,m.dataset,rowChunks[i]!));stmts.push(eventInsert(env.DB,eventChunks[i]!));stmts.push(outboxInsert(env.DB,eventChunks[i]!));}
  const at=nowIso();stmts.push(env.DB.prepare("UPDATE authority_state SET authority_seq=?1,updated_at=?2 WHERE singleton_id=1 AND authority_epoch=?3 AND authority_seq=?4").bind(seq,at,a.authority_epoch,a.authority_seq));stmts.push(env.DB.prepare("UPDATE revision_state SET revision=?1,updated_at=?2 WHERE namespace=?3").bind(revision,at,m.dataset));stmts.push(env.DB.prepare("UPDATE import_batches SET state='ROLLED_BACK',rolled_back_at=?1 WHERE import_batch_id=?2 AND state='COMMITTED'").bind(at,id));try{await env.DB.batch(stmts);}catch(e){return apiError("IMPORT_ROLLBACK_CONFLICT","TRANSIENT",409,true,String(e).slice(0,180));}await notify(env,m.dataset,revision,{authority_epoch:a.authority_epoch,authority_seq:seq,service_generation:a.service_generation});return json({ok:true,import_batch_id:id,state:"ROLLED_BACK",dataset:m.dataset,revision,corrected:audits.length});
}
