import { authenticate } from "./auth";
import { bangkokToday, ensureCurrentBangkokBusinessDate } from "./business_date";
import { currentAuthority } from "./core";
import type { EventRow } from "./domain";
import { enqueueInvalidation } from "./push";
import { apiError, json, nowIso, readJsonBody, sha256Hex } from "./util";

type ResourceType="PDA"|"USER_PICK"|"PACK_TABLE"|"USER_PACK";
type AssignmentState="ACTIVE"|"USED"|"VOID";
type Disposition="USED"|"AVAILABLE";
type AuthLike={login_id:string;role:string;device_id:string};
type SessionRow={session_id:string;mnv:string;business_date:string;shift:string;work_choice:string;state:string;pda_serial:string|null;user_pick:string|null;pack_table:string|null;user_pack:string|null;pda_enter_status:string|null;pda_exit_status:string|null;resource_note:string;enter_at:string|null;exit_at:string|null;entered_by:string|null;exited_by:string|null;version:number};
type AssignmentRow={assignment_id:string;session_id:string;mnv:string;business_date:string;resource_type:ResourceType;resource_id:string;position_key:string;state:AssignmentState;acquired_at:string;released_at:string|null;acquire_event_id:string;release_event_id:string|null;release_reason:string;release_disposition:string;context_json:string};
type PositionRow={position_assignment_id:string;session_id:string;mnv:string;business_date:string;position_key:string;position_label:string;state:AssignmentState;started_at:string;ended_at:string|null;start_event_id:string;end_event_id:string|null;reason:string};
type Operation={op?:unknown;resource_type?:unknown;resource_id?:unknown;new_resource_id?:unknown;assignment_id?:unknown;position_key?:unknown;position_label?:unknown;reason?:unknown;disposition?:unknown;duplicate_user?:unknown;shift?:unknown;pda_enter_status?:unknown};

function text(v:unknown,max=300):string{return String(v??"").trim().slice(0,max);}
function typeOf(v:unknown):ResourceType|null{const x=text(v,30).toUpperCase();return (["PDA","USER_PICK","PACK_TABLE","USER_PACK"] as string[]).includes(x)?x as ResourceType:null;}
function positionForType(t:ResourceType):string{return t==="PDA"||t==="USER_PICK"?"PICK":"PACK";}
function validShift(v:string):boolean{return ["Ca 1","Ca HC","Ca 2"].includes(v);}
function isUser(t:ResourceType):boolean{return t==="USER_PICK"||t==="USER_PACK";}
function clone<T>(v:T):T{return JSON.parse(JSON.stringify(v)) as T;}
function activeAssignments(rows:AssignmentRow[]):AssignmentRow[]{return rows.filter(x=>x.state==="ACTIVE");}
function visibleAssignments(rows:AssignmentRow[]):AssignmentRow[]{return rows.filter(x=>x.state==="ACTIVE"||x.state==="USED");}
function visiblePositions(rows:PositionRow[]):PositionRow[]{return rows.filter(x=>x.state==="ACTIVE"||x.state==="USED");}

async function byId(db:D1Database,id:string):Promise<SessionRow|null>{return db.prepare("SELECT session_id,mnv,business_date,shift,work_choice,state,pda_serial,user_pick,pack_table,user_pack,pda_enter_status,pda_exit_status,resource_note,enter_at,exit_at,entered_by,exited_by,version FROM attendance_sessions WHERE session_id=?1").bind(id).first<SessionRow>();}
async function activeByMnv(db:D1Database,mnv:string):Promise<SessionRow|null>{return db.prepare("SELECT session_id,mnv,business_date,shift,work_choice,state,pda_serial,user_pick,pack_table,user_pack,pda_enter_status,pda_exit_status,resource_note,enter_at,exit_at,entered_by,exited_by,version FROM attendance_sessions WHERE mnv=?1 AND state='ACTIVE' ORDER BY enter_at DESC LIMIT 1").bind(mnv).first<SessionRow>();}
async function resolveSession(db:D1Database,id:string,mnv:string):Promise<SessionRow|null>{if(id){const s=await byId(db,id);if(s&&mnv&&s.mnv!==mnv)return null;return s;}return mnv?activeByMnv(db,mnv):null;}
async function assignments(db:D1Database,sessionId:string):Promise<AssignmentRow[]>{const r=await db.prepare("SELECT assignment_id,session_id,mnv,business_date,resource_type,resource_id,position_key,state,acquired_at,released_at,acquire_event_id,release_event_id,release_reason,release_disposition,context_json FROM session_resource_assignments WHERE session_id=?1 ORDER BY acquired_at,assignment_id").bind(sessionId).all<AssignmentRow>();return r.results??[];}
async function positions(db:D1Database,sessionId:string):Promise<PositionRow[]>{const r=await db.prepare("SELECT position_assignment_id,session_id,mnv,business_date,position_key,position_label,state,started_at,ended_at,start_event_id,end_event_id,reason FROM session_positions WHERE session_id=?1 ORDER BY started_at,position_assignment_id").bind(sessionId).all<PositionRow>();return r.results??[];}

async function existing(env:Env,idem:string):Promise<EventRow|null>{return env.DB.prepare("SELECT * FROM events WHERE idempotency_key=?1").bind(idem).first<EventRow>();}
async function buildEvent(env:Env,auth:AuthLike,s:SessionRow,type:string,payload:Record<string,unknown>,idem:string,newVersion:number):Promise<{event:EventRow;expectedSeq:number}>{
  const a=await currentAuthority(env.DB);if(a.mode!=="SERVICE_PRIMARY"||a.scope!=="PRODUCTION")throw new Error("SERVICE_NOT_WRITE_AUTHORITY");const at=nowIso();
  const base={event_id:crypto.randomUUID(),event_type:type,entity_type:"ATTENDANCE_SESSION",entity_id:s.session_id,business_date:s.business_date,authority_epoch:a.authority_epoch,authority_seq:a.authority_seq+1,service_generation:a.service_generation,base_version:s.version,new_version:newVersion,actor_id:auth.login_id,actor_role:auth.role,device_id:auth.device_id,occurred_at:at,committed_at:at,payload_json:JSON.stringify(payload),idempotency_key:idem,origin:"SESSION_V64",schema_version:1};
  return{event:{...base,checksum:await sha256Hex(JSON.stringify(base))},expectedSeq:a.authority_seq};
}
function eventStmts(db:D1Database,e:EventRow,expectedSeq:number):D1PreparedStatement[]{return[
  db.prepare("UPDATE authority_state SET authority_seq=?1,updated_at=?2 WHERE singleton_id=1 AND authority_epoch=?3 AND authority_seq=?4").bind(e.authority_seq,e.committed_at,e.authority_epoch,expectedSeq),
  db.prepare("INSERT INTO events(event_id,event_type,entity_type,entity_id,business_date,authority_epoch,authority_seq,service_generation,base_version,new_version,actor_id,actor_role,device_id,occurred_at,committed_at,payload_json,idempotency_key,origin,schema_version,checksum) VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11,?12,?13,?14,?15,?16,?17,?18,?19,?20)").bind(e.event_id,e.event_type,e.entity_type,e.entity_id,e.business_date,e.authority_epoch,e.authority_seq,e.service_generation,e.base_version,e.new_version,e.actor_id,e.actor_role,e.device_id,e.occurred_at,e.committed_at,e.payload_json,e.idempotency_key,e.origin,e.schema_version,e.checksum),
  db.prepare("INSERT INTO sheet_replication_outbox(event_id,status,next_attempt_at) VALUES(?1,'PENDING',?2)").bind(e.event_id,e.committed_at),
  db.prepare("INSERT INTO session_version_claims(session_id,base_version,event_id,claimed_at) VALUES(?1,?2,?3,?4)").bind(e.entity_id,e.base_version,e.event_id,e.committed_at),
];}
async function invalidate(env:Env,e:EventRow):Promise<void>{await enqueueInvalidation(env.DB,"day",e.authority_seq,e.business_date);try{const hub=env.REALTIME_HUB.getByName(`business:${e.business_date}`) as unknown as {invalidate(message:Record<string,unknown>):Promise<number>};await hub.invalidate({type:"DAY_CHANGED",business_date:e.business_date,day_revision:e.authority_seq,authority_epoch:e.authority_epoch,authority_seq:e.authority_seq});}catch{}}

async function ensureActivatable(env:Env,s:SessionRow,t:ResourceType,id:string,duplicateUser:boolean,current:AssignmentRow[]):Promise<string>{
  const [master,lease]=await env.DB.batch([
    env.DB.prepare("SELECT status_label,available FROM resources WHERE resource_type=?1 AND resource_id=?2").bind(t,id),
    env.DB.prepare("SELECT session_id FROM resource_leases WHERE resource_type=?1 AND resource_id=?2").bind(t,id),
  ]);
  const m=master?.results?.[0] as {status_label?:string;available?:number}|undefined;if(!m)return `${t}_NOT_FOUND`;if(Number(m.available??0)!==1)return `${t}_UNAVAILABLE`;
  const holder=text((lease?.results?.[0] as {session_id?:string}|undefined)?.session_id);if(holder&&holder!==s.session_id)return `${t}_IN_USE`;
  if(current.some(x=>x.state==="ACTIVE"&&x.resource_type===t&&x.resource_id===id))return `${t}_ALREADY_ACTIVE_THIS_SESSION`;
  if((t==="PDA"||t==="PACK_TABLE")&&current.some(x=>x.state==="ACTIVE"&&x.resource_type===t))return t==="PDA"?"PDA_ALREADY_ACTIVE":"PACK_TABLE_ALREADY_ACTIVE";
  if(isUser(t)&&!duplicateUser){
    const [a,c]=await env.DB.batch([
      env.DB.prepare("SELECT 1 x FROM session_resource_assignments WHERE business_date=?1 AND resource_type=?2 AND resource_id=?3 AND state='USED' LIMIT 1").bind(s.business_date,t,id),
      env.DB.prepare("SELECT 1 x FROM resource_daily_consumption WHERE business_date=?1 AND resource_type=?2 AND resource_id=?3 LIMIT 1").bind(s.business_date,t,id),
    ]);
    if((a?.results?.length??0)>0||(c?.results?.length??0)>0)return t==="USER_PICK"?"USER_PICK_ALREADY_USED_TODAY":"USER_PACK_ALREADY_USED_TODAY";
  }
  return "";
}

function projectedLegacy(rows:AssignmentRow[],pos:PositionRow[]):{pda:string;pick:string;table:string;pack:string;choice:string}{
  const a=activeAssignments(rows);const latest=(t:ResourceType)=>[...a].reverse().find(x=>x.resource_type===t)?.resource_id??"";
  const activePos=pos.filter(x=>x.state==="ACTIVE").map(x=>x.position_key.toUpperCase());const choice=activePos.includes("PICK")?"PICK":activePos.includes("PACK")?"PACK":"KHONG";
  return{pda:latest("PDA"),pick:latest("USER_PICK"),table:latest("PACK_TABLE"),pack:latest("USER_PACK"),choice};
}

async function optionRows(env:Env,s:SessionRow,t:ResourceType,used:boolean):Promise<Array<{id:string;status_label:string}>>{
  const sql=used?
    `SELECT r.resource_id id,r.status_label FROM resources r LEFT JOIN resource_leases l ON l.resource_type=r.resource_type AND l.resource_id=r.resource_id WHERE r.resource_type=?1 AND r.available=1 AND l.resource_id IS NULL AND (EXISTS(SELECT 1 FROM session_resource_assignments a WHERE a.business_date=?2 AND a.resource_type=?1 AND a.resource_id=r.resource_id AND a.state='USED') OR EXISTS(SELECT 1 FROM resource_daily_consumption c WHERE c.business_date=?2 AND c.resource_type=?1 AND c.resource_id=r.resource_id)) ORDER BY r.resource_id`:
    `SELECT r.resource_id id,r.status_label FROM resources r LEFT JOIN resource_leases l ON l.resource_type=r.resource_type AND l.resource_id=r.resource_id WHERE r.resource_type=?1 AND r.available=1 AND l.resource_id IS NULL AND NOT EXISTS(SELECT 1 FROM session_resource_assignments a WHERE a.business_date=?2 AND a.resource_type=?1 AND a.resource_id=r.resource_id AND a.state='USED') AND NOT EXISTS(SELECT 1 FROM resource_daily_consumption c WHERE c.business_date=?2 AND c.resource_type=?1 AND c.resource_id=r.resource_id) ORDER BY r.resource_id`;
  const r=await env.DB.prepare(sql).bind(t,s.business_date).all<{id:string;status_label:string}>();return r.results??[];
}

export async function sessionResourceSnapshotV64(request:Request,env:Env):Promise<Response>{
  const auth=await authenticate(env.DB,env,request);if(!auth)return apiError("UNAUTHORIZED","AUTH",401);const b=await readJsonBody<Record<string,unknown>>(request,48_000),id=text(b.session_id,220),mnv=text(b.mnv,80);if(!id&&!mnv)return apiError("SESSION_REQUIRED","VALIDATION",400);const s=await resolveSession(env.DB,id,mnv);if(!s)return apiError("SESSION_NOT_FOUND","VALIDATION",404);
  const [aa,pp,pda,table,pickAvail,pickUsed,packAvail,packUsed]=await Promise.all([assignments(env.DB,s.session_id),positions(env.DB,s.session_id),optionRows(env,s,"PDA",false),optionRows(env,s,"PACK_TABLE",false),optionRows(env,s,"USER_PICK",false),optionRows(env,s,"USER_PICK",true),optionRows(env,s,"USER_PACK",false),optionRows(env,s,"USER_PACK",true)]);
  const emp=await env.DB.prepare("SELECT main_position FROM employees WHERE mnv=?1").bind(s.mnv).first<{main_position:string}>();
  return json({ok:true,session:s,positions:visiblePositions(pp),resource_assignments:visibleAssignments(aa),options:{pdas:pda,pack_tables:table,user_picks:pickAvail,user_picks_reissue:pickUsed,user_packs:packAvail,user_packs_reissue:packUsed},main_position:emp?.main_position??""});
}

export async function sessionResourceMutateV64(request:Request,env:Env):Promise<Response>{
  const auth=await authenticate(env.DB,env,request);if(!auth)return apiError("UNAUTHORIZED","AUTH",401);const b=await readJsonBody<Record<string,unknown>>(request,160_000),id=text(b.session_id,220),mnv=text(b.mnv,80),idem=text(b.idempotency_key,220),expected=Number(b.expected_version),raw=Array.isArray(b.operations)?b.operations as Operation[]:[];if((!id&&!mnv)||!idem||!Number.isInteger(expected)||!raw.length||raw.length>30)return apiError("SESSION_RESOURCE_MUTATION_FIELDS_REQUIRED","VALIDATION",400);
  const prior=await existing(env,idem);if(prior){const fake=new Request(request.url,{method:"POST",headers:request.headers,body:JSON.stringify({session_id:prior.entity_id})});return sessionResourceSnapshotV64(fake,env);}
  const s=await resolveSession(env.DB,id,mnv);if(!s)return apiError("SESSION_NOT_FOUND","VALIDATION",404);if(s.state!=="ACTIVE")return apiError("SESSION_NOT_ACTIVE","CONFLICT",409);if(s.version!==expected)return apiError("SESSION_CHANGED","CONFLICT",409,false,{current_version:s.version});
  const beforeA=await assignments(env.DB,s.session_id),beforeP=await positions(env.DB,s.session_id),workA=clone(beforeA),workP=clone(beforeP),stmts:D1PreparedStatement[]=[];let nextShift=s.shift;const normalized:Record<string,unknown>[]=[];
  for(const rawOp of raw){
    const op=text(rawOp.op,40).toUpperCase();
    if(op==="UPDATE_SHIFT") {const shift=text(rawOp.shift,40);if(!validShift(shift))return apiError("SHIFT_INVALID","VALIDATION",400);nextShift=shift;normalized.push({op,shift});continue;}
    if(op==="ADD_POSITION"){
      const key=text(rawOp.position_key,100).toUpperCase(),label=text(rawOp.position_label,180);if(!key||!label)return apiError("POSITION_REQUIRED","VALIDATION",400);if(workP.some(x=>x.state==="ACTIVE"&&x.position_key.toUpperCase()===key))continue;const row:PositionRow={position_assignment_id:crypto.randomUUID(),session_id:s.session_id,mnv:s.mnv,business_date:s.business_date,position_key:key,position_label:label,state:"ACTIVE",started_at:"",ended_at:null,start_event_id:"",end_event_id:null,reason:""};workP.push(row);normalized.push({op,position_key:key,position_label:label});continue;
    }
    if(op==="REMOVE_POSITION"){
      const key=text(rawOp.position_key,100).toUpperCase(),reason=text(rawOp.reason,500);if(!key||reason.length<2)return apiError("POSITION_REMOVE_FIELDS_REQUIRED","VALIDATION",400);const current=workP.find(x=>x.state==="ACTIVE"&&x.position_key.toUpperCase()===key);if(!current)return apiError("POSITION_NOT_ACTIVE","VALIDATION",409);const related=workA.some(x=>x.state==="ACTIVE"&&(x.position_key.toUpperCase()===key||positionForType(x.resource_type)===key));if(related)return apiError("POSITION_HAS_ACTIVE_RESOURCES","CONFLICT",409);current.state="USED";current.reason=reason;normalized.push({op,position_key:key,reason});continue;
    }
    if(op==="ADD_RESOURCE"){
      const t=typeOf(rawOp.resource_type),rid=text(rawOp.resource_id,220);if(!t||!rid)return apiError("RESOURCE_REQUIRED","VALIDATION",400);const err=await ensureActivatable(env,s,t,rid,Boolean(rawOp.duplicate_user),workA);if(err)return apiError(err,"RESOURCE",409);const key=text(rawOp.position_key,100).toUpperCase()||positionForType(t);if(!workP.some(x=>x.state==="ACTIVE"&&x.position_key.toUpperCase()===key)){const label=key==="PICK"?"Pick":key==="PACK"?"Pack":key;workP.push({position_assignment_id:crypto.randomUUID(),session_id:s.session_id,mnv:s.mnv,business_date:s.business_date,position_key:key,position_label:label,state:"ACTIVE",started_at:"",ended_at:null,start_event_id:"",end_event_id:null,reason:""});normalized.push({op:"ADD_POSITION",position_key:key,position_label:label,auto:true});}
      workA.push({assignment_id:crypto.randomUUID(),session_id:s.session_id,mnv:s.mnv,business_date:s.business_date,resource_type:t,resource_id:rid,position_key:key,state:"ACTIVE",acquired_at:"",released_at:null,acquire_event_id:"",release_event_id:null,release_reason:"",release_disposition:"",context_json:JSON.stringify(t==="PDA"?{pda_enter_status:text(rawOp.pda_enter_status,180)}:{})});normalized.push({op,resource_type:t,resource_id:rid,position_key:key,duplicate_user:Boolean(rawOp.duplicate_user)});continue;
    }
    if(op==="REMOVE_RESOURCE"||op==="REPLACE_RESOURCE"){
      const aid=text(rawOp.assignment_id,220),reason=text(rawOp.reason,500),disp=text(rawOp.disposition,20).toUpperCase() as Disposition;if(!aid||reason.length<2||!["USED","AVAILABLE"].includes(disp))return apiError("RESOURCE_RELEASE_FIELDS_REQUIRED","VALIDATION",400);const old=workA.find(x=>x.assignment_id===aid&&x.state==="ACTIVE");if(!old)return apiError("RESOURCE_ASSIGNMENT_NOT_ACTIVE","CONFLICT",409);old.state=disp==="USED"?"USED":"VOID";old.release_reason=reason;old.release_disposition=disp;normalized.push({op:"REMOVE_RESOURCE",assignment_id:aid,resource_type:old.resource_type,resource_id:old.resource_id,disposition:disp,reason});
      if(op==="REPLACE_RESOURCE"){
        const rid=text(rawOp.new_resource_id,220);if(!rid)return apiError("NEW_RESOURCE_REQUIRED","VALIDATION",400);const err=await ensureActivatable(env,s,old.resource_type,rid,Boolean(rawOp.duplicate_user),workA);if(err)return apiError(err,"RESOURCE",409);workA.push({assignment_id:crypto.randomUUID(),session_id:s.session_id,mnv:s.mnv,business_date:s.business_date,resource_type:old.resource_type,resource_id:rid,position_key:old.position_key||positionForType(old.resource_type),state:"ACTIVE",acquired_at:"",released_at:null,acquire_event_id:"",release_event_id:null,release_reason:"",release_disposition:"",context_json:old.resource_type==="PDA"?JSON.stringify({pda_enter_status:text(rawOp.pda_enter_status,180)}):"{}"});normalized.push({op:"ADD_RESOURCE",resource_type:old.resource_type,resource_id:rid,position_key:old.position_key,duplicate_user:Boolean(rawOp.duplicate_user),replacement_for:aid});
      }
      continue;
    }
    return apiError("SESSION_RESOURCE_OPERATION_UNSUPPORTED","VALIDATION",400,false,{op});
  }
  const legacy=projectedLegacy(workA,workP),newVersion=s.version+1;let built:{event:EventRow;expectedSeq:number};try{built=await buildEvent(env,auth,s,"RESOURCE_CHANGE",{mnv:s.mnv,mutation_kind:"MULTI",audit_note:text(b.audit_note,500),operations:normalized,before:{shift:s.shift,positions:visiblePositions(beforeP),resource_assignments:visibleAssignments(beforeA)},after:{shift:nextShift,positions:visiblePositions(workP),resource_assignments:visibleAssignments(workA)}},idem,newVersion);}catch(e){return apiError(String(e).replace(/^Error: /,""),"CONFLICT",409);}
  const e=built.event;stmts.push(...eventStmts(env.DB,e,built.expectedSeq));
  for(const p of workP){const prior=beforeP.find(x=>x.position_assignment_id===p.position_assignment_id);if(!prior){stmts.push(env.DB.prepare("INSERT INTO session_positions(position_assignment_id,session_id,mnv,business_date,position_key,position_label,state,started_at,start_event_id,reason) VALUES(?1,?2,?3,?4,?5,?6,'ACTIVE',?7,?8,'')").bind(p.position_assignment_id,s.session_id,s.mnv,s.business_date,p.position_key,p.position_label,e.committed_at,e.event_id));}else if(prior.state!==p.state){stmts.push(env.DB.prepare("UPDATE session_positions SET state=?1,ended_at=?2,end_event_id=?3,reason=?4 WHERE position_assignment_id=?5 AND state='ACTIVE'").bind(p.state,e.committed_at,e.event_id,p.reason,p.position_assignment_id));}}
  for(const a of workA){const prior=beforeA.find(x=>x.assignment_id===a.assignment_id);if(!prior){stmts.push(env.DB.prepare("INSERT INTO session_resource_assignments(assignment_id,session_id,mnv,business_date,resource_type,resource_id,position_key,state,acquired_at,acquire_event_id,context_json) VALUES(?1,?2,?3,?4,?5,?6,?7,'ACTIVE',?8,?9,?10)").bind(a.assignment_id,s.session_id,s.mnv,s.business_date,a.resource_type,a.resource_id,a.position_key,e.committed_at,e.event_id,a.context_json));stmts.push(env.DB.prepare("INSERT INTO resource_leases(resource_type,resource_id,session_id,mnv,business_date,acquired_event_id,acquired_at) VALUES(?1,?2,?3,?4,?5,?6,?7)").bind(a.resource_type,a.resource_id,s.session_id,s.mnv,s.business_date,e.event_id,e.committed_at));}else if(prior.state!==a.state){stmts.push(env.DB.prepare("UPDATE session_resource_assignments SET state=?1,released_at=?2,release_event_id=?3,release_reason=?4,release_disposition=?5 WHERE assignment_id=?6 AND state='ACTIVE'").bind(a.state,e.committed_at,e.event_id,a.release_reason,a.release_disposition,a.assignment_id));stmts.push(env.DB.prepare("DELETE FROM resource_leases WHERE resource_type=?1 AND resource_id=?2 AND session_id=?3").bind(a.resource_type,a.resource_id,s.session_id));if(a.state==="USED"&&isUser(a.resource_type))stmts.push(env.DB.prepare("INSERT OR IGNORE INTO resource_daily_consumption(business_date,resource_type,resource_id,mnv,first_event_id) VALUES(?1,?2,?3,?4,?5)").bind(s.business_date,a.resource_type,a.resource_id,s.mnv,e.event_id));if(a.state==="VOID"&&isUser(a.resource_type))stmts.push(env.DB.prepare("DELETE FROM resource_daily_consumption WHERE business_date=?1 AND resource_type=?2 AND resource_id=?3 AND mnv=?4 AND NOT EXISTS(SELECT 1 FROM session_resource_assignments x WHERE x.business_date=?1 AND x.resource_type=?2 AND x.resource_id=?3 AND x.state='USED')").bind(s.business_date,a.resource_type,a.resource_id,s.mnv));}}
  let pdaStatus:string|null=s.pda_enter_status;if(legacy.pda){const activePda=[...workA].reverse().find(x=>x.state==="ACTIVE"&&x.resource_type==="PDA");if(activePda){try{const c=JSON.parse(activePda.context_json||"{}");pdaStatus=text(c.pda_enter_status,180)||pdaStatus;}catch{}}if(!pdaStatus)pdaStatus=(await env.DB.prepare("SELECT status_label FROM resources WHERE resource_type='PDA' AND resource_id=?1").bind(legacy.pda).first<{status_label:string}>())?.status_label??null;}else pdaStatus=null;
  stmts.push(env.DB.prepare("UPDATE attendance_sessions SET shift=?1,work_choice=?2,pda_serial=?3,user_pick=?4,pack_table=?5,user_pack=?6,pda_enter_status=?7,pda_exit_status=NULL,version=?8,updated_at=?9 WHERE session_id=?10 AND version=?11 AND state='ACTIVE'").bind(nextShift,legacy.choice,legacy.pda||null,legacy.pick||null,legacy.table||null,legacy.pack||null,pdaStatus,newVersion,e.committed_at,s.session_id,s.version));
  try{await env.DB.batch(stmts);}catch(x){const m=String(x);return apiError(m.includes("session_version_claims")?"SESSION_CHANGED":"SESSION_RESOURCE_MUTATION_CONFLICT","CONFLICT",409,true,undefined,m.slice(0,220));}
  await invalidate(env,e);const fake=new Request(request.url,{method:"POST",headers:request.headers,body:JSON.stringify({session_id:s.session_id})});return sessionResourceSnapshotV64(fake,env);
}

export async function sessionEnterV64(request:Request,env:Env):Promise<Response>{
  const auth=await authenticate(env.DB,env,request);if(!auth)return apiError("UNAUTHORIZED","AUTH",401);const b=await readJsonBody<Record<string,unknown>>(request,160_000),mnv=text(b.mnv,80),shift=text(b.shift,40),idem=text(b.idempotency_key,220),positionInput=Array.isArray(b.positions)?b.positions as Array<Record<string,unknown>>:[],resourceInput=Array.isArray(b.resources)?b.resources as Array<Record<string,unknown>>:[];if(!mnv||!validShift(shift)||!idem)return apiError("ATTENDANCE_FIELDS_REQUIRED","VALIDATION",400);const prior=await existing(env,idem);if(prior){const fake=new Request(request.url,{method:"POST",headers:request.headers,body:JSON.stringify({session_id:prior.entity_id})});return sessionResourceSnapshotV64(fake,env);}
  const date=bangkokToday();try{await ensureCurrentBangkokBusinessDate(env.DB,date);}catch{return apiError("BUSINESS_DATE_NOT_BOOTSTRAPPED","INTEGRITY",503,true);}
  const active=await activeByMnv(env.DB,mnv);if(active)return apiError("ATTENDANCE_ALREADY_ACTIVE","CONFLICT",409,false,{session_id:active.session_id,business_date:active.business_date});const same=await env.DB.prepare("SELECT session_id,state FROM attendance_sessions WHERE mnv=?1 AND business_date=?2").bind(mnv,date).first<{session_id:string;state:string}>();if(same)return apiError(same.state==="ENDED"?"ATTENDANCE_ALREADY_ENDED":"ATTENDANCE_ALREADY_EXISTS","CONFLICT",409,false,{session_id:same.session_id});const emp=await env.DB.prepare("SELECT main_position FROM employees WHERE mnv=?1").bind(mnv).first<{main_position:string}>();if(!emp)return apiError("EMPLOYEE_NOT_FOUND","VALIDATION",404);
  const sid=crypto.randomUUID(),at=nowIso(),s:SessionRow={session_id:sid,mnv,business_date:date,shift,work_choice:"KHONG",state:"ACTIVE",pda_serial:null,user_pick:null,pack_table:null,user_pack:null,pda_enter_status:null,pda_exit_status:null,resource_note:text(b.resource_note,500),enter_at:at,exit_at:null,entered_by:auth.login_id,exited_by:null,version:0};const pp:PositionRow[]=[],aa:AssignmentRow[]=[];
  for(const x of positionInput){const key=text(x.position_key,100).toUpperCase(),label=text(x.position_label,180);if(key&&label&&!pp.some(p=>p.position_key===key))pp.push({position_assignment_id:crypto.randomUUID(),session_id:sid,mnv,business_date:date,position_key:key,position_label:label,state:"ACTIVE",started_at:at,ended_at:null,start_event_id:"",end_event_id:null,reason:""});}
  for(const x of resourceInput){const t=typeOf(x.resource_type),rid=text(x.resource_id,220);if(!t||!rid)return apiError("RESOURCE_REQUIRED","VALIDATION",400);const key=text(x.position_key,100).toUpperCase()||positionForType(t);if(!pp.some(p=>p.position_key===key))pp.push({position_assignment_id:crypto.randomUUID(),session_id:sid,mnv,business_date:date,position_key:key,position_label:key==="PICK"?"Pick":"Pack",state:"ACTIVE",started_at:at,ended_at:null,start_event_id:"",end_event_id:null,reason:""});const err=await ensureActivatable(env,s,t,rid,Boolean(x.duplicate_user),aa);if(err)return apiError(err,"RESOURCE",409);aa.push({assignment_id:crypto.randomUUID(),session_id:sid,mnv,business_date:date,resource_type:t,resource_id:rid,position_key:key,state:"ACTIVE",acquired_at:at,released_at:null,acquire_event_id:"",release_event_id:null,release_reason:"",release_disposition:"",context_json:JSON.stringify(t==="PDA"?{pda_enter_status:text(x.pda_enter_status,180)}:{})});}
  const legacy=projectedLegacy(aa,pp),authLike=auth as unknown as AuthLike;let built:{event:EventRow;expectedSeq:number};try{built=await buildEvent(env,authLike,s,"ATTENDANCE_ENTER",{mnv,shift,positions:pp,resource_assignments:aa,main_position:emp.main_position,resource_note:s.resource_note,pda_serial:legacy.pda,user_pick:legacy.pick,pack_table:legacy.table,user_pack:legacy.pack,work_choice:legacy.choice},idem,1);}catch(e){return apiError(String(e).replace(/^Error: /,""),"CONFLICT",409);}
  const e=built.event,stmts=eventStmts(env.DB,e,built.expectedSeq);let pdaStatus:string|null=null;if(legacy.pda){const r=await env.DB.prepare("SELECT status_label FROM resources WHERE resource_type='PDA' AND resource_id=?1").bind(legacy.pda).first<{status_label:string}>();pdaStatus=text(resourceInput.find(x=>typeOf(x.resource_type)==="PDA")?.pda_enter_status,180)||r?.status_label||null;}
  stmts.push(env.DB.prepare("INSERT INTO attendance_sessions(session_id,mnv,business_date,shift,work_choice,state,pda_serial,user_pick,pack_table,user_pack,pda_enter_status,resource_note,enter_at,entered_by,version,updated_at) VALUES(?1,?2,?3,?4,?5,'ACTIVE',?6,?7,?8,?9,?10,?11,?12,?13,1,?12)").bind(sid,mnv,date,shift,legacy.choice,legacy.pda||null,legacy.pick||null,legacy.table||null,legacy.pack||null,pdaStatus,s.resource_note,e.committed_at,auth.login_id));
  for(const p of pp)stmts.push(env.DB.prepare("INSERT INTO session_positions(position_assignment_id,session_id,mnv,business_date,position_key,position_label,state,started_at,start_event_id,reason) VALUES(?1,?2,?3,?4,?5,?6,'ACTIVE',?7,?8,'')").bind(p.position_assignment_id,sid,mnv,date,p.position_key,p.position_label,e.committed_at,e.event_id));
  for(const a of aa){stmts.push(env.DB.prepare("INSERT INTO session_resource_assignments(assignment_id,session_id,mnv,business_date,resource_type,resource_id,position_key,state,acquired_at,acquire_event_id,context_json) VALUES(?1,?2,?3,?4,?5,?6,?7,'ACTIVE',?8,?9,?10)").bind(a.assignment_id,sid,mnv,date,a.resource_type,a.resource_id,a.position_key,e.committed_at,e.event_id,a.context_json));stmts.push(env.DB.prepare("INSERT INTO resource_leases(resource_type,resource_id,session_id,mnv,business_date,acquired_event_id,acquired_at) VALUES(?1,?2,?3,?4,?5,?6,?7)").bind(a.resource_type,a.resource_id,sid,mnv,date,e.event_id,e.committed_at));}
  try{await env.DB.batch(stmts);}catch(x){return apiError("ATTENDANCE_ENTER_CONFLICT","CONFLICT",409,false,undefined,String(x).slice(0,220));}await invalidate(env,e);const fake=new Request(request.url,{method:"POST",headers:request.headers,body:JSON.stringify({session_id:sid})});return sessionResourceSnapshotV64(fake,env);
}

export async function sessionExitV64(request:Request,env:Env):Promise<Response>{
  const auth=await authenticate(env.DB,env,request);if(!auth)return apiError("UNAUTHORIZED","AUTH",401);const b=await readJsonBody<Record<string,unknown>>(request,64_000),id=text(b.session_id,220),mnv=text(b.mnv,80),idem=text(b.idempotency_key,220),expected=Number(b.expected_version),pdaExit=text(b.pda_exit_status,180);if((!id&&!mnv)||!idem||!Number.isInteger(expected))return apiError("SESSION_EXIT_FIELDS_REQUIRED","VALIDATION",400);const prior=await existing(env,idem);if(prior)return json({ok:true,duplicate:true,event:prior,session:await byId(env.DB,prior.entity_id)});const s=await resolveSession(env.DB,id,mnv);if(!s||s.state!=="ACTIVE")return apiError("SESSION_NOT_ACTIVE","CONFLICT",409);if(s.version!==expected)return apiError("SESSION_CHANGED","CONFLICT",409,false,{current_version:s.version});const open=(await env.DB.prepare("SELECT COUNT(*) n FROM labor_sessions WHERE mnv=?1 AND business_date=?2 AND state='OPEN'").bind(s.mnv,s.business_date).first<{n:number}>())?.n??0;if(open>0)return apiError("OPEN_LABOR_BLOCKS_EXIT","CONFLICT",409);
  const aa=await assignments(env.DB,s.session_id),pp=await positions(env.DB,s.session_id),active=activeAssignments(aa),pda=active.find(x=>x.resource_type==="PDA");if(pda){let expectedStatus=text(s.pda_enter_status,180);try{const c=JSON.parse(pda.context_json||"{}");expectedStatus=text(c.pda_enter_status,180)||expectedStatus;}catch{}if(!expectedStatus)expectedStatus=(await env.DB.prepare("SELECT status_label FROM resources WHERE resource_type='PDA' AND resource_id=?1").bind(pda.resource_id).first<{status_label:string}>())?.status_label??"";if(!pdaExit)return apiError("PDA_EXIT_STATUS_REQUIRED","VALIDATION",400);if(expectedStatus&&pdaExit!==expectedStatus)return apiError("PDA_STATUS_MISMATCH_NOTIFY_SPECIALIST","CONFLICT",409,false,{expected_status:expectedStatus,current_status:pdaExit,pda_serial:pda.resource_id});}
  const newVersion=s.version+1;let built:{event:EventRow;expectedSeq:number};try{built=await buildEvent(env,auth as unknown as AuthLike,s,"ATTENDANCE_EXIT",{mnv:s.mnv,shift:s.shift,pda_exit_status:pdaExit,positions:visiblePositions(pp),resource_assignments:visibleAssignments(aa)},idem,newVersion);}catch(e){return apiError(String(e).replace(/^Error: /,""),"CONFLICT",409);}const e=built.event,stmts=eventStmts(env.DB,e,built.expectedSeq);
  for(const a of active){stmts.push(env.DB.prepare("UPDATE session_resource_assignments SET state='USED',released_at=?1,release_event_id=?2,release_reason='Ra ca',release_disposition='USED' WHERE assignment_id=?3 AND state='ACTIVE'").bind(e.committed_at,e.event_id,a.assignment_id));if(isUser(a.resource_type))stmts.push(env.DB.prepare("INSERT OR IGNORE INTO resource_daily_consumption(business_date,resource_type,resource_id,mnv,first_event_id) VALUES(?1,?2,?3,?4,?5)").bind(s.business_date,a.resource_type,a.resource_id,s.mnv,e.event_id));}
  for(const p of pp.filter(x=>x.state==="ACTIVE"))stmts.push(env.DB.prepare("UPDATE session_positions SET state='USED',ended_at=?1,end_event_id=?2,reason='Ra ca' WHERE position_assignment_id=?3 AND state='ACTIVE'").bind(e.committed_at,e.event_id,p.position_assignment_id));stmts.push(env.DB.prepare("DELETE FROM resource_leases WHERE session_id=?1").bind(s.session_id));stmts.push(env.DB.prepare("UPDATE attendance_sessions SET state='ENDED',exit_at=?1,exited_by=?2,pda_exit_status=?3,version=?4,updated_at=?1 WHERE session_id=?5 AND version=?6 AND state='ACTIVE'").bind(e.committed_at,auth.login_id,pdaExit||null,newVersion,s.session_id,s.version));
  try{await env.DB.batch(stmts);}catch(x){const m=String(x);return apiError(m.includes("session_version_claims")?"SESSION_CHANGED":"SESSION_EXIT_CONFLICT","CONFLICT",409,true,undefined,m.slice(0,220));}await invalidate(env,e);return json({ok:true,event:e,session:await byId(env.DB,s.session_id),resource_assignments:visibleAssignments((await assignments(env.DB,s.session_id))),positions:visiblePositions(await positions(env.DB,s.session_id))},201);
}
