import { authenticate } from "./auth";
import { apiError, json, nowIso } from "./util";

type Namespace="employees"|"catalogs"|"accounts"|"pda"|"user_pick"|"pack_table"|"user_pack";
const NS=new Set<Namespace>(["employees","catalogs","accounts","pda","user_pick","pack_table","user_pack"]);

export async function syncStatusV2(request:Request,env:Env):Promise<Response>{
  const auth=await authenticate(env.DB,env,request);if(!auth)return apiError("UNAUTHORIZED","AUTH",401);const now=nowIso(),cutoff=new Date(Date.now()-15*60_000).toISOString();
  const results=await env.DB.batch([
    env.DB.prepare(`WITH recent AS (SELECT business_date,sequence_no FROM business_dates ORDER BY sequence_no DESC LIMIT 7),
      current_authority AS (SELECT authority_epoch,service_generation FROM authority_state WHERE singleton_id=1)
      SELECT r.business_date,r.sequence_no,COALESCE(d.revision,0) revision
      FROM recent r CROSS JOIN current_authority a
      LEFT JOIN day_revision_state d ON d.business_date=r.business_date AND d.authority_epoch=a.authority_epoch AND d.service_generation=a.service_generation
      ORDER BY r.sequence_no DESC`),
    env.DB.prepare("SELECT authority_epoch,authority_seq,mode,scope,service_generation,updated_at FROM authority_state WHERE singleton_id=1"),
    env.DB.prepare("SELECT namespace,revision,updated_at FROM revision_state ORDER BY namespace"),
    env.DB.prepare("SELECT target_kind,target_identity,schema_version,state,checkpoint,pending_count,retry_count,last_attempt_at,last_success_at,last_error_class,updated_at FROM replication_status WHERE singleton_id=1"),
    env.DB.prepare(`INSERT INTO client_devices(device_id,login_id,platform,app_version,channel,authority_epoch,authority_seq,service_generation,last_seen_at,last_online_at,metadata_json)
      SELECT ?1,?2,'ANDROID','UNKNOWN','UNKNOWN',a.authority_epoch,a.authority_seq,a.service_generation,?3,?3,'{}' FROM authority_state a WHERE a.singleton_id=1
      ON CONFLICT(device_id) DO UPDATE SET login_id=excluded.login_id,authority_epoch=excluded.authority_epoch,authority_seq=excluded.authority_seq,service_generation=excluded.service_generation,last_seen_at=excluded.last_seen_at,last_online_at=excluded.last_online_at
      WHERE client_devices.last_seen_at<?4`).bind(auth.device_id,auth.login_id,now,cutoff),
  ]);
  const authority=results[1]?.results?.[0] as Record<string,unknown>|undefined;if(!authority)return apiError("AUTHORITY_STATE_MISSING","INTEGRITY",503);const window=(results[0]?.results??[]).map(r=>({business_date:String((r as Record<string,unknown>).business_date||""),sequence_no:Number((r as Record<string,unknown>).sequence_no||0),revision:Number((r as Record<string,unknown>).revision||0)}));const master:Record<string,number>={};for(const r of results[2]?.results??[])master[String((r as Record<string,unknown>).namespace)]=Number((r as Record<string,unknown>).revision||0);const rep=(results[3]?.results?.[0]??{}) as Record<string,unknown>,metas=results.map(x=>x?.meta).filter(Boolean),telemetry={d1_duration_ms:metas.reduce((n,m)=>n+Number(m?.duration||0),0),d1_rows_read:metas.reduce((n,m)=>n+Number(m?.rows_read||0),0),d1_rows_written:metas.reduce((n,m)=>n+Number(m?.rows_written||0),0),served_by_region:String(metas[0]?.served_by_region||""),served_by_primary:Boolean(metas[0]?.served_by_primary)};
  return json({ok:true,contract:"LOCAL_FIRST_REVISION_V1",authority,service_generation:authority.service_generation,server_seq:authority.authority_seq,business_window:window,business_dates:window,master_revisions:master,replication:rep,realtime:{protocol:"INVALIDATION_V1",ticket_endpoint:"/v1/realtime/ticket",ws_endpoint:"/v1/realtime"},delta:{day_endpoint:"/v1/delta/day",master_endpoint:"/v1/delta/master",authority_endpoint:"/v1/delta"},service_telemetry:telemetry});
}
async function allowedDate(db:D1Database,date:string,superadmin:boolean):Promise<boolean>{if(superadmin)return true;const r=await db.prepare("SELECT 1 x FROM (SELECT business_date FROM business_dates ORDER BY sequence_no DESC LIMIT 7) WHERE business_date=?1").bind(date).first();return !!r;}
export async function dayDeltaV2(request:Request,env:Env):Promise<Response>{const auth=await authenticate(env.DB,env,request);if(!auth)return apiError("UNAUTHORIZED","AUTH",401);const u=new URL(request.url),date=String(u.searchParams.get("business_date")||""),after=Number(u.searchParams.get("after_revision")||0);if(!/^\d{4}-\d{2}-\d{2}$/.test(date))return apiError("BUSINESS_DATE_INVALID","VALIDATION",400);if(!await allowedDate(env.DB,date,auth.role==="SUPERADMIN"&&u.searchParams.get("client_source")==="WEB"))return apiError("BUSINESS_DATE_OUTSIDE_VIEW_WINDOW","PERMISSION",403);const r=await env.DB.prepare("SELECT * FROM events WHERE business_date=?1 AND authority_seq>?2 ORDER BY authority_seq LIMIT 501").bind(date,Math.max(0,after)).all(),all=r.results??[],events=all.slice(0,500),revision=events.length?Number((events[events.length-1] as Record<string,unknown>).authority_seq||after):after;return json({ok:true,business_date:date,from_revision:after,to_revision:revision,events,has_more:all.length>500,service_telemetry:{d1_duration_ms:r.meta.duration,d1_rows_read:r.meta.rows_read,served_by_region:r.meta.served_by_region??"",served_by_primary:r.meta.served_by_primary??false}});}
export async function masterDeltaV2(request:Request,env:Env):Promise<Response>{const auth=await authenticate(env.DB,env,request);if(!auth)return apiError("UNAUTHORIZED","AUTH",401);const u=new URL(request.url),ns=String(u.searchParams.get("namespace")||"") as Namespace,after=Number(u.searchParams.get("after_revision")||0);if(!NS.has(ns))return apiError("MASTER_NAMESPACE_INVALID","VALIDATION",400);const rev=(await env.DB.prepare("SELECT revision FROM revision_state WHERE namespace=?1").bind(ns).first<{revision:number}>())?.revision??0;if(after===rev)return json({ok:true,namespace:ns,from_revision:after,to_revision:rev,changed:false,rows:[]});let rows:unknown[]=[];if(ns==="employees")rows=(await env.DB.prepare("SELECT mnv,full_name,phone,main_position,supplier,department,site,warehouse,start_date,note FROM employees ORDER BY mnv").all()).results??[];else if(ns==="catalogs")rows=(await env.DB.prepare("SELECT namespace,ordinal,value FROM catalog_values ORDER BY namespace,ordinal").all()).results??[];else if(ns==="pack_table")rows=(await env.DB.prepare("SELECT pack_table,shift,user_pack,label,available FROM resource_pack_map ORDER BY pack_table,shift").all()).results??[];else if(ns==="accounts")rows=(await env.DB.prepare("SELECT login_id,role,display_name,position,status FROM accounts WHERE login_id=?1").bind(auth.login_id).all()).results??[];else{const type=ns==="pda"?"PDA":ns==="user_pick"?"USER_PICK":"USER_PACK";rows=(await env.DB.prepare("SELECT resource_id,status_label,available,metadata_json FROM resources WHERE resource_type=?1 ORDER BY resource_id").bind(type).all()).results??[];}return json({ok:true,namespace:ns,from_revision:after,to_revision:rev,changed:true,mode:"NAMESPACE_SNAPSHOT_ON_REVISION_CHANGE",rows});}
