import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";
test("DR uses canonical service core instead of duplicated business rules",()=>{const h=fs.readFileSync(new URL("../src/handler.ts",import.meta.url),"utf8");assert.match(h,/service\/src\/core/);assert.match(h,/service\/src\/legacy/);assert.doesNotMatch(h,/SUPABASE/i)});
test("writer is fenced unless ACTIVE_WRITE",()=>{const h=fs.readFileSync(new URL("../src/handler.ts",import.meta.url),"utf8");assert.match(h,/DR_WRITER_MODE!==\"ACTIVE_WRITE\"/);assert.match(h,/DR_PASSIVE_FENCED/)});

test("active DR exposes Android runtime read sync and session routes",()=>{const h=fs.readFileSync(new URL("../src/handler.ts",import.meta.url),"utf8");for(const p of ["/v1/mobile/read","/v1/legacy-sync","/v1/session/enter-v2","/v1/session/resources/snapshot","/v1/session/resources/mutate","/v1/session/exit-v2"])assert.match(h,new RegExp(p.replaceAll("/","\\/")));});
test("DR session exchange reuses canonical mobile helper",()=>{const h=fs.readFileSync(new URL("../src/handler.ts",import.meta.url),"utf8");assert.match(h,/exchangeGasSession, mobileRead/);});

test("DR environment identity is mandatory and cross-environment requests fail closed",()=>{const h=fs.readFileSync(new URL("../src/handler.ts",import.meta.url),"utf8"),d=fs.readFileSync(new URL("../src/deno.ts",import.meta.url),"utf8"),r=fs.readFileSync(new URL("../src/render.ts",import.meta.url),"utf8");for(const s of [d,r]){assert.match(s,/required\("ENVIRONMENT_ID"\)/);assert.match(s,/required\("SERVICE_AUDIENCE"\)/)}assert.match(h,/DR_ENVIRONMENT_CONFIG_INVALID/);assert.match(h,/ENVIRONMENT_ID_REQUIRED/);assert.match(h,/ENVIRONMENT_MISMATCH/);assert.match(h,/SERVICE_AUDIENCE_MISMATCH/);assert.doesNotMatch(h,/ENVIRONMENT_ID:String\(e\.ENVIRONMENT_ID\|\|"BETA"\)/);assert.match(h,/\/environment\.json/);});

test("DR requires environment-scoped GAS bindings for session/fallback parity",()=>{for(const f of ["deno.ts","render.ts"]){const s=fs.readFileSync(new URL("../src/"+f,import.meta.url),"utf8");for(const k of ["GAS_API_URL","OUTBOUND_GAS_API_URL","DR_GAS_API_URL","DR_TARGET_ID"])assert.match(s,new RegExp('required\\("'+k+'"\\)'))}});
