const DR={OWNER:'tam95.supra@gmail.com',ALLOWED:['Danh mục','LỊCH SỬ NGHIỆP VỤ','DANH SÁCH PDA','DANH SÁCH USER PICK','DANH SÁCH BÀN PACK','DANH SÁCH USER PACK','DANH SÁCH NHÂN SỰ','RA - VÀO TRONG CA','CÔNG NHẬT','Danh sách Admin']};
function json_(x){return ContentService.createTextOutput(JSON.stringify(x)).setMimeType(ContentService.MimeType.JSON);}
function fold_(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().trim();}
function sha_(v){return Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,String(v||''),Utilities.Charset.UTF_8).map(function(b){return ('0'+((b+256)%256).toString(16)).slice(-2);}).join('');}
function ss_(){const s=SpreadsheetApp.getActiveSpreadsheet();if(!s)throw new Error('BOUND_SHEET_REQUIRED');return s;}
function ownerFile_(token){const id=ss_().getId(),r=UrlFetchApp.fetch('https://www.googleapis.com/drive/v3/files/'+encodeURIComponent(id)+'?fields=id,mimeType,owners(emailAddress)',{muteHttpExceptions:true,headers:{Authorization:'Bearer '+String(token||'')}});if(r.getResponseCode()<200||r.getResponseCode()>=300)return false;let j={};try{j=JSON.parse(r.getContentText()||'{}');}catch(_){return false;}return j.id===id&&j.mimeType==='application/vnd.google-apps.spreadsheet'&&(j.owners||[]).some(function(x){return fold_(x.emailAddress)===fold_(DR.OWNER);});}
function provision_(b){const p=PropertiesService.getScriptProperties(),token=String(b.google_access_token||''),secret=String(b.bridge_secret||'');if(!token||secret.length<32||!ownerFile_(token))return {ok:false,error:'PROVISION_OWNER_PROOF_FAILED'};if(p.getProperty('DR_PROVISIONED')==='1')return p.getProperty('DR_SHEET_ID')===ss_().getId()?{ok:true,idempotent:true,environment_id:'STABLE',kind:'DR'}:{ok:false,error:'PROVISION_LOCK_MISMATCH'};p.setProperties({DR_PROVISIONED:'1',DR_ENV:'STABLE',DR_SHEET_ID:ss_().getId(),DR_BRIDGE_SECRET:secret},false);return {ok:true,idempotent:false,environment_id:'STABLE',kind:'DR',writer_scope:'BOUND_CURRENT_ONLY'};}
function auth_(b){const p=PropertiesService.getScriptProperties(),e=String(p.getProperty('DR_BRIDGE_SECRET')||''),g=String(b._bridge_secret||'');return p.getProperty('DR_PROVISIONED')==='1'&&e.length>=32&&g.length>=32&&sha_(e)===sha_(g)&&String(b._environment_id||'')==='STABLE';}
function bridge_(b){if(!auth_(b))return {ok:false,error:'BRIDGE_UNAUTHORIZED'};if(String(b.operation||'')!=='replace_table')return {ok:false,error:'BRIDGE_OPERATION_UNKNOWN'};const name=String(b.sheet||'');if(DR.ALLOWED.indexOf(name)<0)return {ok:false,error:'DR_SHEET_REJECTED'};const headers=Array.isArray(b.headers)?b.headers:[],rows=Array.isArray(b.rows)?b.rows:[],ss=ss_();let sh=ss.getSheetByName(name);if(!sh)sh=ss.insertSheet(name);const cols=Math.max(1,headers.length),needRows=Math.max(100,rows.length+1);if(sh.getMaxColumns()<cols)sh.insertColumnsAfter(sh.getMaxColumns(),cols-sh.getMaxColumns());if(sh.getMaxRows()<needRows)sh.insertRowsAfter(sh.getMaxRows(),needRows-sh.getMaxRows());sh.clearContents();if(headers.length)sh.getRange(1,1,1,headers.length).setValues([headers]);for(let i=0;i<rows.length;i+=400){const chunk=rows.slice(i,i+400);if(chunk.length)sh.getRange(i+2,1,chunk.length,cols).setValues(chunk);}SpreadsheetApp.flush();return {ok:true,sheet:name,row_count:rows.length};}
function doGet(){return json_({ok:true,environment_id:'STABLE',kind:'DR',writer_scope:'BOUND_CURRENT_ONLY',provisioned:PropertiesService.getScriptProperties().getProperty('DR_PROVISIONED')==='1'});}
function doPost(e){try{const b=JSON.parse((e&&e.postData&&e.postData.contents)||'{}');if(b.action==='stable_bound_provision')return json_(provision_(b));if(b.action==='stable_bound_bridge')return json_(bridge_(b));return json_({ok:false,error:'UNKNOWN_ACTION'});}catch(err){console.error(String(err&&err.message||err).slice(0,300));return json_({ok:false,error:'BOUND_DR_ERROR'});}}
