import fs from 'node:fs';
const input=JSON.parse(fs.readFileSync('/tmp/gas-live-recovery-before.json','utf8'));
const files=input.files||[];
const api=files.find(f=>f.name==='PICK_PACK_API'&&f.type==='SERVER_JS');
const m2=files.find(f=>f.name==='SERVICE_MIGRATION_M2'&&f.type==='SERVER_JS');
if(!api||!m2)throw new Error('LIVE_GAS_REQUIRED_FILES_MISSING');
let a=api.source||'';
const anchor="  if(action==='service_discovery')return ppJson_(ppM2Discovery_(body));";
const dispatch=`  if(action==='service_discovery')return ppJson_(ppM2Discovery_(body));\n  if(action==='m2_internal_reconcile_status')return ppJson_(ppM2InternalReconcileStatus_(body));\n  if(action==='m2_internal_reconcile_begin')return ppJson_(ppM2InternalReconcileBegin_(body));\n  if(action==='m2_internal_reconcile_flush')return ppJson_(ppM2InternalReconcileFlush_(body));\n  if(action==='m2_internal_reconcile_complete')return ppJson_(ppM2InternalReconcileComplete_(body));\n  if(action==='m2_internal_reconcile_revert')return ppJson_(ppM2InternalReconcileRevert_(body));`;
if(!a.includes('m2_internal_reconcile_begin')){if(!a.includes(anchor))throw new Error('LIVE_GAS_DISPATCH_ANCHOR_MISSING');a=a.replace(anchor,dispatch);}
api.source=a;
let s=m2.source||'';
const add=`\n\n/* Bridge-secret adapter for the existing owner-locked M2 recovery state machine. */\nfunction ppM2InternalRecoveryAuthorized_(body){return ppM2BridgeSecretOk_(body||{});}\nfunction ppM2InternalReconcileStatus_(body){if(!ppM2InternalRecoveryAuthorized_(body))return {ok:false,error:'BRIDGE_SECRET_INVALID'};const sh=ppM2FallbackSheet_(),last=sh.getLastRow(),statuses=last>=2?sh.getRange(2,13,last-1,1).getDisplayValues().flat():[];return {ok:true,authority_mode:ppM2Mode_(),authority_epoch:ppM2Epoch_(),fallback_seq:Number(ppM2Props_().getProperty('PP_M2_FALLBACK_SEQ')||'0'),pending:statuses.filter(function(x){return String(x)==='PENDING';}).length,ingested:statuses.filter(function(x){return String(x)==='INGESTED';}).length,service_generation:ppM2Generation_(),service_url:ppM2ServiceUrl_()};}\nfunction ppM2InternalReconcileBegin_(body){if(!ppM2InternalRecoveryAuthorized_(body))return {ok:false,error:'BRIDGE_SECRET_INVALID'};return ppM2BeginReconcile_({role:'SUPERADMIN',login_id:'service-recovery'},body||{});}\nfunction ppM2InternalReconcileFlush_(body){if(!ppM2InternalRecoveryAuthorized_(body))return {ok:false,error:'BRIDGE_SECRET_INVALID'};return ppM2FlushFallbackInbox_();}\nfunction ppM2InternalReconcileComplete_(body){if(!ppM2InternalRecoveryAuthorized_(body))return {ok:false,error:'BRIDGE_SECRET_INVALID'};return ppM2CompleteFailback_({role:'SUPERADMIN',login_id:'service-recovery'},body||{});}\nfunction ppM2InternalReconcileRevert_(body){if(!ppM2InternalRecoveryAuthorized_(body))return {ok:false,error:'BRIDGE_SECRET_INVALID'};if(String((body||{}).confirmation||'')!=='OWNER_LOCKED_M2_FAILBACK')return {ok:false,error:'FAILBACK_CONFIRMATION_REQUIRED'};const lock=LockService.getScriptLock();if(!lock.tryLock(5000))return {ok:false,error:'RECONCILE_BUSY'};try{const p=ppM2Props_(),mode=ppM2Mode_();if(mode!=='RECONCILING')return {ok:false,error:'RECONCILE_REVERT_REQUIRES_RECONCILING',mode:mode};p.setProperty('PP_M2_AUTHORITY_MODE','GOOGLE_FALLBACK');p.deleteProperty('PP_M2_RECONCILE_STARTED_AT');p.deleteProperty('PP_M2_RECONCILE_BY');return {ok:true,authority_mode:'GOOGLE_FALLBACK',authority_epoch:ppM2Epoch_()};}finally{lock.releaseLock();}}\n`;
if(!s.includes('function ppM2InternalRecoveryAuthorized_'))s+=add;
m2.source=s;
fs.writeFileSync('/tmp/gas-live-recovery-patched.json',JSON.stringify({files}));
console.log('LIVE_GAS_RECOVERY_PATCH=READY');
