import { createHmac, pbkdf2Sync, randomBytes, createHash } from 'node:crypto';
import { writeFileSync, mkdirSync } from 'node:fs';

const BASE=process.env.M2_BASE_URL||'http://127.0.0.1:8787';
const ADMIN_TOKEN=process.env.M2_ADMIN_TOKEN||'m2-local-admin-token';
const GAS_SECRET=process.env.M2_GAS_SECRET||'m2-local-gas-secret';
const cases=[];
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function b64u(v){return Buffer.from(v).toString('base64url');}
function record(name,ok,detail=''){cases.push({name,ok,detail:String(detail||'')});if(!ok)console.error('FAIL',name,detail);else console.log('PASS',name,detail);}
function expect(name,cond,detail=''){record(name,Boolean(cond),detail);if(!cond)throw new Error(`CASE_FAILED:${name}:${detail}`);}
async function http(path,{method='GET',body,token,headers={}}={}){const h={accept:'application/json',...headers};if(body!==undefined)h['content-type']='application/json';if(token)h.authorization=`Bearer ${token}`;const r=await fetch(BASE+path,{method,headers:h,body:body===undefined?undefined:JSON.stringify(body)});const text=await r.text();let json={};try{json=JSON.parse(text)}catch{json={raw:text}}return{status:r.status,json};}
function verifier(password){const salt=randomBytes(16),iterations=120000,key=pbkdf2Sync(password,salt,iterations,32,'sha256');return{value:`pbkdf2_sha256$${iterations}$${b64u(salt)}$${b64u(key)}`,salt,iterations,key};}
async function createAccount(login,password,role){const v=verifier(password);const r=await http('/internal/test-account',{method:'POST',headers:{'x-m1-admin-token':ADMIN_TOKEN},body:{login_id:login,verifier:v.value,role}});expect(`create account ${login}`,r.status===200&&r.json.ok===true,JSON.stringify(r.json));return v;}
async function login(login,password,device){const c=await http('/v1/auth/challenge',{method:'POST',body:{login_id:login}});expect(`challenge ${login}/${device}`,c.status===200&&c.json.challenge_id&&c.json.challenge,JSON.stringify(c.json));const key=pbkdf2Sync(password,Buffer.from(c.json.salt,'base64url'),c.json.iterations,32,'sha256');const proof=b64u(createHmac('sha256',key).update(c.json.challenge).digest());const s=await http('/v1/auth/login',{method:'POST',body:{login_id:login,challenge_id:c.json.challenge_id,proof,device_id:device,device_label:'M2 chaos'}});expect(`login ${login}/${device}`,s.status===200&&s.json.ok===true&&s.json.token,JSON.stringify(s.json));return s.json.token;}
function mutation({eventId,eventType='M1_SHADOW_PROBE',entityType='TEST',entityId,eventDate='2026-08-19',epoch=1,generation='m2-precutover-20260819-001',baseVersion=0,payload={},idem,device='chaos-device'}){return{event_id:eventId,event_type:eventType,entity_type:entityType,entity_id:entityId||eventId,business_date:eventDate,authority_epoch:epoch,service_generation:generation,base_version:baseVersion,timestamp:new Date().toISOString(),payload,idempotency_key:idem||`idem:${eventId}`,device_id:device,schema_version:1};}
async function legacy(token,action,payload,eventId=crypto.randomUUID(),date='2026-08-19',device='legacy-chaos'){return http('/v1/legacy-mutations',{method:'POST',token,body:{action,event_id:eventId,business_date:date,device_id:device,payload:{...payload,event_id:eventId}}});}
async function ticket(token,date='2026-08-19'){return http(`/v1/realtime/ticket?business_date=${date}`,{method:'POST',token,body:{}});}
async function openWs(ticketValue){if(typeof WebSocket==='undefined')throw new Error('NODE_WEBSOCKET_UNAVAILABLE');const url=BASE.replace(/^http/,'ws')+`/v1/realtime?ticket=${encodeURIComponent(ticketValue)}`;const ws=new WebSocket(url);await new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(new Error('WS_OPEN_TIMEOUT')),5000);ws.addEventListener('open',()=>{clearTimeout(t);resolve();},{once:true});ws.addEventListener('error',()=>{clearTimeout(t);reject(new Error('WS_OPEN_ERROR'));},{once:true});});return ws;}
function nextDelta(ws){return new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(new Error('WS_DELTA_TIMEOUT')),5000);const fn=e=>{let j;try{j=JSON.parse(String(e.data))}catch{return}if(j.type==='DELTA'){clearTimeout(t);ws.removeEventListener('message',fn);resolve(j);}};ws.addEventListener('message',fn);});}
function fallbackChecksum(row){const raw=[row.event_id,row.authority_epoch,row.authority_seq,row.service_generation,row.event.action,row.event.business_date,row.event.actor,row.event.role,row.event.device_id||'',row.event.occurred_at||'',row.event.payload_json].join('|');return createHash('sha256').update(raw).digest('hex');}

async function main(){
  const health=await http('/health');expect('01 health ok',health.status===200&&health.json.ok===true);expect('02 staging shadow',health.json.environment==='staging-shadow',health.json.environment);expect('03 service generation configured',health.json.generation==='m2-precutover-20260819-001',health.json.generation);
  const caps=await http('/v1/capabilities');expect('04 capabilities v1',caps.status===200&&caps.json.api_version==='v1');expect('05 production cutover false',caps.json.production_cutover===false);expect('06 realtime advertised',String(caps.json.realtime).includes('WEBSOCKET'));
  const authority0=await http('/v1/authority');expect('07 initial authority service primary',authority0.json.authority?.mode==='SERVICE_PRIMARY');expect('08 initial epoch one',authority0.json.authority?.authority_epoch===1);

  await createAccount('super','SuperPass!1','SUPERADMIN');await createAccount('admin','AdminPass!1','ADMIN');await createAccount('user','UserPass!1','USER');
  const badC=await http('/v1/auth/challenge',{method:'POST',body:{login_id:'admin'}});const bad=await http('/v1/auth/login',{method:'POST',body:{login_id:'admin',challenge_id:badC.json.challenge_id,proof:'wrong',device_id:'bad-device'}});expect('09 wrong proof rejected',bad.status===401&&bad.json.ok===false,bad.status);
  const admin1=await login('admin','AdminPass!1','admin-device-1');const st1=await http('/v1/sync/status',{token:admin1});expect('10 first admin token works',st1.status===200&&st1.json.ok===true);
  const admin=await login('admin','AdminPass!1','admin-device-2');const invalidated=await http('/v1/sync/status',{token:admin1});expect('11 single active device invalidates old token',invalidated.status===401,invalidated.status);
  const superToken=await login('super','SuperPass!1','super-device');const userToken=await login('user','UserPass!1','user-device');

  const sync=await http('/v1/legacy-sync',{method:'POST',token:admin,body:{action:'sync_status'}});expect('12 legacy sync status works',sync.status===200&&sync.json.ok===true);expect('13 latest business date is n',sync.json.business_date==='2026-08-19',sync.json.business_date);expect('14 45d manifest contains revisions',sync.json.day_revisions&&sync.json.day_revisions['2026-08-19']>=1);
  const day=await http('/v1/legacy-sync',{method:'POST',token:admin,body:{action:'sync_day',business_date:'2026-08-19'}});expect('15 legacy sync day shape',day.status===200&&day.json.day?.sessions&&day.json.day?.report);
  const boot=await http('/v1/legacy-sync',{method:'POST',token:admin,body:{action:'sync_bootstrap',dates:['2026-08-19','2026-08-18']}});expect('16 legacy bootstrap two days',boot.status===200&&boot.json.days?.length===2,boot.json.days?.length);

  const oldAdmin=await http('/v1/mutations',{method:'POST',token:admin,body:mutation({eventId:'old-admin',eventDate:'2026-08-17'})});expect('17 admin n-2 rejected',oldAdmin.status===403&&oldAdmin.json.error?.code==='BUSINESS_DATE_NOT_N_N_MINUS_1',JSON.stringify(oldAdmin.json));
  const oldSuper=await http('/v1/mutations',{method:'POST',token:superToken,body:mutation({eventId:'old-super',eventDate:'2026-08-17',device:'super-device'})});expect('18 superadmin n-2 allowed',oldSuper.status===201&&oldSuper.json.ok===true,JSON.stringify(oldSuper.json));
  const nMinus1=await http('/v1/mutations',{method:'POST',token:admin,body:mutation({eventId:'nminus1',eventDate:'2026-08-18',device:'admin-device-2'})});expect('19 admin n-1 allowed',nMinus1.status===201,nMinus1.status);

  const enterId='enter-e001';const enter=await legacy(admin,'enter',{mnv:'E001',shift:'Ca 1',work_choice:'PICK',pda_serial:'PDA-A',user_pick:'UP-A'},enterId);expect('20 attendance enter succeeds',enter.status===201&&enter.json.result?.new_version===1,JSON.stringify(enter.json));
  const dup=await legacy(admin,'enter',{mnv:'E001',shift:'Ca 1',work_choice:'PICK',pda_serial:'PDA-A',user_pick:'UP-A'},enterId);expect('21 duplicate event exactly once',dup.status===200&&dup.json.duplicate===true,JSON.stringify(dup.json));
  const stale=await http('/v1/mutations',{method:'POST',token:admin,body:mutation({eventId:'stale-exit',eventType:'ATTENDANCE_EXIT',entityType:'ATTENDANCE_SESSION',entityId:enter.json.event.entity_id,baseVersion:0,payload:{mnv:'E001'},device:'admin-device-2'})});expect('22 stale base version rejected',stale.status===409&&stale.json.error?.code==='STALE_BASE_VERSION',JSON.stringify(stale.json));
  const unavailable=await legacy(admin,'enter',{mnv:'E002',shift:'Ca 1',work_choice:'PICK',pda_serial:'PDA-X'},'unavailable');expect('23 unavailable resource rejected',unavailable.status===409&&unavailable.json.error?.code==='PDA_UNAVAILABLE',JSON.stringify(unavailable.json));

  const [raceA,raceB]=await Promise.all([
    legacy(admin,'enter',{mnv:'E002',shift:'Ca 1',work_choice:'PICK',pda_serial:'PDA-B'},'race-a'),
    legacy(superToken,'enter',{mnv:'E003',shift:'Ca 1',work_choice:'PICK',pda_serial:'PDA-B'},'race-b','2026-08-19','super-device'),
  ]);const raceStatuses=[raceA.status,raceB.status].sort();expect('24 exclusive resource race has one winner',raceStatuses[0]===201&&raceStatuses[1]===409,JSON.stringify(raceStatuses));
  const winner=raceA.status===201?'E002':'E003',loser=winner==='E002'?'E003':'E002';expect('25 race conflict classified resource',[raceA,raceB].some(r=>r.status===409&&r.json.error?.error_class==='RESOURCE'),JSON.stringify([raceA.json,raceB.json]));

  const userEnter=await legacy(userToken,'enter',{mnv:'E005',shift:'Ca 2',work_choice:'KHONG'},'user-enter','2026-08-19','user-device');expect('26 user attendance allowed',userEnter.status===201,userEnter.status);
  const userLabor=await legacy(userToken,'labor_start',{mnv:'E005',shift:'Ca 2',labor_type:'Hỗ trợ',time_marker:'Trong ngày'},'user-labor','2026-08-19','user-device');expect('27 user labor blocked',userLabor.status===403&&userLabor.json.error?.code==='LABOR_ADMIN_REQUIRED',JSON.stringify(userLabor.json));
  const labor=await legacy(admin,'labor_start',{mnv:'E005',shift:'Ca 2',labor_type:'Hỗ trợ',time_marker:'Trong ngày'},'labor-e005');expect('28 admin labor start',labor.status===201,labor.status);
  const blockedExit=await legacy(admin,'exit',{mnv:'E005'},'exit-blocked');expect('29 open labor blocks exit',blockedExit.status===409&&blockedExit.json.error?.code==='OPEN_LABOR_BLOCKS_EXIT',JSON.stringify(blockedExit.json));
  const finish=await legacy(admin,'labor_finish',{mnv:'E005'},'labor-finish');expect('30 labor finish',finish.status===201,finish.status);
  const exit5=await legacy(admin,'exit',{mnv:'E005'},'exit-e005');expect('31 exit after labor finish',exit5.status===201,exit5.status);

  const genBad=await http('/v1/mutations',{method:'POST',token:admin,body:mutation({eventId:'gen-bad',generation:'stale-generation',device:'admin-device-2'})});expect('32 stale service generation rejected',genBad.status===409&&genBad.json.error?.code==='SERVICE_GENERATION_STALE',JSON.stringify(genBad.json));
  const epochBad=await http('/v1/mutations',{method:'POST',token:admin,body:mutation({eventId:'epoch-bad',epoch:99,device:'admin-device-2'})});expect('33 stale authority epoch rejected',epochBad.status===409&&epochBad.json.error?.code==='AUTHORITY_EPOCH_STALE',JSON.stringify(epochBad.json));
  const delta=await http('/v1/delta?authority_epoch=1&after_seq=0&limit=500',{token:admin});expect('34 delta returns committed events',delta.status===200&&delta.json.events?.length>=5,delta.json.events?.length);expect('35 delta sequence monotonic',delta.json.events.every((e,i,a)=>i===0||e.authority_seq>a[i-1].authority_seq));

  const ta=await ticket(admin),ts=await ticket(superToken);expect('36 realtime tickets issued',ta.status===200&&ts.status===200);
  const wsA=await openWs(ta.json.ticket),wsS=await openWs(ts.json.ticket),pA=nextDelta(wsA),pS=nextDelta(wsS);const rt=await http('/v1/mutations',{method:'POST',token:admin,body:mutation({eventId:'realtime-probe',device:'admin-device-2'})});expect('37 realtime trigger mutation committed',rt.status===201);const [dA,dS]=await Promise.all([pA,pS]);expect('38 realtime push reaches two clients',dA.event?.event_id==='realtime-probe'&&dS.event?.event_id==='realtime-probe');wsA.close();wsS.close();

  const unauthTransition=await http('/internal/authority/transition',{method:'POST',body:{expected_epoch:1,mode:'SERVICE_PRIMARY'}});expect('39 internal authority transition protected',unauthTransition.status===401,unauthTransition.status);
  const prodNoConfirm=await http('/internal/authority/transition',{method:'POST',headers:{'x-m1-admin-token':ADMIN_TOKEN},body:{expected_epoch:1,mode:'SERVICE_PRIMARY',scope:'PRODUCTION',increment_epoch:true,reason:'chaos'}});expect('40 production promotion requires confirmation',prodNoConfirm.status===403&&prodNoConfirm.json.error?.code==='PRODUCTION_PROMOTION_CONFIRMATION_REQUIRED',JSON.stringify(prodNoConfirm.json));

  const at=new Date().toISOString(),fallback={event_id:'fallback-e006',authority_epoch:2,authority_seq:1,service_generation:'gas-fallback-chaos',event:{action:'enter',business_date:'2026-08-19',actor:'super',role:'SUPERADMIN',device_id:'gas-fallback-device',occurred_at:at,payload_json:JSON.stringify({mnv:'E006',shift:'Ca 1',work_choice:'KHONG',note:'fallback chaos'})}};fallback.checksum=fallbackChecksum(fallback);
  const ingest=await http('/internal/fallback/ingest',{method:'POST',headers:{'x-gas-bridge-secret':GAS_SECRET},body:fallback});expect('41 future fallback epoch staged',ingest.status===200&&ingest.json.staged_for_failback===true,JSON.stringify(ingest.json));
  const ingestDup=await http('/internal/fallback/ingest',{method:'POST',headers:{'x-gas-bridge-secret':GAS_SECRET},body:fallback});expect('42 fallback event ingest idempotent',ingestDup.status===200&&ingestDup.json.duplicate===true,JSON.stringify(ingestDup.json));
  const collision={...fallback,event_id:'fallback-collision'};collision.checksum=fallbackChecksum(collision);const collisionR=await http('/internal/fallback/ingest',{method:'POST',headers:{'x-gas-bridge-secret':GAS_SECRET},body:collision});expect('43 fallback sequence collision rejected',collisionR.status===409&&collisionR.json.error?.code==='FALLBACK_SEQUENCE_COLLISION',JSON.stringify(collisionR.json));
  const badFailback=await http('/internal/recovery/failback',{method:'POST',headers:{'x-m1-admin-token':ADMIN_TOKEN},body:{fallback_epoch:2,expected_service_epoch:1,confirmation:'WRONG',initiated_by:'chaos'}});expect('44 failback requires owner confirmation',badFailback.status===409,JSON.stringify(badFailback.json));
  const failback=await http('/internal/recovery/failback',{method:'POST',headers:{'x-m1-admin-token':ADMIN_TOKEN},body:{fallback_epoch:2,expected_service_epoch:1,confirmation:'OWNER_LOCKED_M2_FAILBACK',initiated_by:'chaos'}});expect('45 failback replay completes',failback.status===200&&failback.json.ok===true,JSON.stringify(failback.json));expect('46 failback bumps to fresh Service epoch',failback.json.authority?.authority_epoch===3&&failback.json.authority?.authority_seq===0,JSON.stringify(failback.json.authority));
  const oldEpochAfter=await http('/v1/mutations',{method:'POST',token:admin,body:mutation({eventId:'after-failback-old-epoch',epoch:1,device:'admin-device-2'})});expect('47 pre-failback epoch fenced',oldEpochAfter.status===409&&oldEpochAfter.json.error?.code==='AUTHORITY_EPOCH_STALE',JSON.stringify(oldEpochAfter.json));
  const drFence=await http('/internal/dr/rebuild-google-staging',{method:'POST',headers:{'x-m1-admin-token':ADMIN_TOKEN},body:{}});expect('48 DR refuses production source as staging target',drFence.status===409&&String(drFence.json.error?.message||'').includes('DR_TARGET_MUST_NOT_BE_PRODUCTION_SOURCE'),JSON.stringify(drFence.json));
  const manifest=await http('/internal/dr/manifest',{method:'POST',headers:{'x-m1-admin-token':ADMIN_TOKEN},body:{}});expect('49 DR manifest emitted',manifest.status===200&&manifest.json.checksum&&manifest.json.authority_epoch===3,JSON.stringify(manifest.json));
  const rep=await http('/internal/replicate',{method:'POST',headers:{'x-m1-admin-token':ADMIN_TOKEN},body:{}});expect('50 Google temporary failure stays off critical mutation path',rep.status===200&&rep.json.ok===false&&rep.json.pending>0,JSON.stringify(rep.json));

  const summary={passed:cases.filter(x=>x.ok).length,failed:cases.filter(x=>!x.ok).length,total:cases.length};mkdirSync('m2-artifacts',{recursive:true});writeFileSync('m2-artifacts/chaos-report.json',JSON.stringify({generated_at:new Date().toISOString(),summary,cases},null,2));console.log(JSON.stringify(summary));if(summary.failed)process.exit(1);
}

main().catch(err=>{record('fatal',false,err.stack||err);const summary={passed:cases.filter(x=>x.ok).length,failed:cases.filter(x=>!x.ok).length,total:cases.length};mkdirSync('m2-artifacts',{recursive:true});writeFileSync('m2-artifacts/chaos-report.json',JSON.stringify({generated_at:new Date().toISOString(),summary,cases,fatal:String(err.stack||err)},null,2));process.exit(1);});
