from pathlib import Path
import re

ROOT=Path('.')
def read(p): return (ROOT/p).read_text(encoding='utf-8')
def write(p,s): (ROOT/p).write_text(s,encoding='utf-8')
def rep(s,a,b,label):
    n=s.count(a)
    if n!=1: raise SystemExit(f'{label}: expected 1 occurrence, got {n}')
    return s.replace(a,b,1)
def sub(s,pat,repl,label):
    out,n=re.subn(pat,repl,s,count=1,flags=re.S)
    if n!=1: raise SystemExit(f'{label}: expected 1 match, got {n}')
    return out

# Version lock: Beta only. Stable stays immutable.
p=Path('app/build.gradle.kts');s=read(p)
s=rep(s,'versionCode = 67','versionCode = 68','beta code')
s=rep(s,'versionName = "0.4.2-beta.61"','versionName = "0.4.2-beta.62"','beta version')
s=rep(s,'// Beta61: restored Staff tab, denser owner UI, active-PDA holder list, attendance editor refinements and direct Service resource admin.','// Beta62: owner UI polish, strict provider fault injection, PDA exchange confirmation, mutation diagnostics and login redesign.\n// Beta61 remains immutable and is the previous public baseline.','version note')
write(p,s)

# Login redesign and global compact employee scanner on launcher/login activity.
p=Path('app/src/main/java/vn/pickpack1291/app/beta/FullBetaActivity.kt');s=read(p)
s=rep(s,'card.addView(ImageView(this).apply { setImageResource(R.drawable.owner_launcher); scaleType = ImageView.ScaleType.CENTER_CROP }, size(dp(92), dp(92)))\n        card.addView(gap(9))\n        card.addView(txt("PICK PACK 1291", 24f, navy, true).center())\n        card.addView(txt("SUPRA DC HƯNG YÊN", 10.5f, accent, true).center())','card.addView(txt("Pick Pack 1291", 25f, navy, true).center())\n        card.addView(txt("Supra DC Hưng Yên", 12f, accent, true).center())\n        card.addView(gap(5))\n        card.addView(txt("KHU VỰC ĐĂNG NHẬP", 10.2f, muted, true).center())','login branding')
s=rep(s,'card.addView(labelled("Tài khoản", user)); card.addView(gap(10))\n        card.addView(labelled("Mật khẩu", pass)); card.addView(gap(14))','card.addView(labelled("Tài khoản", user)); card.addView(gap(10))\n        card.addView(labelled("Mật khẩu", pass)); card.addView(gap(5))\n        val showPassword = CheckBox(this).apply {\n            text = "Hiện mật khẩu"; textSize = 10.8f; setTextColor(muted); setPadding(0,0,0,0)\n            setOnCheckedChangeListener { _, checked ->\n                val cursor=pass.selectionStart.coerceAtLeast(0)\n                pass.inputType=InputType.TYPE_CLASS_TEXT or if(checked) InputType.TYPE_TEXT_VARIATION_VISIBLE_PASSWORD else InputType.TYPE_TEXT_VARIATION_PASSWORD\n                pass.setSelection(cursor.coerceAtMost(pass.text.length))\n            }\n        }\n        card.addView(showPassword,matchWrap()); card.addView(gap(10))','show password')
s=rep(s,'        }, matchWrap())\n\n        val holder = FrameLayout(this).apply {','        }, matchWrap())\n        card.addView(gap(4))\n        card.addView(Button(this).apply {\n            text="ĐĂNG KÝ"; textSize=11.5f; setTextColor(navy); typeface=Typeface.DEFAULT_BOLD; isAllCaps=false; minHeight=dp(44); background=outlineBg(surface,12)\n            setOnClickListener{TopNotice.show(this@FullBetaActivity,"Tính năng đăng ký đang được xây dựng.",TopNotice.Kind.INFO)}\n        },matchWrap())\n\n        val holder = FrameLayout(this).apply {','register pending')
s=rep(s,'setBackgroundColor(surface)\n            minimumHeight','background=GradientDrawable(GradientDrawable.Orientation.TOP_BOTTOM,intArrayOf(Color.rgb(239,247,250),Color.WHITE))\n            minimumHeight','login background')
s=s.replace('mnvInput("Quét QR hoặc nhập MNV")','mnvInput("Scan / Nhập mã nhân viên")')
s=rep(s,'private fun mnvInput(hintValue:String)=input(hintValue,false).apply{setSingleLine(true);inputType=InputType.TYPE_CLASS_NUMBER;keyListener=DigitsKeyListener.getInstance("0123456789");imeOptions=EditorInfo.IME_ACTION_DONE}','private fun mnvInput(hintValue:String)=input(hintValue,false).apply{setSingleLine(true);minHeight=dp(50);setPadding(dp(12),dp(7),dp(12),dp(7));inputType=InputType.TYPE_CLASS_NUMBER;keyListener=DigitsKeyListener.getInstance("0123456789");imeOptions=EditorInfo.IME_ACTION_DONE}','launcher scanner')
write(p,s)

# SERVICE_PRIMARY fencing: fault injection must be a real provider loss, never a client authority promotion.
p=Path('app/src/main/java/vn/pickpack1291/app/beta/M2RuntimeBridge.kt');s=read(p)
s=s.replace(' * Cache-only routing for hot reads. GAS is used as controlled fallback when Cloudflare is unavailable.\n * S58_BETA55_GOOGLE_FALLBACK keeps device-local fault injection truthful: a local Cloudflare test\n * uses the Google/GAS path without pretending production authority globally changed to Google.',' * Cache-only routing for hot reads. GAS is used only when authoritative discovery is GOOGLE_FALLBACK.\n * Device-local provider fault injection blocks that provider; it never promotes authority on its own.')
s=rep(s,'if(ServiceFaultInjection.cloudflareDisabled(app)){recordFallback("TEST_CLOUDFLARE_DISABLED");return false}','if(ServiceFaultInjection.cloudflareDisabled(app)){recordServicePending("TEST_CLOUDFLARE_DISABLED");return false}','service session fault')
s=rep(s,'        if(ServiceFaultInjection.cloudflareDisabled(app)){\n            recordFallback("TEST_CLOUDFLARE_DISABLED")\n            return M2ServiceTransport.TransportResult(false,false,-1,null,"TEST_CLOUDFLARE_DISABLED")\n        }\n        val discovery = transport.cachedDiscoverySnapshot()\n            ?: return M2ServiceTransport.TransportResult(true, false, 0, null, "DISCOVERY_WARMING")\n        val mode = discovery.optString("authority_mode")','        val discovery = transport.cachedDiscoverySnapshot()\n            ?: return M2ServiceTransport.TransportResult(true, false, 0, null, "DISCOVERY_WARMING")\n        val mode = discovery.optString("authority_mode")\n        if(ServiceFaultInjection.cloudflareDisabled(app) && mode != "GOOGLE_FALLBACK"){\n            recordServicePending("TEST_CLOUDFLARE_DISABLED")\n            return M2ServiceTransport.TransportResult(true,false,-1,null,"TEST_CLOUDFLARE_DISABLED")\n        }','direct read fault')
s=s.replace('M2ServiceTransport.TransportResult(false, false, response.code, response.json, response.error)','M2ServiceTransport.TransportResult(true, false, response.code, response.json, response.error)')
s=s.replace('M2ServiceTransport.TransportResult(false, false, -1, null, t.message)','M2ServiceTransport.TransportResult(true, false, -1, null, t.message)')
s=s.replace('cfOff && !googleOff -> "GOOGLE_RELAY_TEST"','cfOff && !googleOff -> "SERVICE_D1_BLOCKED_TEST"')
s=s.replace('"GOOGLE_RELAY_TEST" -> "Google/GAS dự phòng (test Cloudflare)"','"SERVICE_D1_BLOCKED_TEST" -> "Cloudflare / D1 • đang mô phỏng mất dịch vụ"')
s=s.replace('"GOOGLE_RELAY_TEST","GOOGLE_RELAY_PENDING" -> "Google/GAS"','"GOOGLE_RELAY_PENDING" -> "Google/GAS"\n            "SERVICE_D1_BLOCKED_TEST" -> "Cloudflare"')
write(p,s)

p=Path('app/src/main/java/vn/pickpack1291/app/beta/M2ServiceTransport.kt');s=read(p)
s=rep(s,'        if(ServiceFaultInjection.cloudflareDisabled(app)){\n            // S58_BETA55_GOOGLE_FALLBACK: Cloudflare unavailable -> GAS/Google Sheets.\n            // Only disabling both providers is OFFLINE.\n            return flushFallbackItems(store.unresolvedMutations(100))\n        }','        if(ServiceFaultInjection.cloudflareDisabled(app)){\n            // True Service outage simulation. Under SERVICE_PRIMARY keep mutations pending; do not self-promote to Google/GAS.\n            return false\n        }','outbox fault')
s=s.replace('        if(circuitOpen()){\n            if(failureCount()>=FALLBACK_PROBE_FAILURES)return flushFallbackItems(items)\n            return false\n        }','        if(circuitOpen()) return false')
s=s.replace('if((r.code>=500||r.code==-1)&&failureCount()>=FALLBACK_PROBE_FAILURES)return flushFallbackItems(items);','')
s=s.replace('catch(x:Throwable){recordFailure();if(failureCount()>=FALLBACK_PROBE_FAILURES)return flushFallbackItems(items);items.forEach','catch(x:Throwable){recordFailure();items.forEach')
s=s.replace('TransportResult(false, false, r.code, body, r.error ?: "SERVICE_UNAVAILABLE")','TransportResult(true, false, r.code, body, r.error ?: "SERVICE_UNAVAILABLE")')
s=s.replace('TransportResult(false, false, -1, JSONObject().put("_service_rtt_ms", rtt), t.message ?: "SERVICE_READ_NETWORK_ERROR")','TransportResult(true, false, -1, JSONObject().put("_service_rtt_ms", rtt), t.message ?: "SERVICE_READ_NETWORK_ERROR")')
write(p,s)

# Direct mutation observability and a safe one-shot retry on atomic optimistic conflict.
p=Path('app/src/main/java/vn/pickpack1291/app/beta/BetaApiClient.kt');s=read(p)
s=rep(s,'                    val result=serviceOwnerCall(action,payload)\n                    if(action in setOf("resource_master_upsert","resource_master_delete","history_correction")) AppHistory.record(appContext,action,result.ok,result.error.orEmpty())\n                    callback(result)','                    val result=serviceOwnerCall(action,payload)\n                    DirectOwnerDiagnostics.record(appContext,action,payload,result)\n                    if(action in setOf("resource_master_upsert","resource_master_delete","history_correction")) AppHistory.record(appContext,action,result.ok,result.error.orEmpty())\n                    callback(result)','direct owner result')
s=rep(s,'                } catch(t:Throwable){ callback(failure(t)) }\n            }\n            return\n        }','                } catch(t:Throwable){ val result=failure(t);DirectOwnerDiagnostics.record(appContext,action,payload,result);callback(result) }\n            }\n            return\n        }','direct owner exception')
s=rep(s,'        return result\n    }\n\n    private fun serviceOwnerRequest','        if(action=="session_work_update" && result.code==409 && result.error=="SESSION_WORK_CONFLICT") result=request(bearer)\n        return result\n    }\n\n    private fun serviceOwnerRequest','session conflict retry')
write(p,s)

# Manual log resets visibly after acknowledged upload and includes direct owner route evidence.
p=Path('app/src/main/java/vn/pickpack1291/app/beta/LocalLogManager.kt');s=read(p)
s=rep(s,'        uploadFile(api, file, "MANUAL") { r -> if (r.ok) file.delete(); callback(r) }','        uploadFile(api, file, "MANUAL") { r -> if (r.ok) resetAfterSuccessfulManualSend(context); callback(r) }','manual reset call')
s=rep(s,'\n    private fun uploadNext(api: BetaApiClient, files: List<File>, index: Int) {','\n    @Synchronized private fun resetAfterSuccessfulManualSend(context:Context){\n        logDir(context).listFiles()?.filter{it.isFile}?.forEach{runCatching{it.delete()}}\n        context.getSharedPreferences(PREFS,Context.MODE_PRIVATE).edit().putBoolean(KEY_STATS_INIT,true).putLong(KEY_TOTAL_FILES,0L).putLong(KEY_TOTAL_BYTES,0L).putLong(KEY_LATEST_AT,0L).apply()\n        DirectOwnerDiagnostics.clear(context)\n    }\n\n    private fun uploadNext(api: BetaApiClient, files: List<File>, index: Int) {','manual reset method')
s=rep(s,'        runCatching { M2TransportDiagnostics.snapshotLines(context).forEach { appendLine(it) } }\n            .onFailure { appendLine("transport_diag_error=${safe(it.javaClass.simpleName+\":\"+(it.message?:\"\"))}") }','        runCatching { M2TransportDiagnostics.snapshotLines(context).forEach { appendLine(it) } }\n            .onFailure { appendLine("transport_diag_error=${safe(it.javaClass.simpleName+\":\"+(it.message?:\"\"))}") }\n        runCatching { DirectOwnerDiagnostics.snapshotLines(context).forEach { appendLine(it) } }\n            .onFailure { appendLine("direct_owner_diag_error=${safe(it.javaClass.simpleName+\":\"+(it.message?:\"\"))}") }','manual diagnostics')
write(p,s)

# Natural MNV ordering in staff master cache.
p=Path('app/src/main/java/vn/pickpack1291/app/beta/MasterDataCache.kt');s=read(p)
s=rep(s,'        searchableStaff = searchable\n        memorySnapshot = snapshot','        searchableStaff = searchable.sortedWith(Comparator { a,b -> naturalCompare(a.second.optString("mnv"),b.second.optString("mnv")) })\n        memorySnapshot = snapshot','staff sort')
s=rep(s,'\n    private fun fold(v: String): String = Normalizer.normalize(v, Normalizer.Form.NFD)','\n    private fun naturalCompare(aRaw:String,bRaw:String):Int{\n        val rx=Regex("\\\\d+|\\\\D+");val a=rx.findAll(aRaw.trim()).map{it.value}.toList();val b=rx.findAll(bRaw.trim()).map{it.value}.toList();val n=minOf(a.size,b.size)\n        for(i in 0 until n){val x=a[i];val y=b[i];val xn=x.toLongOrNull();val yn=y.toLongOrNull();val c=if(xn!=null&&yn!=null)xn.compareTo(yn) else x.compareTo(y,ignoreCase=true);if(c!=0)return c}\n        return if(a.size!=b.size)a.size.compareTo(b.size) else aRaw.compareTo(bRaw,ignoreCase=true)\n    }\n\n    private fun fold(v: String): String = Normalizer.normalize(v, Normalizer.Form.NFD)','natural helper')
write(p,s)

# Operations UI: scan, swipe, cards, reconciliation, status colors, long user lists, history and PDA exchange.
p=Path('app/src/main/java/vn/pickpack1291/app/beta/OperationsActivity.kt');s=read(p)
for old in ['mnvInput("Scan / Nhập mã nhân viên để ghi nhận ra ca / vào ca")','mnvInput("Quét QR hoặc nhập mã nhân viên")','mnvInput("Quét / nhập mã nhân viên")','mnvInput("Nhập / quét mã nhân viên")']:
    s=s.replace(old,'mnvInput("Scan / Nhập mã nhân viên")')
s=rep(s,'private fun mnvInput(h:String)=scanField(h,true,72)','private fun mnvInput(h:String)=scanField(h,true,50)','scanner height')
s=rep(s,'val root=EdgeSwipeBackLayout(this){navigateBack()}.apply{setBackgroundColor(bg)}','val root=EdgeSwipeBackLayout(this){if(!isRootScreen())navigateBack()}.apply{setBackgroundColor(bg)}','swipe fence')
s=rep(s,'private fun reconciliationButton(t:String,balanced:Boolean)=Button(this).apply{text=t;textSize=9.4f;typeface=Typeface.DEFAULT_BOLD;isAllCaps=false;setSingleLine(true);setPadding(dp(2),0,dp(2),0);val fg=if(balanced)Color.rgb(30,125,76) else Color.rgb(190,55,65);val fill=if(balanced)Color.rgb(236,248,241) else Color.rgb(254,240,242);setTextColor(fg);background=GradientDrawable().apply{setColor(fill);cornerRadius=dp(10).toFloat();setStroke(dp(1),Color.argb(90,Color.red(fg),Color.green(fg),Color.blue(fg)))}}','private fun reconciliationButton(t:String,balanced:Boolean)=Button(this).apply{text=t;textSize=9.8f;typeface=Typeface.DEFAULT_BOLD;isAllCaps=false;setSingleLine(true);setPadding(dp(2),0,dp(2),0);val fg=if(balanced)Color.rgb(25,110,66) else Color.rgb(165,0,32);val fill=if(balanced)Color.rgb(235,248,240) else Color.rgb(255,235,238);setTextColor(fg);background=GradientDrawable().apply{setColor(fill);cornerRadius=dp(10).toFloat();setStroke(dp(if(balanced)1 else 2),Color.argb(if(balanced)105 else 190,Color.red(fg),Color.green(fg),Color.blue(fg)))}}','reconciliation')
s=rep(s,'        setPadding(dp(7),dp(7),dp(7),dp(7))\n        background=outlineBg(surface,20)','        setPadding(dp(8),dp(6),dp(8),dp(5))\n        background=outlineBg(surface,18)','business spacing')
s=rep(s,'private fun employeeCard(e:JSONObject)=column(surface).apply{setPadding(dp(10),dp(8),dp(10),dp(8));background=outlineBg(surface,11);addView(txt("${e.optString(\"mnv\")} • ${e.optString(\"full_name\")}",13.2f,navy,true));addView(txt("${dash(e.optString(\"main_position\"))} • ${dash(e.optString(\"supplier\"))}",9.5f,ink,false));addView(txt("${dash(e.optString(\"department\"))} • Site ${dash(e.optString(\"site\"))} • Kho ${dash(e.optString(\"warehouse\"))}",9.1f,muted,false))}','private fun employeeCard(e:JSONObject,state:String="")=column(surface).apply{val fill=when(state.uppercase()){ "ACTIVE"->Color.rgb(255,249,214);"ENDED"->Color.rgb(231,247,237);else->surface };setPadding(dp(10),dp(8),dp(10),dp(8));background=GradientDrawable().apply{setColor(fill);cornerRadius=dp(11).toFloat();setStroke(dp(1),if(state.equals("ACTIVE",true))Color.rgb(217,165,32) else if(state.equals("ENDED",true))Color.rgb(54,142,91) else line)};addView(txt("${e.optString(\"mnv\")} • ${e.optString(\"full_name\")}",13.2f,navy,true).apply{maxLines=2});addView(txt("${dash(e.optString(\"main_position\"))} • ${dash(e.optString(\"supplier\"))}",9.5f,ink,false).apply{maxLines=2});addView(txt("${dash(e.optString(\"department\"))} • Site ${dash(e.optString(\"site\"))} • Kho ${dash(e.optString(\"warehouse\"))}",9.1f,muted,false).apply{maxLines=3})}','employee card')
s=rep(s,'body.addView(labelled("Mã nhân viên",scan));body.addView(gap(9));body.addView(employeeCard(e));body.addView(gap(10))','body.addView(labelled("Mã nhân viên",scan));body.addView(gap(6));body.addView(employeeCard(e,state));body.addView(gap(8))','employee card state')
s=s.replace('body.addView(status("ĐANG TRONG PHIÊN",green,Color.rgb(235,248,239)));body.addView(gap(7));','')
s=s.replace('body.addView(status("ĐÃ RA CA",teal,Color.rgb(232,248,245)));body.addView(gap(8));','')
s=rep(s,'private fun details(items:List<Pair<String,String>>)=column(surface).apply{setPadding(dp(9),dp(6),dp(9),dp(6));background=outlineBg(surface,10);items.forEach{(k,v)->addView(row(surface).apply{addView(txt(k,9.5f,muted,false),LinearLayout.LayoutParams(0,-2,.45f));addView(txt(if(v.isBlank())"—" else v,9.7f,ink,true).apply{gravity=Gravity.END},LinearLayout.LayoutParams(0,-2,.55f));setPadding(0,dp(2),0,dp(2))})}}','private fun details(items:List<Pair<String,String>>)=column(surface).apply{setPadding(dp(9),dp(6),dp(9),dp(6));background=outlineBg(surface,10);items.forEach{(k,raw)->val v=if(raw.isBlank())"—" else raw;val longValue=v.length>26||v.contains(", ")||v.contains(" & ");if(longValue)addView(column(surface).apply{setPadding(0,dp(3),0,dp(3));addView(txt(k,9.3f,muted,false));addView(txt(v,10f,ink,true).apply{maxLines=8;ellipsize=null})})else addView(row(surface).apply{addView(txt(k,9.5f,muted,false),LinearLayout.LayoutParams(0,-2,.42f));addView(txt(v,9.7f,ink,true).apply{gravity=Gravity.END;maxLines=3},LinearLayout.LayoutParams(0,-2,.58f));setPadding(0,dp(2),0,dp(2))})}}','details wrap')
s=s.replace('        if(type!="PDA"){body.addView(info("Danh mục dùng chung. Thay đổi được ghi nhận vào lịch sử; xóa yêu cầu xác thực lại mật khẩu."));body.addView(gap(8))}\n','')
s=s.replace('Triple(R.drawable.ic_pp_settings,"Quyền","ROLE_MODE")','Triple(R.drawable.ic_pp_account,"Quyền","ROLE_MODE")')
s=s.replace('"Seri / tình trạng"','"PDA"')
s=rep(s,'if(!r.ok)showError(r.error?:"Không gửi được báo lỗi")else TopNotice.show(this,"Đã gửi báo lỗi thành công.",TopNotice.Kind.SUCCESS)','if(!r.ok)showError(r.error?:"Không gửi được báo lỗi")else{TopNotice.show(this,"Đã gửi báo lỗi thành công. Nhật ký trên thiết bị đã được reset.",TopNotice.Kind.SUCCESS);settingsScreen()}','settings reset')
# History: show complete payload/metadata rather than selected keys only.
s=rep(s,'val p=runCatching{JSONObject(e.optString("payload_json","{}"))}.getOrDefault(JSONObject());val before=p.optJSONObject("before");val after=p.optJSONObject("after");val src=after?:p;val d=mutableListOf<String>();listOf("shift","work_choice","pda_serial","user_pick","pack_table","user_pack","labor_type","time_marker","start_at","end_at","note","state").forEach{k->val v=src.optString(k);if(v.isNotBlank())d.add("$k: $v")};if(before!=null)d.add("Trước: ${before.toString().take(500)}");if(after!=null)d.add("Sau: ${after.toString().take(500)}")','val p=runCatching{JSONObject(e.optString("payload_json","{}"))}.getOrDefault(JSONObject());val d=mutableListOf<String>();fun addJson(prefix:String,j:JSONObject?){if(j==null)return;val keys=j.keys().asSequence().toList().sortedWith(Comparator{a,b->naturalUserCompare(a,b)});for(k in keys){val raw=j.opt(k);val v=when(raw){is JSONObject,is JSONArray->raw.toString();else->raw?.toString().orEmpty()};if(v.isNotBlank()&&v!="null")d.add("$prefix$k: $v")}};addJson("",p);listOf("business_date","entity_id","actor_id","actor_role","device_id","origin","history_source","event_id").forEach{k->val v=e.optString(k);if(v.isNotBlank())d.add("$k: $v")};e.optString("detail").takeIf{it.isNotBlank()}?.let{d.add("detail: $it")};e.optString("local_error").takeIf{it.isNotBlank()}?.let{d.add("local_error: $it")}','history details')
s=s.replace('if(d.isNotEmpty())card.addView(txt(d.joinToString("\\n"),9.4f,ink,false))','if(d.isNotEmpty())card.addView(txt(d.joinToString("\\n"),9.4f,ink,false).apply{maxLines=60;ellipsize=null;setTextIsSelectable(true)})',1)
# PDA exchange: no search button; input live-filters loaded in-use holders. Existing card/dialog/mutation logic is retained.
s=rep(s,'        val serialField=input("Nhập Seri PDA / 5 số cuối",false).apply{setSingleLine(true);imeOptions=EditorInfo.IME_ACTION_SEARCH}\n        body.addView(labelled("Seri PDA",serialField));body.addView(gap(6))\n        val find=primary("TÌM PDA",navy){};body.addView(find,matchWrap());body.addView(gap(7))','        val serialField=input("Nhập 5 số cuối PDA",false).apply{setSingleLine(true);inputType=InputType.TYPE_CLASS_NUMBER;keyListener=DigitsKeyListener.getInstance("0123456789");imeOptions=EditorInfo.IME_ACTION_DONE}\n        body.addView(labelled("Tìm PDA đang sử dụng",serialField));body.addView(gap(7))','pda search header')
# Convert refresh to natural ordering and input-driven refresh; strict last-5 match already exists.
s=s.replace('holders.sortWith(compareBy<Pair<String,String>>{it.first.takeLast(5)}.thenBy{it.first})','holders.sortWith(Comparator{a,b->naturalUserCompare(a.first,b.first)})')
s=s.replace('find.setOnClickListener{refreshList(serialField.text.toString())};serialField.setOnEditorActionListener{_,_,_->refreshList(serialField.text.toString());true};attach(root,body);refreshList("")','serialField.addTextChangedListener(object:TextWatcher{override fun beforeTextChanged(v:CharSequence?,start:Int,count:Int,after:Int)=Unit;override fun onTextChanged(v:CharSequence?,start:Int,before:Int,count:Int)=Unit;override fun afterTextChanged(v:Editable?){refreshList(v?.toString().orEmpty())}});attach(root,body);refreshList("")')
# Add detailed PDA handover condition into existing reason/mutation audit by replacing the two button callbacks.
s=s.replace('chooseReason("Lý do đổi PDA",changeReasons){mutate(next,"Đổi",it)}','confirmPdaHandoverCondition(ses,serial,"Đổi PDA"){condition->chooseReason("Lý do đổi PDA",changeReasons){mutate(next,"Đổi","$it • Tình trạng bàn giao: $condition")}}')
s=s.replace('chooseReason("Lý do trả PDA",returnReasons){mutate("","Trả",it)}','confirmPdaHandoverCondition(ses,serial,"Trả PDA"){condition->chooseReason("Lý do trả PDA",returnReasons){mutate("","Trả","$it • Tình trạng bàn giao: $condition")}}')
# Insert reusable detailed condition confirmation immediately before pda exchange screen.
condition_fun='''\n    private fun confirmPdaHandoverCondition(ses:JSONObject,serial:String,operation:String,done:(String)->Unit){\n        val expected=ses.optString("pda_enter_status").trim();val statuses=mutableListOf<String>();val arr=MasterDataCache.snapshot(this)?.optJSONArray("pda_statuses")?:JSONArray();for(i in 0 until arr.length()){val v=arr.optString(i).trim();if(v.isNotBlank()&&!statuses.contains(v))statuses.add(v)};if(expected.isNotBlank()&&!statuses.contains(expected))statuses.add(0,expected);if(statuses.isEmpty())statuses.add("Nguyên vẹn")\n        val sp=spinner(statuses.toTypedArray());val pos=statuses.indexOf(expected);if(pos>=0)sp.setSelection(pos);val note=input("Ghi chú tình trạng (tùy chọn)",false)\n        val box=column(surface).apply{setPadding(dp(12),dp(4),dp(12),dp(8));addView(details(listOf("Seri PDA" to serial,"Tình trạng khi nhận" to expected.ifBlank{"—"},"Thao tác" to operation)));addView(gap(7));addView(labelled("Tình trạng PDA hiện tại",sp));addView(gap(7));addView(note,matchWrap())}\n        AlertDialog.Builder(this).setTitle("Xác nhận tình trạng PDA").setView(box).setNegativeButton("Hủy",null).setPositiveButton("XÁC NHẬN"){_,_->val v=sp.selectedItem?.toString().orEmpty();val n=note.text.toString().trim();done(if(n.isBlank())v else "$v • $n")}.show()\n    }\n'''
s=rep(s,'\n    private fun pdaExchangeScreen(){',condition_fun+'\n    private fun pdaExchangeScreen(){','condition function')
write(p,s)

print('BETA62_PATCH_APPLIED')
