#!/usr/bin/env python3
from pathlib import Path
p=Path(__file__).resolve().parents[1]/'service/public/app.js'
s=p.read_text(encoding='utf-8')
MARK='S30_WEB_READABLE_HISTORY'
if MARK not in s:
    old='''function historyView(){const rows=state.events||[];return `<section class="panel"><div class="section-title"><div><h2>Lịch sử sự kiện</h2><p>Canonical/delta + thao tác cục bộ gần đây</p></div><span class="chip">${rows.length}</span></div><div class="table-wrap"><table><thead><tr><th>Thời gian</th><th>Loại</th><th>Đối tượng</th><th>Actor</th><th>Trạng thái</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${escapeHtml(x.committed_at||x.timestamp||x.occurred_at||'')}</td><td>${escapeHtml(x.event_type)}</td><td>${escapeHtml(x.entity_id)}</td><td>${escapeHtml(x.actor_id||'—')}</td><td>${escapeHtml(x.local_status||'CONFIRMED')}</td></tr>`).join('')}</tbody></table></div></section>`}\n'''
    new='''// S30_WEB_READABLE_HISTORY\nfunction historyPayload(x){try{return x.payload&&typeof x.payload==='object'?x.payload:JSON.parse(x.payload_json||'{}')}catch{return{}}}\nfunction historyLabel(t){return({ATTENDANCE_ENTER:'Vào ca',ATTENDANCE_EXIT:'Ra ca',RESOURCE_CHANGE:'Đổi tài nguyên',LABOR_START:'Bắt đầu công nhật',LABOR_FINISH:'Hoàn thành công nhật',MASTER_STAFF_UPSERT:'Cập nhật nhân sự',MASTER_STAFF_DELETE:'Xóa nhân sự',ACCOUNT_UPSERT:'Tạo / sửa tài khoản',ACCOUNT_STATUS:'Đổi trạng thái tài khoản',ACCOUNT_EMAIL:'Đổi email tài khoản',ACCOUNT_PASSWORD:'Đổi mật khẩu',MASTER_STAFF_IMPORT:'Import nhân sự',HISTORICAL_CORRECTION:'Chỉnh sửa có lịch sử',FALLBACK_RECONCILED_DUPLICATE:'Đối soát dữ liệu dự phòng'})[t]||t||'Thao tác'}\nfunction historyView(){const rows=state.events||[];return `<section class="panel"><div class="section-title"><div><h2>Lịch sử</h2><p>Thao tác canonical từ Service/D1 và dữ liệu cục bộ đang chờ xác nhận</p></div><span class="chip">${rows.length}</span></div><div class="table-wrap"><table><thead><tr><th>Thời gian</th><th>Thao tác</th><th>Đối tượng</th><th>Người thực hiện</th><th>Chi tiết</th><th>Trạng thái</th></tr></thead><tbody>${rows.map(x=>{const p=historyPayload(x),subject=p.mnv||p.target_id||x.entity_id||'—',label=p.target_label||p.full_name||'',detail=p.detail||p.note||p.labor_type||[p.shift,p.work_choice,p.pda_serial,p.user_pick,p.pack_table,p.user_pack].filter(Boolean).join(' · ')||`revision ${x.authority_seq??'—'}`,status=x.local_status==='LOCAL_PENDING'?'Chờ đồng bộ':x.local_status==='REJECTED'?'Bị từ chối':x.local_status==='REVIEW_REQUIRED'?'Cần đối soát':'Đã đồng bộ';return `<tr><td>${escapeHtml(x.committed_at||x.timestamp||x.occurred_at||'')}</td><td><strong>${escapeHtml(historyLabel(x.event_type))}</strong></td><td>${escapeHtml(subject)}${label?`<br><span class="muted">${escapeHtml(label)}</span>`:''}</td><td>${escapeHtml(x.actor_id||state.account?.login_id||'Hệ thống')}</td><td>${escapeHtml(detail)}</td><td><span class="badge">${escapeHtml(status)}</span></td></tr>`}).join('')}</tbody></table></div></section>`}\n'''
    if old not in s: raise SystemExit('S30 Web history anchor missing')
    s=s.replace(old,new,1)
    p.write_text(s,encoding='utf-8')
print('Applied S30 readable Web history')
