#!/usr/bin/env python3
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
OPS=ROOT/'app/src/main/java/vn/pickpack1291/app/beta/OperationsActivity.kt'
GRADLE=ROOT/'app/build.gradle.kts'


def replace_fun(src:str,name:str,new_body:str)->str:
    marker=f'    private fun {name}'
    start=src.find(marker)
    if start<0: raise SystemExit(f'missing function: {name}')
    nxt=src.find('\n    private fun ',start+len(marker))
    if nxt<0: raise SystemExit(f'missing next function after: {name}')
    return src[:start]+new_body.rstrip()+"\n"+src[nxt+1:]


g=GRADLE.read_text(encoding='utf-8')
if 'versionName = "0.4.2-beta.75"' not in g:
    g=g.replace('versionCode = 80\n            versionName = "0.4.2-beta.74"','versionCode = 81\n            versionName = "0.4.2-beta.75"',1)
GRADLE.write_text(g,encoding='utf-8')

s=OPS.read_text(encoding='utf-8')

s=replace_fun(s,'sessionWorkChangeDetail(payload:JSONObject):String{',r'''    private fun sessionWorkChangeDetail(payload:JSONObject):String{
        val before=payload.optJSONObject("before")?:JSONObject();val after=payload.optJSONObject("after")?:JSONObject()
        fun assignments(x:JSONObject):JSONArray=x.optJSONArray("resource_assignments_v64")?:x.optJSONArray("resource_assignments")?:x.optJSONArray("assignments")?:JSONArray()
        fun positions(x:JSONObject):JSONArray=x.optJSONArray("positions_v64")?:x.optJSONArray("positions")?:JSONArray()
        fun label(t:String)=when(t.uppercase()){ "PDA"->"PDA";"USER_PICK"->"User Pick";"PACK_TABLE"->"Bàn Pack";"USER_PACK"->"User Pack";else->t.ifBlank{"Tài nguyên"} }
        fun directKey(t:String)=when(t.uppercase()){ "PDA"->"pda_serial";"USER_PICK"->"user_pick";"PACK_TABLE"->"pack_table";"USER_PACK"->"user_pack";else->"" }
        fun currentResource(x:JSONObject,t:String):String{
            val direct=directKey(t).takeIf{it.isNotBlank()}?.let{x.optString(it).trim()}.orEmpty();if(direct.isNotBlank())return direct
            val a=assignments(x);val out=mutableListOf<String>();for(i in 0 until a.length()){val q=a.optJSONObject(i)?:continue;if(!q.optString("resource_type").equals(t,true))continue;if(q.optString("state").uppercase() !in setOf("","ACTIVE"))continue;val id=q.optString("resource_id").trim();if(id.isNotBlank())out.add(id)};return out.distinct().joinToString(" • ")
        }
        fun assignmentById(x:JSONObject,id:String):JSONObject?{val a=assignments(x);for(i in 0 until a.length()){val q=a.optJSONObject(i)?:continue;if(q.optString("assignment_id")==id)return q};return null}
        fun workText(x:JSONObject):String{
            val a=positions(x);val p=mutableListOf<String>();for(i in 0 until a.length()){val q=a.optJSONObject(i)?:continue;if(q.optString("state").uppercase() !in setOf("","ACTIVE"))continue;val v=q.optString("position_label").ifBlank{q.optString("position_key")}.trim();if(v.isNotBlank())p.add(v)}
            if(p.isNotEmpty())return p.distinct().joinToString(" & ")
            return when(x.optString("work_choice").uppercase()){"PICK"->"Pick";"PACK"->"Pack";"BOTH","PICK_PACK"->"Pick & Pack";"KHONG","NONE","NO"->"Không";else->x.optString("work_choice").ifBlank{"—"}}
        }
        val changes=mutableListOf<String>();val ops=payload.optJSONArray("operations")
        if(ops!=null){for(i in 0 until ops.length()){
            val q=ops.optJSONObject(i)?:continue;val op=q.optString("op").uppercase();val t=q.optString("resource_type")
            when(op){
                "ADD_RESOURCE"->{val id=q.optString("resource_id").trim();if(id.isNotBlank())changes.add("${label(t)}: — → $id")}
                "REMOVE_RESOURCE"->{val old=assignmentById(before,q.optString("assignment_id"));val rt=old?.optString("resource_type").orEmpty().ifBlank{t};val id=old?.optString("resource_id").orEmpty().ifBlank{q.optString("resource_id")}.ifBlank{currentResource(before,rt)}.ifBlank{"—"};changes.add("${label(rt)}: $id → —${q.optString("reason").takeIf{it.isNotBlank()}?.let{" • Lý do: $it"}.orEmpty()}")}
                "REPLACE_RESOURCE"->{val old=assignmentById(before,q.optString("assignment_id"));val rt=old?.optString("resource_type").orEmpty().ifBlank{t};val oldId=old?.optString("resource_id").orEmpty().ifBlank{currentResource(before,rt)}.ifBlank{"—"};val newId=q.optString("new_resource_id").ifBlank{currentResource(after,rt)}.ifBlank{"—"};changes.add("${label(rt)}: $oldId → $newId${q.optString("reason").takeIf{it.isNotBlank()}?.let{" • Lý do: $it"}.orEmpty()}")}
                "UPDATE_SHIFT"->{val old=before.optString("shift").ifBlank{"—"};val next=q.optString("shift").ifBlank{after.optString("shift")}.ifBlank{"—"};changes.add("Ca: $old → $next")}
            }
        }}
        if(before.length()>0||after.length()>0){
            val bw=workText(before);val aw=workText(after);if(bw!=aw&&bw!="—"&&aw!="—"&&changes.none{it.startsWith("Công việc trong ca:")})changes.add("Công việc trong ca: $bw → $aw")
            for(t in listOf("PDA","USER_PICK","PACK_TABLE","USER_PACK")){val b=currentResource(before,t).ifBlank{"—"};val a=currentResource(after,t).ifBlank{"—"};if(b!=a&&changes.none{it.startsWith("${label(t)}:")})changes.add("${label(t)}: $b → $a")}
            val bs=before.optString("shift");val asv=after.optString("shift");if(bs.isNotBlank()&&asv.isNotBlank()&&bs!=asv&&changes.none{it.startsWith("Ca:")})changes.add("Ca: $bs → $asv")
        }
        return changes.joinToString(" • ")
    }''')

s=replace_fun(s,'sessionWorkEditor(ctx:JSONObject,mode:String){',r'''    private fun sessionWorkEditor(ctx:JSONObject,mode:String){
        val s=ctx.optJSONObject("session")?:return;if(!s.optString("state").equals("ACTIVE",true)){showError("Phiên không còn hoạt động.");return}
        val edit=mode.equals("EDIT",true);val server=s.optJSONObject("resource_options_v64")?:JSONObject();val local=PdaLocalProjection.resourceOptions(this,s.optString("mnv"))
        fun arr(key:String):JSONArray{val a=server.optJSONArray(key);return if(a!=null&&a.length()>0)a else local.optJSONArray(key)?:JSONArray()}
        fun ids(key:String):MutableList<String>{val out=mutableListOf<String>();val a=arr(key);for(i in 0 until a.length()){val x=a.opt(i);val v=when(x){is JSONObject->x.optString("id").ifBlank{x.optString("resource_id").ifBlank{x.optString("serial")}};else->a.optString(i)}.trim();if(v.isNotBlank()&&!out.contains(v))out.add(v)};out.sortWith(Comparator{a,b->naturalUserCompare(a,b)});return out}
        class PackMap(val table:String,val user:String,val used:Boolean)
        val normalPick=ids("user_picks");val usedPick=optionIds(arr("user_picks_reissue"));val pdaIds=ids("pdas");val normalMaps=mutableListOf<PackMap>();val usedMaps=mutableListOf<PackMap>()
        fun readMaps(a:JSONArray,used:Boolean,out:MutableList<PackMap>){for(i in 0 until a.length()){val x=a.optJSONObject(i)?:continue;val table=x.optString("table").ifBlank{x.optString("pack_table")}.trim();val user=x.optString("user_pack").ifBlank{x.optString("id").ifBlank{x.optString("resource_id")}}.trim();if(table.isNotBlank()&&user.isNotBlank()&&out.none{it.table==table&&it.user==user})out.add(PackMap(table,user,used||x.optBoolean("duplicate_user")))}}
        readMaps(arr("pack_tables"),false,normalMaps);readMaps(arr("pack_tables_reissue"),true,usedMaps)
        val activePda=activeAssignments(s,"PDA").firstOrNull();val activePick=activeAssignments(s,"USER_PICK").firstOrNull();val activeTable=activeAssignments(s,"PACK_TABLE").firstOrNull();val activePack=activeAssignments(s,"USER_PACK").firstOrNull()
        val activePos=activePositions(s);val activeKeys=activePos.map{it.optString("position_key").uppercase()}.toSet();val main=s.optString("main_position_v64").trim();val positionCatalog=(listOf("PICK" to "Pick","PACK" to "Pack")+(if(main.isNotBlank()&&!main.equals("Pick",true)&&!main.equals("Pack",true))listOf(foldLocal(main).ifBlank{main.uppercase()} to main)else emptyList())).distinctBy{it.first.uppercase()}
        val choices=mutableListOf<Pair<String,String>>()
        if(edit){choices.add("Ca" to "SHIFT");if(activePda!=null)choices.add("PDA" to "PDA");if(activePick!=null)choices.add("User Pick" to "PICK");if(activeTable!=null||activePack!=null)choices.add("Bàn Pack / User Pack" to "PACK")}
        else{if(activePda==null)choices.add("PDA" to "PDA");if(activePick==null)choices.add("User Pick" to "PICK");if(activeTable==null&&activePack==null)choices.add("Pack" to "PACK");if(positionCatalog.any{it.first.uppercase() !in activeKeys})choices.add("Vị trí trong ca" to "POSITION")}
        if(choices.isEmpty()){showError(if(edit)"Không có thông tin hiện tại phù hợp để sửa." else "Không còn nội dung phù hợp để thêm.");return}
        val box=column(surface).apply{setPadding(dp(10),dp(5),dp(10),dp(8))};box.addView(info(if(edit)"Chọn đúng nội dung cần sửa. Chỉ control liên quan mới hiển thị." else "Chọn nội dung cần thêm. Chỉ phần cấu hình tương ứng mới mở."));box.addView(gap(7))
        val selector=spinner((listOf(if(edit)"Chọn nội dung cần sửa" else "Chọn nội dung cần thêm")+choices.map{it.first}).toTypedArray());box.addView(selector,matchWrap());box.addView(gap(7));val host=column(surface);box.addView(host,matchWrap())
        var makeOps:(()->JSONArray)?=null
        fun replaceOrAdd(active:JSONObject?,type:String,id:String,duplicate:Boolean=false):JSONObject?{if(id.isBlank())return null;return if(active==null)JSONObject().put("op","ADD_RESOURCE").put("resource_type",type).put("resource_id",id).put("duplicate_user",duplicate) else if(active.optString("resource_id")!=id)JSONObject().put("op","REPLACE_RESOURCE").put("assignment_id",active.optString("assignment_id")).put("resource_type",type).put("new_resource_id",id).put("reason","Cập nhật ${resourceLabel(type)} trong ca").put("disposition","USED").put("duplicate_user",duplicate) else null}
        fun render(kind:String){
            host.removeAllViews();makeOps=null
            when(kind){
                "SHIFT"->{val values=listOf("Ca 1","Ca HC","Ca 2");val sp=spinner(values.toTypedArray());selectByValue(sp,values,s.optString("shift"));host.addView(labelled("Ca",sp));makeOps={JSONArray().apply{val v=sp.selectedItem?.toString().orEmpty();if(v!=s.optString("shift"))put(JSONObject().put("op","UPDATE_SHIFT").put("shift",v))}}}
                "PDA"->{val values=pdaIds.toMutableList();activePda?.optString("resource_id")?.takeIf{it.isNotBlank()&&it !in values}?.let{values.add(0,it)};val sp=spinner((listOf("Chọn PDA")+values).toTypedArray());activePda?.optString("resource_id")?.let{val at=values.indexOf(it);if(at>=0)sp.setSelection(at+1)};host.addView(labelled(if(edit)"PDA mới" else "PDA",sp));makeOps={val id=values.getOrNull(sp.selectedItemPosition-1).orEmpty();JSONArray().apply{replaceOrAdd(activePda,"PDA",id)?.let{put(it)}}}}
                "PICK"->{var chosenUsed="";var pdaSp:Spinner?=null;var pdaValues=emptyList<String>();val pickSp=spinner((listOf("Chọn User Pick")+normalPick).toTypedArray());activePick?.optString("resource_id")?.let{val at=normalPick.indexOf(it);if(at>=0)pickSp.setSelection(at+1)}
                    fun showPick(id:String){chosenUsed=id;pickSp.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,arrayOf(id));pickSp.setSelection(0);TopNotice.show(this,"Đã chọn User Pick $id.",TopNotice.Kind.INFO)}
                    val row=row(surface).apply{gravity=Gravity.CENTER_VERTICAL;addView(pickSp,LinearLayout.LayoutParams(0,dp(48),1.25f).apply{marginEnd=dp(5)});addView(compactReissueButton("Phát lại",usedPick.isNotEmpty()){showReissueChooser("Phát lại User Pick",usedPick){i->showPick(usedPick[i])}},LinearLayout.LayoutParams(0,dp(44),.75f))};host.addView(labelled("User Pick",row));if(activePda==null){host.addView(gap(6));pdaValues=pdaIds;val sp=spinner((listOf("Chọn PDA bắt buộc")+pdaValues).toTypedArray());pdaSp=sp;host.addView(labelled("PDA — bắt buộc khi cấp User Pick",sp))}
                    makeOps={val id=chosenUsed.ifBlank{normalPick.getOrNull(pickSp.selectedItemPosition-1).orEmpty()};val out=JSONArray();if(activePda==null){val pda=pdaValues.getOrNull((pdaSp?.selectedItemPosition?:0)-1).orEmpty();replaceOrAdd(null,"PDA",pda)?.let{out.put(it)}};replaceOrAdd(activePick,"USER_PICK",id,chosenUsed.isNotBlank())?.let{out.put(it)};out}}
                "PACK"->{var tableSp:Spinner?=null;var userSp:Spinner?=null;var currentRows=normalMaps.toList();var duplicate=false
                    fun rebuild(preferredTable:String="",preferredUser:String="",used:Boolean=false){host.removeAllViews();duplicate=used;currentRows=if(used){(normalMaps+usedMaps.filter{it.table==preferredTable&&it.user==preferredUser}).distinctBy{it.table+"|"+it.user}}else normalMaps;val currentTable=activeTable?.optString("resource_id").orEmpty();val allTables=currentRows.map{it.table}.toMutableList();if(currentTable.isNotBlank()&&currentTable !in allTables)allTables.add(currentTable);val tables=allTables.distinct().sortedWith(Comparator{a,b->naturalUserCompare(a,b)});val t=spinner((listOf("Chọn Bàn Pack")+tables).toTypedArray());tableSp=t;val target=preferredTable.ifBlank{currentTable};tables.indexOf(target).takeIf{it>=0}?.let{t.setSelection(it+1)};host.addView(labelled("Bàn Pack",t));host.addView(gap(5));val userHost=column(surface);host.addView(userHost,matchWrap())
                        fun users(pref:String=""){userHost.removeAllViews();val table=tables.getOrNull(t.selectedItemPosition-1).orEmpty();val rows=currentRows.filter{it.table==table}.sortedWith(Comparator{a,b->naturalUserCompare(a.user,b.user)});val u=spinner((listOf("Chọn User Pack")+rows.map{it.user}).toTypedArray());userSp=u;val currentUser=activePack?.optString("resource_id").orEmpty();val targetUser=pref.ifBlank{currentUser};rows.indexOfFirst{it.user==targetUser}.takeIf{it>=0}?.let{u.setSelection(it+1)};val rr=row(surface).apply{gravity=Gravity.CENTER_VERTICAL;addView(u,LinearLayout.LayoutParams(0,dp(48),1.25f).apply{marginEnd=dp(5)});addView(compactReissueButton("Phát lại",usedMaps.isNotEmpty()){val labels=usedMaps.map{"${it.table} – ${it.user}"};showReissueChooser("Phát lại User Pack",labels){i->val m=usedMaps[i];rebuild(m.table,m.user,true)}},LinearLayout.LayoutParams(0,dp(44),.75f))};userHost.addView(labelled("User Pack",rr))}
                        t.onItemSelectedListener=object:android.widget.AdapterView.OnItemSelectedListener{override fun onItemSelected(p:android.widget.AdapterView<*>?,v:View?,i:Int,id:Long){users(if(tables.getOrNull(i-1)==preferredTable)preferredUser else "")};override fun onNothingSelected(p:android.widget.AdapterView<*>?)=Unit};users(preferredUser)
                    };rebuild();makeOps={val table=(tableSp?.selectedItem?.toString()?:"").takeIf{it!="Chọn Bàn Pack"}.orEmpty();val user=(userSp?.selectedItem?.toString()?:"").takeIf{it!="Chọn User Pack"}.orEmpty();JSONArray().apply{replaceOrAdd(activeTable,"PACK_TABLE",table)?.let{put(it)};replaceOrAdd(activePack,"USER_PACK",user,duplicate)?.let{put(it)}}}}
                "POSITION"->{val available=positionCatalog.filter{it.first.uppercase() !in activeKeys};val labels=available.map{it.second};val sp=spinner((listOf("Chọn vị trí cần thêm")+labels).toTypedArray());host.addView(labelled("Vị trí trong ca",sp));makeOps={val x=available.getOrNull(sp.selectedItemPosition-1);JSONArray().apply{if(x!=null)put(JSONObject().put("op","ADD_POSITION").put("position_key",x.first.uppercase()).put("position_label",x.second))}}}
            }
        }
        selector.onItemSelectedListener=object:android.widget.AdapterView.OnItemSelectedListener{override fun onItemSelected(p:android.widget.AdapterView<*>?,v:View?,i:Int,id:Long){render(choices.getOrNull(i-1)?.second.orEmpty())};override fun onNothingSelected(p:android.widget.AdapterView<*>?)=Unit}
        AlertDialog.Builder(this).setTitle(if(edit)"Sửa thông tin trong ca" else "Thêm thông tin trong ca").setView(ScrollView(this).apply{addView(box)}).setNegativeButton("Hủy",null).setPositiveButton(if(edit)"LƯU" else "THÊM"){_,_->val ops=makeOps?.invoke()?:JSONArray();if(ops.length()==0){showError("Chọn nội dung và giá trị cần ${if(edit)"sửa" else "thêm"}.");return@setPositiveButton};if(ops.toString().contains("\"resource_type\":\"USER_PICK\"")&&activePda==null&&!ops.toString().contains("\"resource_type\":\"PDA\"")){showError("User Pick bắt buộc phải có PDA.");return@setPositiveButton};submitResourceMutation(ctx,ops,if(edit)"Sửa thông tin trong ca" else "Thêm thông tin trong ca")}.show()
    }''')

s=replace_fun(s,'deleteSessionWork(ctx:JSONObject){',r'''    private fun deleteSessionWork(ctx:JSONObject){
        val s=ctx.optJSONObject("session")?:return;val assignments=activeAssignments(s);val positions=activePositions(s)
        class Item(val label:String,val assignment:JSONObject?=null,val position:JSONObject?=null)
        val items=mutableListOf<Item>();for(a in assignments)items.add(Item("${resourceLabel(a.optString("resource_type"))}: ${a.optString("resource_id")}",assignment=a));for(p in positions)items.add(Item("Vị trí: ${p.optString("position_label").ifBlank{p.optString("position_key")}}",position=p))
        if(items.isEmpty()){showError("Phiên không có thông tin công việc có thể xóa.");return}
        val box=column(surface).apply{setPadding(dp(10),dp(5),dp(10),dp(8))};box.addView(info("Chọn đúng một nội dung đang tồn tại. Chỉ phần xác nhận liên quan mới hiển thị."));box.addView(gap(7));val selector=spinner((listOf("Chọn nội dung cần xóa")+items.map{it.label}).toTypedArray());box.addView(selector,matchWrap());box.addView(gap(7));val host=column(surface);box.addView(host,matchWrap())
        var selected:Item?=null;var disposition:Spinner?=null;var reason:EditText?=null
        fun render(i:Int){host.removeAllViews();selected=items.getOrNull(i-1);disposition=null;reason=null;val x=selected?:return;if(x.assignment!=null){val d=spinner(arrayOf("Đã sử dụng / có sản lượng","Cấp nhầm / chưa sử dụng"));val r=input("Lý do xóa",false);disposition=d;reason=r;host.addView(labelled("Xử lý tài nguyên sau khi xóa",d));host.addView(gap(6));host.addView(r,matchWrap())}else{val r=input("Lý do xóa vị trí",false);reason=r;host.addView(r,matchWrap())}}
        selector.onItemSelectedListener=object:android.widget.AdapterView.OnItemSelectedListener{override fun onItemSelected(p:android.widget.AdapterView<*>?,v:View?,i:Int,id:Long){render(i)};override fun onNothingSelected(p:android.widget.AdapterView<*>?)=Unit}
        val full=smallButton("XÓA TOÀN BỘ PHIÊN VÀO – RA",red);box.addView(gap(10));box.addView(full,matchWrap());var dialog:AlertDialog?=null
        full.setOnClickListener{val r=input("Lý do xóa toàn bộ phiên",false).apply{setText("Xóa phiên theo xác nhận thực tế")};AlertDialog.Builder(this).setTitle("Xóa toàn bộ phiên?").setView(r).setNegativeButton("Hủy",null).setPositiveButton("XÁC NHẬN"){_,_->if(r.text.toString().trim().length<3){showError("Nhập lý do xóa phiên.");return@setPositiveButton};verifyDeletePassword("xóa toàn bộ phiên"){api.call("attendance_session_delete",JSONObject().put("session_id",s.optString("session_id")).put("reason",r.text.toString().trim()).put("idempotency_key",UUID.randomUUID().toString())){x->runOnUiThread{if(!x.ok){showError(x.error?:"Không xóa được phiên");return@runOnUiThread};dialog?.dismiss();TopNotice.show(this,"Đã xóa phiên; audit chi tiết vẫn được giữ.",TopNotice.Kind.SUCCESS);employeeScan()}}}}.show()}
        dialog=AlertDialog.Builder(this).setTitle("Xóa thông tin trong ca").setView(ScrollView(this).apply{addView(box)}).setNegativeButton("Hủy",null).setPositiveButton("XÓA"){_,_->val x=selected?:run{showError("Chọn nội dung cần xóa.");return@setPositiveButton};val why=reason?.text?.toString()?.trim().orEmpty();if(why.length<2){showError("Nhập lý do xóa.");return@setPositiveButton};val ops=JSONArray();if(x.assignment!=null)ops.put(JSONObject().put("op","REMOVE_RESOURCE").put("assignment_id",x.assignment.optString("assignment_id")).put("resource_type",x.assignment.optString("resource_type")).put("resource_id",x.assignment.optString("resource_id")).put("reason",why).put("disposition",if(disposition?.selectedItemPosition==1)"AVAILABLE" else "USED"))else x.position?.let{ops.put(JSONObject().put("op","REMOVE_POSITION").put("position_key",it.optString("position_key")).put("reason",why))};submitResourceMutation(ctx,ops,"Xóa thông tin trong ca")}.create();dialog?.show()
    }''')

s=replace_fun(s,'shiftInfoRows(s:JSONObject,ended:Boolean)=listOf(',r'''    private fun shiftInfoRows(s:JSONObject,ended:Boolean)=listOf(
        "Ca" to dash(s.optString("shift")),
        "Thời gian vào" to formatIso(s.optString("enter_at")),
        "Thời gian ra" to if(ended)formatIso(s.optString("exit_at")) else "—"
    )''')

s=replace_fun(s,'workInfoRows(s:JSONObject,ended:Boolean):List<Pair<String,String>>{',r'''    private fun workInfoRows(s:JSONObject,ended:Boolean):List<Pair<String,String>>{
        val positions=(if(ended)allPositionLabels(s) else activePositionLabels(s)).distinct().toMutableList()
        if(positions.isEmpty()){if(s.optString("pda_serial").isNotBlank()||s.optString("user_pick").isNotBlank())positions.add("Pick");if(s.optString("pack_table").isNotBlank()||s.optString("user_pack").isNotBlank())positions.add("Pack")}
        val rawPick=shiftResourceValue(s,"USER_PICK",ended);val hasPick=positions.any{it.equals("Pick",true)}||shiftResourceValue(s,"PDA",ended)!="—";val pickDisplay=if(hasPick&&rawPick=="—")"Đang dùng tài khoản ${login.ifBlank{"—"}} / ${name.ifBlank{"—"}} cố định" else rawPick
        return listOf("Vị trí trong ca" to if(positions.isEmpty())"Làm theo vị trí chính" else positions.joinToString(" & "),"PDA" to shiftResourceValue(s,"PDA",ended),"Bàn Pack" to shiftResourceValue(s,"PACK_TABLE",ended),"User Pick" to pickDisplay,"User Pack" to shiftResourceValue(s,"USER_PACK",ended))
    }''')

s=replace_fun(s,'renderEnter(body:LinearLayout,ctx:JSONObject,masters:JSONObject){',r'''    private fun renderEnter(body:LinearLayout,ctx:JSONObject,masters:JSONObject){
        val e=ctx.optJSONObject("employee")?:JSONObject();val mnv=e.optString("mnv");val main=e.optString("main_position").trim();body.addView(section("PHÂN CÔNG TRONG CA"))
        val now=java.time.LocalTime.now(ZoneId.of("Asia/Ho_Chi_Minh"));var shiftValue=when{now.isBefore(java.time.LocalTime.of(8,0))->"Ca 1";now.isBefore(java.time.LocalTime.of(10,0))->"Ca HC";else->"Ca 2"}
        val mainPick=main.equals("Pick",true);val mainPack=main.equals("Pack",true);val third=if(mainPick||mainPack)"Không" else main.ifBlank{"Không"};val thirdKey=if(third=="Không")"NONE" else foldLocal(third).ifBlank{third.uppercase()};val positionChoices=listOf("Pick" to "PICK","Pack" to "PACK",third to thirdKey)
        var posKey=when{mainPick->"PICK";mainPack->"PACK";else->thirdKey};var posLabel=positionChoices.firstOrNull{it.second==posKey}?.first?:third
        val shiftBox=column(bg);shiftBox.addView(segmentedChoice(listOf("Ca 1" to "Ca 1","Ca HC" to "Ca HC","Ca 2" to "Ca 2"),shiftValue){shiftValue=it},matchWrap());body.addView(labelled("Ca",shiftBox));body.addView(gap(7))
        val resource=column(bg);var pdaField:AutoCompleteTextView?=null;var selectedPda:JSONObject?=null;var pickSpin:Spinner?=null;var pickChoices=mutableListOf<Pair<String,Boolean>>();var preferredPick="";var tableSpin:Spinner?=null;var packSelection:JSONObject?=null;var preferredPackTable="";var preferredPackUser="";var preferredPackUsed=false
        val pdas=masters.optJSONArray("pdas")?:JSONArray();val picks=masters.optJSONArray("user_picks")?:JSONArray();val pickUsed=masters.optJSONArray("user_picks_reissue")?:JSONArray();val packRows=masters.optJSONArray("pack_tables")?:JSONArray();val packUsedRows=masters.optJSONArray("pack_tables_reissue")?:JSONArray()
        fun maps(src:JSONArray,used:Boolean):MutableList<JSONObject>{val out=mutableListOf<JSONObject>();for(i in 0 until src.length()){val q=src.optJSONObject(i)?:continue;val table=q.optString("table").ifBlank{q.optString("pack_table")}.trim();val user=q.optString("user_pack").ifBlank{q.optString("id").ifBlank{q.optString("resource_id")}}.trim();if(table.isNotBlank()&&user.isNotBlank())out.add(JSONObject(q.toString()).put("table",table).put("user_pack",user).put("duplicate_user",used||q.optBoolean("duplicate_user")))};return out}
        val normalPack=maps(packRows,false);val usedPack=maps(packUsedRows,true)
        fun rebuildResources(){
            resource.removeAllViews();pdaField=null;selectedPda=null;pickSpin=null;pickChoices.clear();tableSpin=null;packSelection=null
            if(posKey=="PICK"){
                pdaField=pdaInput(pdas,onSelected={selectedPda=it});resource.addView(labelled("PDA — gõ 5 số cuối",pdaField!!));resource.addView(gap(4));resource.addView(pdaSelectedPanel(pdas,pdaField!!));resource.addView(gap(5))
                val normal=mutableListOf<String>();for(i in 0 until picks.length()){val v=picks.optString(i).trim();if(v.isNotBlank()&&!normal.contains(v))normal.add(v)};normal.sortWith(Comparator{a,b->naturalUserCompare(a,b)})
                val labels=mutableListOf("Không dùng hy1.outbound");pickChoices.add("" to false);normal.forEach{pickChoices.add(it to false);labels.add(it)};if(preferredPick.isNotBlank()&&preferredPick !in normal){pickChoices.add(preferredPick to true);labels.add(preferredPick)}
                pickSpin=spinner(labels.toTypedArray());preferredPick.takeIf{it.isNotBlank()}?.let{v->pickChoices.indexOfFirst{it.first==v}.takeIf{it>=0}?.let{pickSpin?.setSelection(it)}}
                val usedIds=optionIds(pickUsed);val userRow=row(bg).apply{gravity=Gravity.CENTER_VERTICAL;addView(pickSpin!!,LinearLayout.LayoutParams(0,dp(50),1.35f).apply{marginEnd=dp(5)});addView(compactReissueButton("Phát lại",usedIds.isNotEmpty()){showReissueChooser("Phát lại User Pick",usedIds){i->preferredPick=usedIds[i];rebuildResources()}},LinearLayout.LayoutParams(0,dp(46),.85f))};resource.addView(labelled("User Pick",userRow))
            }else if(posKey=="PACK"){
                val chosenUsed=usedPack.filter{it.optString("table")==preferredPackTable&&it.optString("user_pack")==preferredPackUser};val mappings=(normalPack+chosenUsed).distinctBy{it.optString("table")+"|"+it.optString("user_pack")};val tables=mappings.map{it.optString("table")}.filter{it.isNotBlank()}.distinct().sortedWith(Comparator{a,b->naturalUserCompare(a,b)})
                tableSpin=spinner((if(tables.isEmpty())listOf("Không có Bàn Pack khả dụng")else tables).toTypedArray());preferredPackTable.takeIf{it.isNotBlank()}?.let{v->tables.indexOf(v).takeIf{it>=0}?.let{tableSpin?.setSelection(it)}};resource.addView(labelled("Bàn Pack — bắt buộc",tableSpin!!));resource.addView(gap(5));val userHost=column(bg);resource.addView(userHost,matchWrap())
                fun renderUsers(){userHost.removeAllViews();packSelection=null;if(tables.isEmpty()){userHost.addView(info("Không có User Pack theo Bàn Pack khả dụng."));return};val table=tables.getOrNull(tableSpin?.selectedItemPosition?:0).orEmpty();preferredPackTable=table;val rows=mappings.filter{it.optString("table")==table}.sortedWith(Comparator{a,b->naturalUserCompare(a.optString("user_pack"),b.optString("user_pack"))});val u=spinner((if(rows.isEmpty())listOf("Không có User Pack")else rows.map{it.optString("user_pack")}).toTypedArray());val target=preferredPackUser;val at=rows.indexOfFirst{it.optString("user_pack")==target};if(at>=0)u.setSelection(at);packSelection=rows.getOrNull(if(at>=0)at else 0);u.onItemSelectedListener=object:android.widget.AdapterView.OnItemSelectedListener{override fun onItemSelected(p:android.widget.AdapterView<*>?,v:View?,i:Int,id:Long){packSelection=rows.getOrNull(i);preferredPackUser=packSelection?.optString("user_pack").orEmpty();preferredPackUsed=packSelection?.optBoolean("duplicate_user")?:false};override fun onNothingSelected(p:android.widget.AdapterView<*>?)=Unit};val reissueLabels=usedPack.map{"${it.optString("table")} – ${it.optString("user_pack")}"};val row=row(bg).apply{gravity=Gravity.CENTER_VERTICAL;addView(u,LinearLayout.LayoutParams(0,dp(50),1.35f).apply{marginEnd=dp(5)});addView(compactReissueButton("Phát lại",usedPack.isNotEmpty()){showReissueChooser("Phát lại User Pack",reissueLabels){i->val q=usedPack[i];preferredPackTable=q.optString("table");preferredPackUser=q.optString("user_pack");preferredPackUsed=true;rebuildResources()}},LinearLayout.LayoutParams(0,dp(46),.85f))};userHost.addView(labelled("User Pack theo Bàn Pack",row))}
                tableSpin?.onItemSelectedListener=object:android.widget.AdapterView.OnItemSelectedListener{override fun onItemSelected(p:android.widget.AdapterView<*>?,v:View?,i:Int,id:Long){val t=tables.getOrNull(i).orEmpty();if(t!=preferredPackTable){preferredPackTable=t;preferredPackUser="";preferredPackUsed=false};renderUsers()};override fun onNothingSelected(p:android.widget.AdapterView<*>?)=Unit};renderUsers()
            }
        }
        val posBox=column(bg);posBox.addView(segmentedChoice(positionChoices,posKey){k->posKey=k;posLabel=positionChoices.firstOrNull{it.second==k}?.first?:k;preferredPick="";preferredPackTable="";preferredPackUser="";preferredPackUsed=false;rebuildResources()},matchWrap());body.addView(labelled("Vị trí trong ca",posBox));body.addView(gap(7));body.addView(resource,matchWrap());rebuildResources()
        val enter=primary("VÀO CA",teal){};enter.setOnClickListener{val positions=JSONArray();if(posKey!="NONE")positions.put(JSONObject().put("position_key",posKey).put("position_label",posLabel));val resources=JSONArray();if(posKey=="PICK"){val typed=pdaField?.text?.toString()?.trim().orEmpty();val p=selectedPda?:resolvePdaObject(pdas,typed);val expected=p?.optString("last5").orEmpty().ifBlank{p?.optString("serial").orEmpty().takeLast(5)};if(p==null||typed!=expected){showError("Vị trí Pick bắt buộc chọn PDA bằng đúng 5 số cuối.");return@setOnClickListener};resources.put(JSONObject().put("resource_type","PDA").put("resource_id",p.optString("serial")).put("pda_enter_status",p.optString("status")));val choice=pickChoices.getOrNull(pickSpin?.selectedItemPosition?:0)?:("" to false);if(choice.first.isNotBlank())resources.put(JSONObject().put("resource_type","USER_PICK").put("resource_id",choice.first).put("duplicate_user",choice.second))};if(posKey=="PACK"){val q=packSelection;val table=q?.optString("table").orEmpty().trim();val user=q?.optString("user_pack").orEmpty().trim();if(q==null||table.isBlank()||user.isBlank()){showError("Chọn đủ Bàn Pack và User Pack đúng theo bàn.");return@setOnClickListener};resources.put(JSONObject().put("resource_type","PACK_TABLE").put("resource_id",table));resources.put(JSONObject().put("resource_type","USER_PACK").put("resource_id",user).put("duplicate_user",preferredPackUsed||q.optBoolean("duplicate_user")))};val gen=employeeLookupGeneration;enter.isEnabled=false;enter.text="ĐANG VÀO CA...";api.call("attendance_enter_v2",JSONObject().put("mnv",mnv).put("shift",shiftValue).put("positions",positions).put("resources",resources).put("idempotency_key",UUID.randomUUID().toString())){r->runOnUiThread{enter.isEnabled=true;enter.text="VÀO CA";if(!r.ok){showError(r.error?:"VÀO CA thất bại");return@runOnUiThread};TopNotice.show(this,"Đã ghi nhận vào ca.",TopNotice.Kind.SUCCESS);foregroundSync.requestSync();if(gen==employeeLookupGeneration&&liveEmployeeMnv==mnv)scheduleAttendanceAutoReset(mnv,gen)}}};body.addView(gap(8));body.addView(enter,matchWrap())
    }''')

s=replace_fun(s,'pdaExchangeScreen(){',r'''    private fun pdaExchangeScreen(){
        module="PDA_EXCHANGE";screenState="PDA_EXCHANGE";val root=baseRoot("ĐỔI / TRẢ PDA");val body=body();val serialField=input("Nhập 5 số cuối PDA",false).apply{setSingleLine(true);inputType=InputType.TYPE_CLASS_NUMBER;keyListener=DigitsKeyListener.getInstance("0123456789");imeOptions=EditorInfo.IME_ACTION_DONE}
        body.addView(txt("PDA ĐANG ĐƯỢC SỬ DỤNG",13f,navy,true));body.addView(txt("Nhập 5 số cuối để lọc. Mỗi PDA có thao tác Đổi và Trả riêng.",9.7f,muted,false));body.addView(gap(7));body.addView(labelled("Tìm nhanh PDA",serialField));body.addView(gap(8));val listBox=column(bg);body.addView(listBox,matchWrap())
        val changeReasons=arrayOf("PDA lỗi quét / không đọc mã","PDA lỗi mạng / không đồng bộ","PDA yếu pin / hết pin","PDA lỗi phần cứng / hư hỏng","PDA treo / hoạt động không ổn định","Đổi theo điều phối vận hành","Khác")
        val returnReasons=arrayOf("Đi công nhật","Làm xong sớm","Về sớm","Chuyển sang Pack","Điều chuyển sang công việc / vị trí không cần PDA","Tạm dừng Pick theo điều phối","Khác")
        fun chooseReason(title:String,items:Array<String>,done:(String)->Unit){AlertDialog.Builder(this).setTitle(title).setItems(items){_,which->val chosen=items[which];if(chosen!="Khác"){done(chosen);return@setItems};val other=input("Nhập lý do",false);AlertDialog.Builder(this).setTitle("Lý do khác").setView(other).setNegativeButton("Hủy",null).setPositiveButton("XÁC NHẬN"){_,_->val v=other.text.toString().trim();if(v.isBlank())showError("Nhập lý do.")else done(v)}.show()}.setNegativeButton("Hủy",null).show()}
        fun matches(serial:String,typed:String):Boolean{val q=typed.trim();if(q.isBlank())return true;return q.length==5&&q.all{it.isDigit()}&&serial.takeLast(5)==q}
        fun refreshList(filter:String){listBox.removeAllViews();listBox.addView(info("Đang tải PDA đang sử dụng..."));api.call("resource_master_list"){rr->runOnUiThread{listBox.removeAllViews();if(handleAuth(rr))return@runOnUiThread
            class Holder(val serial:String,val mnv:String,var status:String);val holders=linkedMapOf<String,Holder>();val day=operationalStore.loadDay(operationalStore.businessDate());val sessions=day?.optJSONArray("sessions")?:JSONArray();for(i in 0 until sessions.length()){val x=sessions.optJSONObject(i)?:continue;if(!x.optString("state").equals("ACTIVE",true))continue;val serial=x.optString("pda_serial").trim();val mnv=x.optString("mnv").trim();if(serial.isBlank()||mnv.isBlank()||!matches(serial,filter))continue;holders[serial]=Holder(serial,mnv,x.optString("pda_enter_status").ifBlank{"—"})}
            if(rr.ok){val resources=rr.json?.optJSONArray("resources")?:JSONArray();for(i in 0 until resources.length()){val x=resources.optJSONObject(i)?:continue;if(!x.optString("resource_type").equals("PDA",true))continue;val serial=x.optString("resource_id").trim();holders[serial]?.status=x.optString("status_label").ifBlank{holders[serial]?.status?:"—"}}}else TopNotice.show(this@OperationsActivity,"Chưa tải được tình trạng PDA từ Service; vẫn giữ danh sách đang dùng trên thiết bị.",TopNotice.Kind.WARNING)
            val rows=holders.values.sortedWith(Comparator{a,b->naturalUserCompare(a.serial,b.serial)});if(rows.isEmpty()){listBox.addView(info(if(filter.isBlank())"Hiện không có PDA nào đang được sử dụng." else "Không có PDA đang dùng khớp 5 số cuối."));return@runOnUiThread}
            fun loadSession(h:Holder,done:(JSONObject,JSONObject)->Unit){api.call("employee_context",JSONObject().put("mnv",h.mnv).put("include_options",true)){r->runOnUiThread{if(handleAuth(r))return@runOnUiThread;if(!r.ok){showError(r.error?:"Không tải được phiên");return@runOnUiThread};val c=r.json?:JSONObject();val ses=c.optJSONObject("session")?:JSONObject();if(!c.optString("state").equals("ACTIVE",true)||!ses.optString("pda_serial").equals(h.serial,true)){showError("PDA đã thay đổi người dùng hoặc phiên. Đồng bộ lại rồi thử lại.");foregroundSync.requestSync();refreshList(serialField.text.toString());return@runOnUiThread};done(c,ses)}}}
            fun mutate(h:Holder,ses:JSONObject,next:String,kind:String,why:String){val p=JSONObject().put("session_id",ses.optString("session_id")).put("mnv",h.mnv).put("shift",ses.optString("shift")).put("work_choice",ses.optString("work_choice")).put("pda_serial",next).put("user_pick",ses.optString("user_pick")).put("pack_table",ses.optString("pack_table")).put("user_pack",ses.optString("user_pack")).put("resource_note",ses.optString("resource_note")).put("preserve_work_choice",true).put("mutation_kind","EDIT").put("audit_note","$kind PDA • $why").put("idempotency_key",UUID.randomUUID().toString());api.call("session_work_update",p){x->runOnUiThread{if(handleAuth(x))return@runOnUiThread;if(!x.ok)showError(x.error?:"Không cập nhật được PDA")else{TopNotice.show(this,"Đã ${if(kind=="Đổi")"đổi" else "trả"} PDA và lưu lịch sử.",TopNotice.Kind.SUCCESS);foregroundSync.requestSync();refreshList(serialField.text.toString())}}}}
            fun change(h:Holder){loadSession(h){_,ses->val pdas=MasterDataCache.resourceOptions(this).optJSONArray("pdas")?:JSONArray();val field=pdaInput(pdas,h.serial);val wrap=column(surface).apply{setPadding(dp(10),dp(4),dp(10),dp(8));addView(txt("PDA hiện tại: ${h.serial}",12f,navy,true));addView(txt("Tình trạng: ${h.status}",10f,muted,true));addView(gap(7));addView(labelled("PDA mới — gõ 5 số cuối",field));addView(gap(5));addView(pdaSelectedPanel(pdas,field))};AlertDialog.Builder(this).setTitle("Đổi PDA").setView(wrap).setNegativeButton("Hủy",null).setPositiveButton("TIẾP TỤC"){_,_->val next=resolvePda(pdas,field.text.toString());if(next==null||next.equals(h.serial,true)){showError("Chọn PDA mới khác PDA hiện tại.");return@setPositiveButton};confirmPdaHandoverCondition(ses,h.serial,"Đổi PDA"){condition->chooseReason("Lý do đổi PDA",changeReasons){why->mutate(h,ses,next,"Đổi","$why • Tình trạng bàn giao: $condition")}}}.show()}}
            fun giveBack(h:Holder){loadSession(h){_,ses->confirmPdaHandoverCondition(ses,h.serial,"Trả PDA"){condition->chooseReason("Lý do trả PDA",returnReasons){why->mutate(h,ses,"","Trả","$why • Tình trạng bàn giao: $condition")}}}}
            rows.forEach{h->val e=MasterDataCache.employee(this,h.mnv)?:JSONObject().put("mnv",h.mnv);val item=column(bg).apply{setPadding(dp(2),dp(8),dp(2),dp(8))};val top=row(bg).apply{gravity=Gravity.CENTER_VERTICAL};top.addView(column(bg).apply{addView(txt(h.serial,15.5f,navy,true));addView(txt("Tình trạng: ${h.status.ifBlank{"—"}}",10f,teal,true))},LinearLayout.LayoutParams(0,-2,1f));item.addView(top,matchWrap());item.addView(gap(3));item.addView(txt("${e.optString("mnv")} • ${e.optString("full_name")}",11f,ink,true));item.addView(txt("${dash(e.optString("main_position"))} • ${dash(e.optString("supplier"))}",9.4f,muted,false));item.addView(gap(6));val actions=row(bg);actions.addView(smallButton("Đổi PDA",teal).apply{setOnClickListener{change(h)}},LinearLayout.LayoutParams(0,dp(42),1f).apply{marginEnd=dp(4)});actions.addView(smallButton("Trả PDA",orange).apply{setOnClickListener{giveBack(h)}},LinearLayout.LayoutParams(0,dp(42),1f).apply{marginStart=dp(4)});item.addView(actions,matchWrap());item.addView(View(this@OperationsActivity).apply{setBackgroundColor(line)},LinearLayout.LayoutParams(-1,dp(1)).apply{topMargin=dp(9)});listBox.addView(item,matchWrap())}
        }}}
        bindScannerEnter(serialField){hideSoftKeyboard(serialField);refreshList(serialField.text.toString())};attach(root,body);foregroundSync.requestSync();refreshList("");serialField.requestFocus()
    }''')

s=replace_fun(s,'pdaSelectedPanel(pdas:JSONArray,field:AutoCompleteTextView):TextView{',r'''    private fun pdaSelectedPanel(pdas:JSONArray,field:AutoCompleteTextView):TextView{
        val panel=txt("Serial PDA\nChưa chọn\nTình trạng PDA\n—",11.2f,navy,false).apply{setPadding(dp(10),dp(8),dp(10),dp(8));background=ColorDrawable(Color.rgb(239,246,255))}
        fun update(){val p=(field.tag as? JSONObject)?:resolvePdaObject(pdas,field.text?.toString().orEmpty());val serial=p?.optString("serial").orEmpty();val status=p?.optString("status").orEmpty();val full="Serial PDA\n${serial.ifBlank{"Chưa chọn"}}\nTình trạng PDA\n${status.ifBlank{"—"}}";val styled=android.text.SpannableStringBuilder(full);val a=full.indexOf('\n')+1;val b=full.indexOf('\n',a);val c=full.lastIndexOf('\n')+1;if(b>a){styled.setSpan(android.text.style.StyleSpan(Typeface.BOLD),a,b,android.text.Spanned.SPAN_EXCLUSIVE_EXCLUSIVE);styled.setSpan(android.text.style.RelativeSizeSpan(1.18f),a,b,android.text.Spanned.SPAN_EXCLUSIVE_EXCLUSIVE)};if(c<full.length)styled.setSpan(android.text.style.StyleSpan(Typeface.BOLD),c,full.length,android.text.Spanned.SPAN_EXCLUSIVE_EXCLUSIVE);panel.text=styled;panel.setTextColor(if(serial.isBlank())muted else navy)}
        field.addTextChangedListener(object:TextWatcher{override fun beforeTextChanged(v:CharSequence?,start:Int,count:Int,after:Int)=Unit;override fun onTextChanged(v:CharSequence?,start:Int,before:Int,count:Int)=update();override fun afterTextChanged(v:Editable?)=Unit});update();return panel
    }''')

# Strong regression invariants for owner scope.
assert 'versionName = "0.4.2-beta.75"' in GRADLE.read_text(encoding='utf-8')
assert 'versionCode = 81' in GRADLE.read_text(encoding='utf-8')
assert 'Dùng user cố định theo số điện thoại / họ tên.' not in s
assert 'Không dùng hy1.outbound' in s
assert 'Trạng thái hoàn tất phiên' not in s
assert 'Chạm vào thẻ PDA' not in s
assert 'ĐANG SỬ DỤNG' not in s
assert 'compactReissueButton("Phát lại"' in s
assert '"${it.table} – ${it.user}"' in s
assert 'Serial PDA\\n' in s and 'Tình trạng PDA\\n' in s
assert 'Chọn nội dung cần thêm' in s and 'Chọn nội dung cần sửa' in s and 'Chọn nội dung cần xóa' in s
assert 'Công việc trong ca: $bw → $aw' in s
assert 'Bàn Pack' in s
assert 'arrayOf("PDA lỗi quét / không đọc mã","PDA lỗi mạng / không đồng bộ","PDA yếu pin / hết pin","PDA lỗi phần cứng / hư hỏng","PDA treo / hoạt động không ổn định","Đổi theo điều phối vận hành","Khác")' in s
assert 'arrayOf("Đi công nhật","Làm xong sớm","Về sớm","Chuyển sang Pack","Điều chuyển sang công việc / vị trí không cần PDA","Tạm dừng Pick theo điều phối","Khác")' in s
OPS.write_text(s,encoding='utf-8')
print('Beta75 contextual UI materialized')
