#!/usr/bin/env python3
from pathlib import Path
import re

ROOT=Path(__file__).resolve().parents[1]

def read(path): return (ROOT/path).read_text(encoding='utf-8')
def write(path,text): (ROOT/path).write_text(text,encoding='utf-8')
def replace_once(text,old,new,label):
    n=text.count(old)
    if n!=1: raise SystemExit(f'{label}: expected 1 occurrence, got {n}')
    return text.replace(old,new,1)

# 1) Foreground realtime: expose DAY_CHANGED immediately, before sync_status/delta reconciliation.
p='app/src/main/java/vn/pickpack1291/app/beta/ForegroundSyncCoordinator.kt'
s=read(p)
s=replace_once(s,
'''    interface Listener {\n        fun onStatus(status: Status)\n        fun onAuthExpired()\n    }''',
'''    interface Listener {\n        fun onStatus(status: Status)\n        fun onDayInvalidation(invalidation: JSONObject) {}\n        fun onAuthExpired()\n    }''','foreground listener')
s=replace_once(s,
'''        main.post {\n            if (state != State.ACTIVE) return@post\n            val seq = invalidation.optLong("authority_seq", 0L)\n            if (seq > lastSeq || invalidation.optLong("day_revision", 0L) > 0L) requestSync()\n        }''',
'''        main.post {\n            if (state != State.ACTIVE) return@post\n            // UI gets the invalidation immediately; canonical correctness still comes from the\n            // subsequent revision/delta reconcile. This removes the extra sync_status RTT from\n            // visible warning/list refresh on another PDA.\n            listener.onDayInvalidation(JSONObject(invalidation.toString()))\n            val seq = invalidation.optLong("authority_seq", 0L)\n            if (seq > lastSeq || invalidation.optLong("day_revision", 0L) > 0L) requestSync()\n        }''','foreground day invalidation')
write(p,s)

# 2) Service: SUPERADMIN-only canonical bulk exit for old sessions; any labor => skip; PDA auto-confirmed.
p='service/src/mobile_hotfix.ts';s=read(p)
s=replace_once(s,'import { currentAuthority } from "./core";','import { commitMutation, currentAuthority } from "./core";','service core import')
s=replace_once(s,'import { apiError, b64u, b64uDecode, hmacB64u, json, nowIso, readJsonBody } from "./util";','import { apiError, b64u, b64uDecode, hmacB64u, json, nowIso, readJsonBody } from "./util";\nimport type { AuthContext } from "./domain";','service auth type import')
needle='''async function oldActiveSessions(env:Env):Promise<Response>{\n  const date=await businessDate(env.DB);\n  const items=(await env.DB.prepare("SELECT s.session_id,s.mnv,s.business_date,s.shift,s.work_choice,s.state,s.pda_serial,s.user_pick,s.pack_table,s.user_pack,s.enter_at,s.version,COALESCE(e.full_name,'') full_name FROM attendance_sessions s LEFT JOIN employees e ON e.mnv=s.mnv WHERE s.state='ACTIVE' AND s.business_date<?1 ORDER BY s.business_date ASC,s.enter_at ASC,s.mnv ASC").bind(date).all<Record<string,unknown>>()).results??[];\n  return json({ok:true,source:"SERVICE_D1",business_date:date,count:items.length,items});\n}\n'''
insert=needle+'''\nasync function oldActiveSessionsBulkExit(env:Env,auth:AuthContext):Promise<Response>{\n  if(auth.role!=="SUPERADMIN")return apiError("SUPERADMIN_REQUIRED","PERMISSION",403);\n  const date=await businessDate(env.DB);\n  const items=(await env.DB.prepare(`SELECT s.session_id,s.mnv,s.business_date,s.shift,s.pda_serial,s.version,\n      (SELECT COUNT(*) FROM labor_sessions l WHERE l.mnv=s.mnv AND l.business_date=s.business_date) labor_count\n    FROM attendance_sessions s\n    WHERE s.state='ACTIVE' AND s.business_date<?1\n    ORDER BY s.business_date ASC,s.enter_at ASC,s.mnv ASC`).bind(date).all<Record<string,unknown>>()).results??[];\n  let exited=0;const skippedLabor:Array<Record<string,unknown>>=[];const failed:Array<Record<string,unknown>>=[];\n  for(const row of items){\n    const sessionId=String(row.session_id||""),mnv=String(row.mnv||""),businessDateValue=String(row.business_date||"");\n    if(Number(row.labor_count||0)>0){skippedLabor.push({session_id:sessionId,mnv,business_date:businessDateValue,reason:"HAS_LABOR"});continue;}\n    try{\n      await commitMutation(env.DB,env,auth,{\n        event_id:crypto.randomUUID(),event_type:"ATTENDANCE_EXIT",entity_type:"ATTENDANCE_SESSION",entity_id:sessionId,\n        business_date:businessDateValue,base_version:Number(row.version||0),timestamp:nowIso(),\n        payload:{mnv,pda_exit_status:"SUPERADMIN_CONFIRMED",resource_note:"SUPERADMIN_BULK_OLD_SESSION_EXIT",superadmin_bulk_exit:true,pda_auto_confirmed:Boolean(String(row.pda_serial||""))},\n        idempotency_key:`OLD_SESSION_BULK_EXIT|${sessionId}|${Number(row.version||0)}`,device_id:auth.device_id||"SUPERADMIN_BULK_EXIT",schema_version:1,client_source:"PDA"\n      });\n      exited++;\n    }catch(error){failed.push({session_id:sessionId,mnv,business_date:businessDateValue,error:String(error instanceof Error?error.message:error).slice(0,160)});}\n  }\n  const remaining=(await env.DB.prepare("SELECT s.session_id,s.mnv,s.business_date,s.shift,s.work_choice,s.state,s.pda_serial,s.user_pick,s.pack_table,s.user_pack,s.enter_at,s.version,COALESCE(e.full_name,'') full_name FROM attendance_sessions s LEFT JOIN employees e ON e.mnv=s.mnv WHERE s.state='ACTIVE' AND s.business_date<?1 ORDER BY s.business_date ASC,s.enter_at ASC,s.mnv ASC").bind(date).all<Record<string,unknown>>()).results??[];\n  return json({ok:true,source:"SERVICE_D1",business_date:date,exited,skipped_labor:skippedLabor.length,failed_count:failed.length,skipped_labor_items:skippedLabor,failed,remaining_count:remaining.length,items:remaining});\n}\n'''
s=replace_once(s,needle,insert,'bulk exit service function')
s=replace_once(s,'if(action==="old_active_sessions")return oldActiveSessions(env);','if(action==="old_active_sessions")return oldActiveSessions(env);\n  if(action==="old_active_sessions_bulk_exit")return oldActiveSessionsBulkExit(env,auth);','bulk exit router')
write(p,s)

# 3) Old-session warning: SUPERADMIN button + time-password callback + immediate refresh.
p='app/src/main/java/vn/pickpack1291/app/beta/OldSessionWarningFeature.kt';s=read(p)
s=replace_once(s,'import org.json.JSONObject','import org.json.JSONObject\nimport java.util.UUID','old warning UUID')
s=replace_once(s,'object OldSessionWarningFeature {\n    const val WARNING_TEXT = "CẢNH BÁO: CÓ PHIÊN CŨ CHƯA BẮN RA"','object OldSessionWarningFeature {\n    const val WARNING_TEXT = "CẢNH BÁO: CÓ PHIÊN CŨ CHƯA BẮN RA"\n    @Volatile private var activeRefresh:(()->Unit)?=null\n    fun onRealtime(){activeRefresh?.invoke()}','old warning active refresh')
s=replace_once(s,'fun build(activity:Activity,api:BetaApiClient,onOpen:(JSONObject)->Unit):View{','fun build(activity:Activity,api:BetaApiClient,actualRole:String,confirmTime:(String,()->Unit)->Unit,onOpen:(JSONObject)->Unit):View{','old warning signature')
# Add reload before showList.
s=replace_once(s,
'''        fun showList(){\n            if(items.isEmpty())return\n            val list=LinearLayout(activity).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(10),dp(8),dp(10),dp(8))}\n            var dialog:AlertDialog?=null\n            items.forEach{item->''',
'''        fun reload(){\n            api.call("old_active_sessions"){r->activity.runOnUiThread{if(r.ok)apply(parse(r.json?.optJSONArray("items")?:JSONArray()))}}\n        }\n        fun showList(){\n            if(items.isEmpty())return\n            val list=LinearLayout(activity).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(10),dp(8),dp(10),dp(8))}\n            var dialog:AlertDialog?=null\n            if(actualRole.uppercase()=="SUPERADMIN"){\n                val bulk=Button(activity).apply{\n                    text="RA CA TẤT CẢ HỢP LỆ";textSize=10f;setTextColor(Color.WHITE);typeface=Typeface.DEFAULT_BOLD;isAllCaps=false;background=round(Color.rgb(180,35,45),9)\n                    setOnClickListener{\n                        dialog?.dismiss()\n                        confirmTime("ra ca tất cả phiên cũ hợp lệ"){\n                            isEnabled=false\n                            api.call("old_active_sessions_bulk_exit",JSONObject().put("idempotency_key",UUID.randomUUID().toString())){r->activity.runOnUiThread{\n                                isEnabled=true\n                                if(!r.ok){TopNotice.show(activity,r.error?:"Không ra ca hàng loạt được.",TopNotice.Kind.ERROR);reload();return@runOnUiThread}\n                                val exited=r.json?.optInt("exited",0)?:0;val skipped=r.json?.optInt("skipped_labor",0)?:0;val failed=r.json?.optInt("failed_count",0)?:0\n                                TopNotice.show(activity,"Đã ra ca $exited phiên • bỏ qua công nhật $skipped${if(failed>0)" • lỗi $failed" else ""}.",if(failed>0)TopNotice.Kind.WARNING else TopNotice.Kind.SUCCESS)\n                                reload()\n                            }}\n                        }\n                    }\n                }\n                list.addView(bulk,LinearLayout.LayoutParams(-1,dp(42)).apply{bottomMargin=dp(7)})\n            }\n            items.forEach{item->''','old warning list bulk')
s=replace_once(s,
'''        button.setOnClickListener{showList()}\n        apply(local())\n        api.call("old_active_sessions"){r->activity.runOnUiThread{if(r.ok)apply(parse(r.json?.optJSONArray("items")?:JSONArray()))}}\n        return root''',
'''        button.setOnClickListener{showList()}\n        apply(local())\n        activeRefresh={activity.runOnUiThread{reload()}}\n        root.addOnAttachStateChangeListener(object:View.OnAttachStateChangeListener{\n            override fun onViewAttachedToWindow(v:View)=Unit\n            override fun onViewDetachedFromWindow(v:View){if(activeRefresh!=null)activeRefresh=null}\n        })\n        reload()\n        return root''','old warning reload binding')
write(p,s)

# 4) Post-meal: remove duplicate inner title and target refresh immediately on websocket invalidation.
p='app/src/main/java/vn/pickpack1291/app/beta/PostMealAttendanceFeature.kt';s=read(p)
s=replace_once(s,'@Volatile private var activeRefresh:(()->Unit)?=null','@Volatile private var activeRefresh:(()->Unit)?=null\n    @Volatile private var homeWarningRefresh:(()->Unit)?=null','meal home refresh field')
s=replace_once(s,
'''    fun onRealtime(changedDates:Set<String>){\n        if(activeDate.isNotBlank()&&activeDate in changedDates)activeRefresh?.invoke()\n    }\n    fun leave(){activeDate="";activeRefresh=null}''',
'''    fun onRealtime(changedDates:Set<String>){\n        if(activeDate.isNotBlank()&&activeDate in changedDates)activeRefresh?.invoke()\n        if(changedDates.isNotEmpty())homeWarningRefresh?.invoke()\n    }\n    fun onRealtimeFast(date:String){\n        if(date.isBlank())return\n        if(activeDate==date)activeRefresh?.invoke()\n        homeWarningRefresh?.invoke()\n    }\n    fun leave(){activeDate="";activeRefresh=null}''','meal realtime fast')
s=replace_once(s,
'''        apply(store.load(today))\n        api.call("meal_attendance_list",JSONObject().put("business_date",today)){r->activity.runOnUiThread{\n            if(r.ok&&r.json!=null){\n                val fresh=JSONObject(r.json.toString());store.save(fresh);apply(fresh)\n            }\n        }}\n        return root''',
'''        fun remoteRefresh(){\n            api.call("meal_attendance_list",JSONObject().put("business_date",today)){r->activity.runOnUiThread{\n                if(r.ok&&r.json!=null){val fresh=JSONObject(r.json.toString());store.save(fresh);apply(fresh)}\n            }}\n        }\n        apply(store.load(today))\n        homeWarningRefresh={activity.runOnUiThread{remoteRefresh()}}\n        root.addOnAttachStateChangeListener(object:View.OnAttachStateChangeListener{\n            override fun onViewAttachedToWindow(v:View)=Unit\n            override fun onViewDetachedFromWindow(v:View){homeWarningRefresh=null}\n        })\n        remoteRefresh()\n        return root''','meal home targeted refresh')
header='''        val header=column().apply{setPadding(dp(12),dp(9),dp(12),dp(8));background=GradientDrawable(GradientDrawable.Orientation.TL_BR,intArrayOf(navy,ThemeManager.accent(activity))).apply{cornerRadius=0f}}\n        header.addView(text("ĐIỂM DANH",15f,Color.WHITE,true))\n        root.addView(header,LinearLayout.LayoutParams(-1,-2))\n\n'''
s=replace_once(s,header,'','meal duplicate header')
write(p,s)

# 5) Document UI refinements.
p='app/src/main/java/vn/pickpack1291/app/beta/DocumentManagementFeature.kt';s=read(p)
s=replace_once(s,
'''            val listHead=row()\n            listHead.addView(text("Biên bản đã tải",11.5f,navy,true),LinearLayout.LayoutParams(0,-2,1f))\n            val refresh=button("Làm mới",navy)\n            listHead.addView(refresh,LinearLayout.LayoutParams(dp(90),dp(38)))\n            body.addView(listHead,LinearLayout.LayoutParams(-1,-2));body.addView(gap(5))\n            filterSpinner=Spinner(activity).apply{minimumHeight=dp(36);setPadding(dp(7),0,dp(7),0);background=bg()}''',
'''            body.addView(text("Biên bản đã tải",11.5f,navy,true));body.addView(gap(5))\n            filterSpinner=Spinner(activity).apply{minimumHeight=dp(36);setPadding(dp(7),0,dp(7),0);background=bg()}''','document refresh old header')
s=replace_once(s,
'''            val selectAllUploaded=iconButton(android.R.drawable.ic_menu_agenda,navy,"Chọn tất cả biên bản đang lọc")\n            deleteSelectedButton=iconButton(R.drawable.ic_pp_delete,red,"Xóa biên bản đã chọn").apply{isEnabled=false;alpha=.4f}\n            selectionRow.addView(filterSpinner,LinearLayout.LayoutParams(0,dp(38),1f).apply{marginEnd=dp(4)})\n            selectionRow.addView(selectAllUploaded,LinearLayout.LayoutParams(dp(40),dp(40)).apply{marginEnd=dp(4)})\n            selectionRow.addView(deleteSelectedButton,LinearLayout.LayoutParams(dp(40),dp(40)))''',
'''            val selectAllUploaded=iconButton(android.R.drawable.ic_menu_agenda,navy,"Chọn tất cả biên bản đang lọc")\n            deleteSelectedButton=iconButton(R.drawable.ic_pp_delete,red,"Xóa biên bản đã chọn").apply{isEnabled=false;alpha=.4f}\n            val refresh=iconButton(R.drawable.ic_pp_sync,teal,"Làm mới biên bản")\n            selectionRow.addView(filterSpinner,LinearLayout.LayoutParams(0,dp(38),1f).apply{marginEnd=dp(4)})\n            selectionRow.addView(selectAllUploaded,LinearLayout.LayoutParams(dp(40),dp(40)).apply{marginEnd=dp(4)})\n            selectionRow.addView(deleteSelectedButton,LinearLayout.LayoutParams(dp(40),dp(40)).apply{marginEnd=dp(4)})\n            selectionRow.addView(refresh,LinearLayout.LayoutParams(dp(40),dp(40)))''','document inline refresh')
s=replace_once(s,
'''            deleteDraftButton.setOnClickListener{\n                val keys=selectedDraftKeys.toSet();if(keys.isNotEmpty()){\n                    draftStore.removeItems(login,keys);selected.removeAll{it.idempotencyKey in keys};selectedDraftKeys.clear();renderSelectedPreview()\n                }\n            }''',
'''            deleteDraftButton.setOnClickListener{\n                val keys=selectedDraftKeys.toSet();if(keys.isEmpty())return@setOnClickListener\n                AlertDialog.Builder(activity).setTitle("Xóa ảnh chưa tải lên?").setMessage("Xóa ${keys.size} ảnh đã chọn khỏi hàng chờ trên thiết bị?")\n                    .setNegativeButton("HỦY",null).setPositiveButton("XÓA"){_,_->\n                        draftStore.removeItems(login,keys);selected.removeAll{it.idempotencyKey in keys};selectedDraftKeys.clear();renderSelectedPreview()\n                    }.show()\n            }''','document draft confirm')
old='''            val dialog=AlertDialog.Builder(activity).setTitle("Biên bản • vuốt mọi ảnh / pinch / kéo ảnh").setView(host).setNegativeButton("Đóng",null)\n                .setNeutralButton("XÓA ẢNH ĐÃ CHỌN",null).setPositiveButton("LƯU",null).create()\n            dialog.setOnShowListener{\n                dialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener{\n                    if(categoryIds.isEmpty())return@setOnClickListener\n                    val item=sequence[index];val categoryId=categoryIds.getOrNull(category.selectedItemPosition)?:item.optString("category_id")\n                    confirmAction("sửa ảnh biên bản"){updateDocumentRecord(item,categoryId,note.text.toString().trim()){if(it)loadCurrent()}}\n                }\n                dialog.getButton(AlertDialog.BUTTON_NEUTRAL).setOnClickListener{\n                    val ids=selectedInViewer.toList();if(ids.isEmpty()){warning("Chọn ít nhất một ảnh.");return@setOnClickListener}\n                    confirmAction("xóa ${ids.size} ảnh trong biên bản"){dialog.dismiss();startDeleteRecords(ids)}\n                }\n            }\n            dialog.show();loadCurrent()'''
new='''            lateinit var dialog:AlertDialog\n            val viewerActions=row()\n            val save=button("LƯU",teal);val deletePicked=button("XÓA ĐÃ CHỌN",red);val close=button("ĐÓNG",navy)\n            viewerActions.addView(save,LinearLayout.LayoutParams(0,dp(40),.8f).apply{marginEnd=dp(3)})\n            viewerActions.addView(deletePicked,LinearLayout.LayoutParams(0,dp(40),1.25f).apply{marginStart=dp(3);marginEnd=dp(3)})\n            viewerActions.addView(close,LinearLayout.LayoutParams(0,dp(40),.8f).apply{marginStart=dp(3)})\n            host.addView(gap(5));host.addView(viewerActions,LinearLayout.LayoutParams(-1,dp(40)))\n            dialog=AlertDialog.Builder(activity).setView(host).create()\n            save.setOnClickListener{\n                if(categoryIds.isEmpty())return@setOnClickListener\n                val item=sequence[index];val categoryId=categoryIds.getOrNull(category.selectedItemPosition)?:item.optString("category_id")\n                confirmAction("sửa ảnh biên bản"){updateDocumentRecord(item,categoryId,note.text.toString().trim()){if(it)loadCurrent()}}\n            }\n            deletePicked.setOnClickListener{\n                val ids=selectedInViewer.toList();if(ids.isEmpty()){warning("Chọn ít nhất một ảnh.");return@setOnClickListener}\n                confirmAction("xóa ${ids.size} ảnh trong biên bản"){dialog.dismiss();startDeleteRecords(ids)}\n            }\n            close.setOnClickListener{dialog.dismiss()}\n            dialog.show();loadCurrent()'''
s=replace_once(s,old,new,'document viewer controls')
write(p,s)

# 6) Drop receive: remove duplicate title/back, remove delete-all, inline actions, labels gone, 50/page.
p='app/src/main/java/vn/pickpack1291/app/beta/DropReceiveFeature.kt';s=read(p)
bar='''        val bar=row().apply{setPadding(dp(10),dp(7),dp(10),dp(7));background=GradientDrawable(GradientDrawable.Orientation.TL_BR,intArrayOf(navy,ThemeManager.accent(activity))).apply{cornerRadius=0f}}\n        bar.addView(ImageView(activity).apply{setImageResource(R.drawable.ic_pp_back);imageTintList=ColorStateList.valueOf(Color.WHITE);setPadding(dp(6),dp(6),dp(6),dp(6));contentDescription="Quay lại";setOnClickListener{onBack()}},LinearLayout.LayoutParams(dp(34),dp(34)))\n        bar.addView(text("NHẬN HÀNG RỚT",15f,Color.WHITE,true),LinearLayout.LayoutParams(0,-2,1f).apply{marginStart=dp(5)})\n        root.addView(bar,LinearLayout.LayoutParams(-1,-2))\n\n'''
s=replace_once(s,bar,'','drop duplicate bar')
old='''        val addBtn=button("Thêm thông tin",teal).apply{textSize=11f};val clearBtn=button("Xóa toàn bộ",red).apply{textSize=11f;isEnabled=canDelete;alpha=if(canDelete)1f else .35f}\n        val actions=row();actions.addView(addBtn,LinearLayout.LayoutParams(0,dp(46),1f).apply{marginEnd=dp(4)});actions.addView(clearBtn,LinearLayout.LayoutParams(0,dp(46),1f).apply{marginStart=dp(4)});body.addView(actions,LinearLayout.LayoutParams(-1,-2))\n        body.addView(gap(10))\n        val listHead=row();listHead.addView(text("Danh sách hàng rớt",11f,navy,true),LinearLayout.LayoutParams(0,-2,1f))\n        val selectAll=button("Chọn tất cả",navy);val deleteSelected=button("Xóa đã chọn",red).apply{isEnabled=false;alpha=.4f;visibility=if(canDelete)View.VISIBLE else View.GONE}\n        listHead.addView(selectAll,LinearLayout.LayoutParams(dp(94),dp(38)).apply{marginEnd=dp(3)});listHead.addView(deleteSelected,LinearLayout.LayoutParams(dp(106),dp(38)))\n        body.addView(listHead,LinearLayout.LayoutParams(-1,-2));body.addView(gap(5))'''
new='''        val addBtn=button("Thêm thông tin",teal).apply{textSize=10.2f}\n        val selectAll=button("Chọn tất cả",navy).apply{textSize=9.4f;visibility=if(canDelete)View.VISIBLE else View.GONE}\n        val deleteSelected=button("Xóa đã chọn",red).apply{textSize=9.4f;isEnabled=false;alpha=.4f;visibility=if(canDelete)View.VISIBLE else View.GONE}\n        val actions=row();actions.addView(addBtn,LinearLayout.LayoutParams(0,dp(44),1.15f).apply{marginEnd=dp(3)});actions.addView(selectAll,LinearLayout.LayoutParams(0,dp(44),.9f).apply{marginStart=dp(3);marginEnd=dp(3)});actions.addView(deleteSelected,LinearLayout.LayoutParams(0,dp(44),1f).apply{marginStart=dp(3)});body.addView(actions,LinearLayout.LayoutParams(-1,-2))\n        body.addView(gap(7))'''
s=replace_once(s,old,new,'drop actions inline')
s=s.replace('cell("DO: ${x.optString("do_number").ifBlank{"-"}}",1.12f)','cell(x.optString("do_number").ifBlank{"-"},1.12f)',1)
s=s.replace('cell("Số kiện: ${x.optInt("package_count")}",.92f,Gravity.END)','cell(x.optInt("package_count").toString(),.92f,Gravity.END)',1)
# Pagination state and renderer.
s=replace_once(s,'var dropRenderGeneration=0L','var dropRenderGeneration=0L\n        var dropPageStart=0\n        val dropPageSize=50\n        var lastDropItems=listOf<JSONObject>()','drop pagination vars')
s=replace_once(s,
'''        fun renderDropList(items:List<JSONObject>){\n            val sorted=items.sortedByDescending{runCatching{java.time.Instant.parse(it.optString("created_at")).toEpochMilli()}.getOrDefault(0L)}\n            val generation=++dropRenderGeneration\n            dropList.removeAllViews();displayedDropIds=sorted.map{it.optString("record_id")}.filter{it.isNotBlank()}\n            selectedDropIds.retainAll(displayedDropIds.toSet());updateDeleteSelection()\n            if(sorted.isEmpty()){dropList.addView(text("Chưa có dữ liệu nhận hàng rớt.",9.7f,muted,false));return}\n            fun addDropChunk(from:Int){\n                if(generation!=dropRenderGeneration)return\n                val to=minOf(from+20,sorted.size)\n                for(i in from until to){\n                    val x=sorted[i];val id=x.optString("record_id")''',
'''        fun renderDropList(items:List<JSONObject>){\n            val sorted=items.sortedByDescending{runCatching{java.time.Instant.parse(it.optString("created_at")).toEpochMilli()}.getOrDefault(0L)}\n            lastDropItems=sorted\n            if(dropPageStart>=sorted.size&&dropPageStart>0)dropPageStart=((sorted.size-1).coerceAtLeast(0)/dropPageSize)*dropPageSize\n            val pageItems=sorted.drop(dropPageStart).take(dropPageSize)\n            val generation=++dropRenderGeneration\n            dropList.removeAllViews();displayedDropIds=pageItems.map{it.optString("record_id")}.filter{it.isNotBlank()}\n            selectedDropIds.retainAll(sorted.map{it.optString("record_id")}.filter{it.isNotBlank()}.toSet());updateDeleteSelection()\n            if(sorted.isEmpty()){dropList.addView(text("Chưa có dữ liệu nhận hàng rớt.",9.7f,muted,false));return}\n            fun addPager(){\n                val from=dropPageStart+1;val to=(dropPageStart+pageItems.size).coerceAtMost(sorted.size)\n                val nav=row();\n                val prev=button("‹ 50 TRƯỚC",navy).apply{visibility=if(dropPageStart>0)View.VISIBLE else View.INVISIBLE;setOnClickListener{dropPageStart=(dropPageStart-dropPageSize).coerceAtLeast(0);renderDropList(lastDropItems)}}\n                val count=text("$from–$to / ${sorted.size}",8.8f,muted,true).apply{gravity=Gravity.CENTER}\n                val next=button("50 TIẾP ›",teal).apply{visibility=if(dropPageStart+dropPageSize<sorted.size)View.VISIBLE else View.INVISIBLE;setOnClickListener{dropPageStart+=dropPageSize;renderDropList(lastDropItems)}}\n                nav.addView(prev,LinearLayout.LayoutParams(0,dp(36),1f).apply{marginEnd=dp(3)});nav.addView(count,LinearLayout.LayoutParams(0,dp(36),.8f));nav.addView(next,LinearLayout.LayoutParams(0,dp(36),1f).apply{marginStart=dp(3)});dropList.addView(nav,LinearLayout.LayoutParams(-1,dp(36)))\n            }\n            fun addDropChunk(from:Int){\n                if(generation!=dropRenderGeneration)return\n                val to=minOf(from+20,pageItems.size)\n                for(i in from until to){\n                    val x=pageItems[i];val id=x.optString("record_id")''','drop render page start')
s=replace_once(s,'if(to<sorted.size)dropList.post{addDropChunk(to)}','if(to<pageItems.size)dropList.post{addDropChunk(to)} else addPager()','drop render page continuation')
s=replace_once(s,'selectAll.setOnClickListener{if(!canDelete)return@setOnClickListener;selectedDropIds.clear();selectedDropIds.addAll(displayedDropIds);updateDeleteSelection();loadDropList()}','selectAll.setOnClickListener{if(!canDelete)return@setOnClickListener;selectedDropIds.clear();selectedDropIds.addAll(displayedDropIds);updateDeleteSelection();renderDropList(lastDropItems)}','drop select all no reload')
# remove clear-all block exactly
clear_block='''        clearBtn.setOnClickListener{\n            if(!canDelete){error("Chỉ ADMIN/SUPERADMIN được xóa hàng rớt.");return@setOnClickListener}\n            AlertDialog.Builder(activity).setTitle("Xóa toàn bộ dữ liệu?").setMessage("Chỉ xóa các dòng nghiệp vụ trong tab Nhận hàng rớt; không xóa header, Vị trí, quyền hoặc protected ranges.").setNegativeButton("Hủy",null).setPositiveButton("TIẾP TỤC"){_,_->\n                val pw=input("Nhập mật khẩu thực tế").apply{inputType=InputType.TYPE_CLASS_TEXT or InputType.TYPE_TEXT_VARIATION_PASSWORD}\n                val authDialog=AlertDialog.Builder(activity).setTitle("Xác thực trước khi xóa").setView(pw).setNegativeButton("Hủy",null).setPositiveButton("XÁC THỰC",null).create()\n                authDialog.setOnShowListener{val b=authDialog.getButton(AlertDialog.BUTTON_POSITIVE);b.setOnClickListener{val password=pw.text.toString();if(password.isBlank()){error("Nhập mật khẩu thực tế.");return@setOnClickListener};b.isEnabled=false;b.text="Đang xác thực...";api.login(login,password){lr->activity.runOnUiThread{b.isEnabled=true;b.text="XÁC THỰC";if(!lr.ok){error("Không thể xác thực mật khẩu.");return@runOnUiThread};authDialog.dismiss();clearBtn.isEnabled=false;api.call("outbound_drop_clear",JSONObject().put("idempotency_key",UUID.randomUUID().toString())){cr->activity.runOnUiThread{clearBtn.isEnabled=true;if(!cr.ok){error(cr.error?:"Service/D1 chưa xác nhận lệnh xóa.");return@runOnUiThread};success("Service/D1 đã xác nhận xóa; Google Sheet đồng bộ nền.")}}}}}};authDialog.show();pw.requestFocus()\n            }.show()\n        }\n\n'''
s=replace_once(s,clear_block,'','drop clear all removal')
write(p,s)

# 7) OperationsActivity: immediate invalidation routing, targeted warnings, time-only auth, optimistic labor cache.
p='app/src/main/java/vn/pickpack1291/app/beta/OperationsActivity.kt';s=read(p)
s=replace_once(s,'private var employeeTimelineRealtimeRefresh: ((Set<String>) -> Unit)? = null','private var employeeTimelineRealtimeRefresh: ((Set<String>) -> Unit)? = null\n    private var businessFastRealtimeRefresh: ((String) -> Unit)? = null\n    private var laborRealtimeRefresh: ((String) -> Unit)? = null\n    private var laborWarningRealtimeRefresh: (() -> Unit)? = null','operations realtime fields')
s=replace_once(s,
'''            override fun onAuthExpired() { api.clearSession(); finishAffinity() }''',
'''            override fun onDayInvalidation(invalidation:JSONObject) {\n                val date=invalidation.optString("business_date")\n                when(screenState){\n                    "BUSINESS"->businessFastRealtimeRefresh?.invoke(date)\n                    "LABOR_HOME"->laborRealtimeRefresh?.invoke(date)\n                    "MEAL_ATTENDANCE"->PostMealAttendanceFeature.onRealtimeFast(date)\n                }\n            }\n\n            override fun onAuthExpired() { api.clearSession(); finishAffinity() }''','operations fast invalidation')
old='''        val dynamic=column(bg)\n        fun renderDynamic(){\n            dynamic.suppressLayout(true)\n            try {\n                dynamic.removeAllViews()\n                dynamic.addView(OldSessionWarningFeature.build(this,api){raw->openHistoricalSession(raw)},matchWrap())\n                dynamic.addView(PostMealAttendanceFeature.buildHomeWarning(this,api){postMealAttendanceScreen()},matchWrap())\n                if(isAdmin())dynamic.addView(laborOpenWarning(),matchWrap())\n                addBusinessShiftReconciliation(dynamic)\n            } finally { dynamic.suppressLayout(false) }\n        }\n        body.addView(dynamic,matchWrap())\n        businessRealtimeRefresh={dates->\n            val current=operationalStore.businessDate()\n            if(screenState=="BUSINESS"&&(current.isBlank()||current in dates))renderDynamic()\n        }\n        renderDynamic()'''
new='''        val dynamic=column(bg)\n        val oldWarning=OldSessionWarningFeature.build(this,api,role,{label,after->verifyTimePasswordOnly(label,after)}){raw->openHistoricalSession(raw)}\n        val mealWarning=PostMealAttendanceFeature.buildHomeWarning(this,api){postMealAttendanceScreen()}\n        dynamic.addView(oldWarning,matchWrap());dynamic.addView(mealWarning,matchWrap())\n        if(isAdmin())dynamic.addView(laborOpenWarning(),matchWrap())\n        val reconciliationHost=column(bg);dynamic.addView(reconciliationHost,matchWrap());addBusinessShiftReconciliation(reconciliationHost)\n        body.addView(dynamic,matchWrap())\n        businessFastRealtimeRefresh={date->\n            if(screenState=="BUSINESS"){\n                OldSessionWarningFeature.onRealtime();PostMealAttendanceFeature.onRealtimeFast(date);laborWarningRealtimeRefresh?.invoke()\n            }\n        }\n        businessRealtimeRefresh={dates->\n            val current=operationalStore.businessDate()\n            if(screenState=="BUSINESS"&&(current.isBlank()||current in dates)){\n                OldSessionWarningFeature.onRealtime();PostMealAttendanceFeature.onRealtime(dates);laborWarningRealtimeRefresh?.invoke()\n                reconciliationHost.removeAllViews();addBusinessShiftReconciliation(reconciliationHost)\n            }\n        }'''
s=replace_once(s,old,new,'business targeted realtime')
old='''    private fun laborOpenWarning():View{\n        val host=ReviewAlertUi.warningContainer(this)\n        val open=reconciliationButton("",false).apply{visibility=View.GONE;setOnClickListener{laborHome()}}\n        host.addView(open,ReviewAlertUi.fixedHeightParams(this))\n        api.call("labor_list",JSONObject().put("business_date",operationalStore.businessDate())){r->runOnUiThread{\n            if(!r.ok)return@runOnUiThread\n            val items=r.json?.optJSONArray("items")?:JSONArray();var count=0\n            for(i in 0 until items.length())if(items.optJSONObject(i)?.optString("state")?.equals("OPEN",true)==true)count++\n            if(count>0){open.text="CẢNH BÁO: $count CÔNG NHẬT CHƯA HOÀN THÀNH";open.visibility=View.VISIBLE;host.visibility=View.VISIBLE}\n        }}\n        return host\n    }'''
new='''    private fun laborOpenWarning():View{\n        val host=ReviewAlertUi.warningContainer(this)\n        val open=reconciliationButton("",false).apply{visibility=View.GONE;setOnClickListener{laborHome()}}\n        host.addView(open,ReviewAlertUi.fixedHeightParams(this))\n        fun refresh(){\n            api.call("labor_list",JSONObject().put("business_date",operationalStore.businessDate())){r->runOnUiThread{\n                if(!r.ok)return@runOnUiThread\n                val items=r.json?.optJSONArray("items")?:JSONArray();var count=0\n                for(i in 0 until items.length())if(items.optJSONObject(i)?.optString("state")?.equals("OPEN",true)==true)count++\n                if(count>0){open.text="CẢNH BÁO: $count CÔNG NHẬT CHƯA HOÀN THÀNH";open.visibility=View.VISIBLE;host.visibility=View.VISIBLE}\n                else{open.visibility=View.GONE;host.visibility=View.GONE}\n            }}\n        }\n        laborWarningRealtimeRefresh={if(screenState=="BUSINESS")refresh()}\n        refresh();return host\n    }'''
s=replace_once(s,old,new,'labor warning targeted')
# time-password-only helper before generic verifier
marker='''    private fun verifyActionPassword(actionLabel:String,after:()->Unit){'''
helper='''    private fun verifyTimePasswordOnly(actionLabel:String,after:()->Unit){\n        if(!isActualSuper()){showError("Chỉ SUPERADMIN được thực hiện thao tác này.");return}\n        val pw=input("Mật khẩu thời gian HHmm",true)\n        val dialog=AlertDialog.Builder(this).setTitle("Xác thực $actionLabel").setView(pw).setNegativeButton("Hủy",null).setPositiveButton("XÁC THỰC",null).create()\n        dialog.setOnShowListener{dialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener{\n            val value=pw.text.toString().trim();val now=java.time.ZonedDateTime.now(ZoneId.of("Asia/Ho_Chi_Minh"));val formatter=DateTimeFormatter.ofPattern("HHmm")\n            val ok=Regex("""\\d{4}""").matches(value)&&(-2L..2L).any{delta->now.plusMinutes(delta).format(formatter)==value}\n            if(!ok){showError("Mật khẩu thời gian không hợp lệ.");return@setOnClickListener}\n            dialog.dismiss();after()\n        }};dialog.show();pw.requestFocus()\n    }\n\n'''+marker
s=replace_once(s,marker,helper,'time password helper')
# optimistic labor cache helper before batch candidate
marker='''    private fun laborBatchCandidateFromSession(s:JSONObject):JSONObject{'''
helper='''    private fun patchLaborCacheOptimistic(item:JSONObject){\n        val date=item.optString("business_date");val laborId=item.optString("labor_id");if(date.isBlank()||laborId.isBlank())return\n        val cache=getSharedPreferences("pp_labor_list_cache_v116",MODE_PRIVATE);val raw=cache.getString(date,"").orEmpty();val rows=mutableListOf<JSONObject>()\n        if(raw.isNotBlank())runCatching{val a=JSONArray(raw);for(i in 0 until a.length())a.optJSONObject(i)?.let{rows.add(JSONObject(it.toString()))}}\n        val at=rows.indexOfFirst{it.optString("labor_id")==laborId};if(at>=0)rows[at]=JSONObject(item.toString()) else rows.add(0,JSONObject(item.toString()))\n        cache.edit().putString(date,JSONArray(rows).toString()).apply()\n    }\n\n'''+marker
s=replace_once(s,marker,helper,'labor optimistic helper')
# patch after successful start before possible finish
s=replace_once(s,
'''                            if(!started.ok){failures.add("$mnv: ${started.error?:"không tạo được"}");next(index+1,ok);return@runOnUiThread}\n                            if(end==null){next(index+1,ok+1);return@runOnUiThread}''',
'''                            if(!started.ok){failures.add("$mnv: ${started.error?:"không tạo được"}");next(index+1,ok);return@runOnUiThread}\n                            val optimistic=JSONObject().put("labor_id",laborId).put("mnv",mnv).put("business_date",session.optString("business_date")).put("shift",session.optString("shift")).put("labor_type",type).put("state","OPEN").put("start_at",startIso).put("end_at",JSONObject.NULL).put("note",noteText).put("deduct_staff",deductRequested&&!fixedMain&&!fixedLabor).put("attendance_session_id",session.optString("session_id")).put("full_name",row.optString("full_name")).put("supplier",row.optString("supplier")).put("position",row.optString("position"))\n                            patchLaborCacheOptimistic(optimistic)\n                            if(end==null){next(index+1,ok+1);return@runOnUiThread}''','labor optimistic start')
s=replace_once(s,
'''                                if(!done.ok){failures.add("$mnv: đã tạo nhưng chưa kết thúc — ${done.error?:"lỗi"}");next(index+1,ok)}\n                                else next(index+1,ok+1)''',
'''                                if(!done.ok){failures.add("$mnv: đã tạo nhưng chưa kết thúc — ${done.error?:"lỗi"}");next(index+1,ok)}\n                                else{patchLaborCacheOptimistic(JSONObject(optimistic.toString()).put("state","COMPLETED").put("end_at",end));next(index+1,ok+1)}''','labor optimistic finish')
# targeted labor refresh after loadOpen local function.
s=replace_once(s,
'''                cache.edit().putString(selectedLaborDate,a.toString()).apply();renderRows(fresh);reviewFixed(fresh)\n            }}\n        }\n\n        var busy=false''',
'''                cache.edit().putString(selectedLaborDate,a.toString()).apply();renderRows(fresh);reviewFixed(fresh)\n            }}\n        }\n        laborRealtimeRefresh={date->if(screenState=="LABOR_HOME"&&date==selectedLaborDate)loadOpen()}\n\n        var busy=false''','labor realtime targeted')
write(p,s)

# 8) Bump Beta version + release notes, keep Stable untouched.
p='app/build.gradle.kts';s=read(p);s=replace_once(s,'versionCode = 123\n            versionName = "0.4.2-beta.117"','versionCode = 124\n            versionName = "0.4.2-beta.118"','version bump')
s=s.replace('// Beta117: OWNER follow-up document compact/edit/fullscreen, cross-document viewer, dropped-receiving admin layout, large-data rendering, fixed-role labor bulk/per-person ack, true SUPERADMIN LAN mode, compact selects, and stronger transform-only tap feedback; preserves Beta116 ACTIVE_PASS. Stable unchanged.','// Beta118: SUPERADMIN bulk old-session exit, owner test data, compact document/drop UI follow-up, targeted websocket refresh, and optimistic labor cache; preserves Beta117 accepted semantics. Stable unchanged.\n// Beta117: OWNER follow-up document compact/edit/fullscreen, cross-document viewer, dropped-receiving admin layout, large-data rendering, fixed-role labor bulk/per-person ack, true SUPERADMIN LAN mode, compact selects, and stronger transform-only tap feedback; preserves Beta116 ACTIVE_PASS. Stable unchanged.',1);write(p,s)
p='app/src/main/java/vn/pickpack1291/app/beta/ReleaseNotes.kt';s=read(p);s=replace_once(s,'const val VERSION_NAME = "0.4.2-beta.117"','const val VERSION_NAME = "0.4.2-beta.118"','release notes version');write(p,s)

# 9) Make Beta117 regression version-generic and add Beta118 regression contract.
p='tools/beta117_owner_followup_contract.py';s=read(p)
s=replace_once(s,"assert 'versionCode = 123' in gradle and 'versionName = \\\"0.4.2-beta.117\\\"' in gradle\nassert 'const val VERSION_NAME = \\\"0.4.2-beta.117\\\"' in notes","assert 'versionCode = 1' in gradle and 'versionName = \\\"0.1.0-stable\\\"' in gradle\nimport re\nbeta_version=re.search(r'versionName = \\\"(0\\\\.4\\\\.2-beta\\\\.\\\\d+)\\\"',gradle).group(1)\nassert f'const val VERSION_NAME = \\\"{beta_version}\\\"' in notes",'beta117 generic version')
write(p,s)
contract='''#!/usr/bin/env python3\nfrom pathlib import Path\nroot=Path(__file__).resolve().parents[1]\nread=lambda p:(root/p).read_text(encoding="utf-8")\nops=read("app/src/main/java/vn/pickpack1291/app/beta/OperationsActivity.kt")\nold=read("app/src/main/java/vn/pickpack1291/app/beta/OldSessionWarningFeature.kt")\ndoc=read("app/src/main/java/vn/pickpack1291/app/beta/DocumentManagementFeature.kt")\ndrop=read("app/src/main/java/vn/pickpack1291/app/beta/DropReceiveFeature.kt")\nmeal=read("app/src/main/java/vn/pickpack1291/app/beta/PostMealAttendanceFeature.kt")\nfg=read("app/src/main/java/vn/pickpack1291/app/beta/ForegroundSyncCoordinator.kt")\nservice=read("service/src/mobile_hotfix.ts")\ngradle=read("app/build.gradle.kts")\nnotes=read("app/src/main/java/vn/pickpack1291/app/beta/ReleaseNotes.kt")\nassert 'versionCode = 124' in gradle and 'versionName = "0.4.2-beta.118"' in gradle\nassert 'const val VERSION_NAME = "0.4.2-beta.118"' in notes\nassert 'versionCode = 1' in gradle and 'versionName = "0.1.0-stable"' in gradle\nfor t in ['old_active_sessions_bulk_exit','SUPERADMIN_REQUIRED','HAS_LABOR','pda_auto_confirmed','commitMutation(env.DB,env,auth']:\n    assert t in service,t\nassert 'verifyTimePasswordOnly' in ops and 'RA CA TẤT CẢ HỢP LỆ' in old\nassert 'Mật khẩu thời gian HHmm' in ops and '(-2L..2L)' in ops\nassert 'Biên bản • vuốt mọi ảnh / pinch / kéo ảnh' not in doc\nassert 'R.drawable.ic_pp_sync,teal,"Làm mới biên bản"' in doc\nassert 'Xóa ảnh chưa tải lên?' in doc\nassert 'val viewerActions=row()' in doc and 'val save=button("LƯU"' in doc and 'val close=button("ĐÓNG"' in doc\nassert 'Xóa toàn bộ' not in drop and 'clearBtn' not in drop\nassert 'dropPageSize=50' in drop and '50 TIẾP' in drop\nassert 'DO: ${x.optString' not in drop and 'Số kiện: ${x.optInt' not in drop\nassert 'text("NHẬN HÀNG RỚT"' not in drop and 'text("ĐIỂM DANH",15f' not in meal\nassert 'fun onDayInvalidation' in fg and 'listener.onDayInvalidation' in fg\nassert 'businessFastRealtimeRefresh' in ops and 'laborRealtimeRefresh' in ops and 'onRealtimeFast' in meal\nassert 'patchLaborCacheOptimistic' in ops\nprint("beta118_owner_followup_contract=PASS bulk_exit=PASS seed_receipt=EXTERNAL realtime=PASS document=PASS drop=PASS")\n'''
write('tools/beta118_owner_followup_contract.py',contract)

# Wire contract into Fast Check.
p='.github/workflows/app-fast-check.yml';s=read(p)
s=replace_once(s,'      - tools/beta117_owner_followup_contract.py\n','      - tools/beta117_owner_followup_contract.py\n      - tools/beta118_owner_followup_contract.py\n','fast check path beta118')
s=replace_once(s,'          python3 tools/beta117_owner_followup_contract.py\n','          python3 tools/beta117_owner_followup_contract.py\n          python3 tools/beta118_owner_followup_contract.py\n','fast check beta118 contract')
write(p,s)

print('beta118_apply_owner_followup=PASS')
