#!/usr/bin/env python3
from pathlib import Path

def replace(path:str, old:str, new:str, label:str, count:int=1):
    p=Path(path);t=p.read_text(encoding='utf-8')
    if t.count(old)<count: raise SystemExit(f'{label}_ANCHOR_MISSING')
    p.write_text(t.replace(old,new,count),encoding='utf-8')

# ---- canonical Sheets replication: meter every direct Sheets API request ----
p='service/src/replication.ts'
replace(p,'import { isStableEnvironment, stableSheetBridge } from "./stable_sheet_bridge";','import { isStableEnvironment, stableSheetBridge } from "./stable_sheet_bridge";\nimport { requireSheetsCall } from "./quota_budget";','REPL_IMPORT')
replace(p,'  const url=`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(sheetId)}/values/${encodeURIComponent(a1(sheet,range))}?valueRenderOption=FORMATTED_VALUE`;\n  const r=await fetch(url,{headers:authHeaders(token)});','  await requireSheetsCall(env.DB,"READ");\n  const url=`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(sheetId)}/values/${encodeURIComponent(a1(sheet,range))}?valueRenderOption=FORMATTED_VALUE`;\n  const r=await fetch(url,{headers:authHeaders(token)});','REPL_GET')
replace(p,'  const qs=ranges.map(([sheet,range])=>`ranges=${encodeURIComponent(a1(sheet,range))}`).join("&"),url=`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(sheetId)}/values:batchGet?valueRenderOption=FORMATTED_VALUE&${qs}`;\n  const r=await fetch(url,{headers:authHeaders(token)});','  await requireSheetsCall(env.DB,"READ");\n  const qs=ranges.map(([sheet,range])=>`ranges=${encodeURIComponent(a1(sheet,range))}`).join("&"),url=`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(sheetId)}/values:batchGet?valueRenderOption=FORMATTED_VALUE&${qs}`;\n  const r=await fetch(url,{headers:authHeaders(token)});','REPL_BATCH_GET')
replace(p,'  const full=a1(sheet,range),url=`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(sheetId)}/values/${encodeURIComponent(full)}?valueInputOption=RAW`;\n  const r=await fetch(url,{method:"PUT"','  await requireSheetsCall(env.DB,"WRITE");\n  const full=a1(sheet,range),url=`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(sheetId)}/values/${encodeURIComponent(full)}?valueInputOption=RAW`;\n  const r=await fetch(url,{method:"PUT"','REPL_PUT')
replace(p,'  const full=a1(sheet,range),url=`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(sheetId)}/values/${encodeURIComponent(full)}:append?valueInputOption=RAW&insertDataOption=INSERT_ROWS`;\n  const r=await fetch(url,{method:"POST"','  await requireSheetsCall(env.DB,"WRITE");\n  const full=a1(sheet,range),url=`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(sheetId)}/values/${encodeURIComponent(full)}:append?valueInputOption=RAW&insertDataOption=INSERT_ROWS`;\n  const r=await fetch(url,{method:"POST"','REPL_APPEND')
replace(p,'  const url=`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(sheetId)}/values:batchUpdate`,body={valueInputOption:"RAW",data:data.map(d=>({range:a1(d.sheet,d.range),majorDimension:"ROWS",values:d.values}))};\n  const r=await fetch(url,{method:"POST"','  await requireSheetsCall(env.DB,"WRITE");\n  const url=`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(sheetId)}/values:batchUpdate`,body={valueInputOption:"RAW",data:data.map(d=>({range:a1(d.sheet,d.range),majorDimension:"ROWS",values:d.values}))};\n  const r=await fetch(url,{method:"POST"','REPL_BATCH_PUT')
replace(p,'  const id=env.GOOGLE_STAGING_SHEET_ID;\n  const meta=await fetch(`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(id)}?fields=sheets.properties(sheetId,title,hidden)`','  const id=env.GOOGLE_STAGING_SHEET_ID;\n  await requireSheetsCall(env.DB,"READ");\n  const meta=await fetch(`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(id)}?fields=sheets.properties(sheetId,title,hidden)`','REPL_META')
replace(p,'  if(!p){\n    const create=await fetch(`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(id)}:batchUpdate`','  if(!p){\n    await requireSheetsCall(env.DB,"WRITE");\n    const create=await fetch(`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(id)}:batchUpdate`','REPL_CREATE')
replace(p,'  }else if(!p.hidden&&p.sheetId!==undefined){\n    const hide=await fetch(`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(id)}:batchUpdate`','  }else if(!p.hidden&&p.sheetId!==undefined){\n    await requireSheetsCall(env.DB,"WRITE");\n    const hide=await fetch(`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(id)}:batchUpdate`','REPL_HIDE')
# On any canonical replica failure, set recovery dirty; canonical events/outbox remain durable.
replace(p,'    await db.prepare("UPDATE replication_status SET state=\'DEGRADED\',pending_count=?1,retry_count=retry_count+1,last_attempt_at=?2,last_error_class=\'TRANSIENT\',last_error=?3,updated_at=?2 WHERE singleton_id=1").bind(pending?.n??0,failedAt,msg).run();\n    return{ok:false,processed:claimed.length,appended:0,operational:0,pending:pending?.n??0,error:msg};','    await db.batch([\n      db.prepare("UPDATE replication_status SET state=\'DEGRADED\',pending_count=?1,retry_count=retry_count+1,last_attempt_at=?2,last_error_class=\'TRANSIENT\',last_error=?3,updated_at=?2 WHERE singleton_id=1").bind(pending?.n??0,failedAt,msg),\n      db.prepare("INSERT INTO system_meta(key,value,updated_at) VALUES(\'r5_operational_repair_dirty\',\'1\',?1) ON CONFLICT(key) DO UPDATE SET value=\'1\',updated_at=excluded.updated_at").bind(failedAt),\n    ]);\n    return{ok:false,processed:claimed.length,appended:0,operational:0,pending:pending?.n??0,error:msg};','REPL_DIRTY')

# ---- master projection ----
p='service/src/master_replication.ts'
replace(p,'import { isStableEnvironment, stableSheetBridge } from "./stable_sheet_bridge";','import { isStableEnvironment, stableSheetBridge } from "./stable_sheet_bridge";\nimport { requireSheetsCall } from "./quota_budget";','MASTER_IMPORT')
replace(p,'async function batchGet(env:Env,sheetId:string,token:string,ranges:string[]):Promise<Grid[]>{if(isStableEnvironment(env)){const j=await stableSheetBridge<{ok:true;values?:Grid[]}>(env,"primary","batch_get_a1",{ranges});return j.values??ranges.map(()=>[]);}const qs=','async function batchGet(env:Env,sheetId:string,token:string,ranges:string[]):Promise<Grid[]>{if(isStableEnvironment(env)){const j=await stableSheetBridge<{ok:true;values?:Grid[]}>(env,"primary","batch_get_a1",{ranges});return j.values??ranges.map(()=>[]);}await requireSheetsCall(env.DB,"READ");const qs=','MASTER_GET')
replace(p,'async function batchPut(env:Env,sheetId:string,token:string,data:DataUpdate[]):Promise<void>{if(!data.length)return;if(isStableEnvironment(env)){await stableSheetBridge(env,"primary","batch_put_a1",{data});return;}const r=await fetch','async function batchPut(env:Env,sheetId:string,token:string,data:DataUpdate[]):Promise<void>{if(!data.length)return;if(isStableEnvironment(env)){await stableSheetBridge(env,"primary","batch_put_a1",{data});return;}await requireSheetsCall(env.DB,"WRITE");const r=await fetch','MASTER_PUT')

# ---- bounded recovery/catalog projection ----
p='service/src/beta47_projection.ts'
replace(p,'import { isStableEnvironment, stableSheetBridge } from "./stable_sheet_bridge";','import { isStableEnvironment, stableSheetBridge } from "./stable_sheet_bridge";\nimport { requireSheetsCall } from "./quota_budget";','B47_IMPORT')
replace(p,'async function getGrid(env:Env,token:string,sheet:string,range:string):Promise<Grid>{if(isStableEnvironment(env)){const j=await stableSheetBridge<{ok:true;values?:Grid}>(env,"primary","get_values",{sheet,range});return j.values??[];}const full=','async function getGrid(env:Env,token:string,sheet:string,range:string):Promise<Grid>{if(isStableEnvironment(env)){const j=await stableSheetBridge<{ok:true;values?:Grid}>(env,"primary","get_values",{sheet,range});return j.values??[];}await requireSheetsCall(env.DB,"READ");const full=','B47_GET')
replace(p,'async function batchPut(env:Env,token:string,data:Update[]):Promise<void>{if(!data.length)return;if(isStableEnvironment(env)){await stableSheetBridge(env,"primary","batch_put_a1",{data});return;}const r=await fetch','async function batchPut(env:Env,token:string,data:Update[]):Promise<void>{if(!data.length)return;if(isStableEnvironment(env)){await stableSheetBridge(env,"primary","batch_put_a1",{data});return;}await requireSheetsCall(env.DB,"WRITE");const r=await fetch','B47_PUT')
replace(p,'async function appendRows(env:Env,token:string,sheet:string,range:string,values:unknown[][]):Promise<void>{if(!values.length)return;if(isStableEnvironment(env)){await stableSheetBridge(env,"primary","append_values",{sheet,range,values});return;}const full=','async function appendRows(env:Env,token:string,sheet:string,range:string,values:unknown[][]):Promise<void>{if(!values.length)return;if(isStableEnvironment(env)){await stableSheetBridge(env,"primary","append_values",{sheet,range,values});return;}await requireSheetsCall(env.DB,"WRITE");const full=','B47_APPEND')

# ---- special session projection ----
p='service/src/session_hotfix.ts'
replace(p,'import { apiError, json, nowIso, readJsonBody, sha256Hex } from "./util";','import { apiError, json, nowIso, readJsonBody, sha256Hex } from "./util";\nimport { requireSheetsCall } from "./quota_budget";','SPECIAL_IMPORT')
replace(p,'async function raRows(env:Env,t:string):Promise<unknown[][]>{const range=','async function raRows(env:Env,t:string):Promise<unknown[][]>{await requireSheetsCall(env.DB,"READ");const range=','SPECIAL_RA_READ')
replace(p,'async function updateRaTime(env:Env,t:string,row:number,value:string){const range=','async function updateRaTime(env:Env,t:string,row:number,value:string){await requireSheetsCall(env.DB,"WRITE");const range=','SPECIAL_RA_WRITE')
replace(p,'async function raSheetId(env:Env,t:string):Promise<number>{const r=await fetch','async function raSheetId(env:Env,t:string):Promise<number>{await requireSheetsCall(env.DB,"READ");const r=await fetch','SPECIAL_META_READ')
replace(p,'async function deleteRaRow(env:Env,t:string,row:number){const sheetId=await raSheetId(env,t);const r=await fetch','async function deleteRaRow(env:Env,t:string,row:number){const sheetId=await raSheetId(env,t);await requireSheetsCall(env.DB,"WRITE");const r=await fetch','SPECIAL_DELETE_WRITE')
replace(p,'async function historyHas(env:Env,t:string,eventId:string):Promise<boolean>{const range=','async function historyHas(env:Env,t:string,eventId:string):Promise<boolean>{await requireSheetsCall(env.DB,"READ");const range=','SPECIAL_HISTORY_READ')
replace(p,'async function appendHistory(env:Env,t:string,e:EventRow,s:SessionRow,label:string,detail:string){if(await historyHas(env,t,e.event_id))return;','async function appendHistory(env:Env,t:string,e:EventRow,s:SessionRow,label:string,detail:string){if(await historyHas(env,t,e.event_id))return;await requireSheetsCall(env.DB,"WRITE");','SPECIAL_HISTORY_WRITE')

# ---- outbound secondary Sheets replication ----
p='service/src/outbound_beta78.ts'
replace(p,'import { isStableEnvironment, stableSheetBridge } from "./stable_sheet_bridge";','import { isStableEnvironment, stableSheetBridge } from "./stable_sheet_bridge";\nimport { requireSheetsCall } from "./quota_budget";','OUT_IMPORT')
replace(p,'async function getValues(env:Env,token:string,sheet:string,range:string):Promise<unknown[][]>{\n  if(isStableEnvironment(env)){const j=await stableSheetBridge<{ok:true;values?:unknown[][]}>(env,"outbound","get_values",{sheet,range});return j.values??[];}\n  const url=','async function getValues(env:Env,token:string,sheet:string,range:string):Promise<unknown[][]>{\n  if(isStableEnvironment(env)){const j=await stableSheetBridge<{ok:true;values?:unknown[][]}>(env,"outbound","get_values",{sheet,range});return j.values??[];}\n  await requireSheetsCall(env.DB,"READ");\n  const url=','OUT_GET')
replace(p,'async function putValues(env:Env,token:string,sheet:string,range:string,values:unknown[][]):Promise<void>{\n  if(isStableEnvironment(env)){await stableSheetBridge(env,"outbound","put_values",{sheet,range,values});return;}\n  const full=','async function putValues(env:Env,token:string,sheet:string,range:string,values:unknown[][]):Promise<void>{\n  if(isStableEnvironment(env)){await stableSheetBridge(env,"outbound","put_values",{sheet,range,values});return;}\n  await requireSheetsCall(env.DB,"WRITE");\n  const full=','OUT_PUT')
replace(p,'async function appendValues(env:Env,token:string,sheet:string,range:string,values:unknown[][]):Promise<void>{\n  if(isStableEnvironment(env)){await stableSheetBridge(env,"outbound","append_values",{sheet,range,values});return;}\n  const full=','async function appendValues(env:Env,token:string,sheet:string,range:string,values:unknown[][]):Promise<void>{\n  if(isStableEnvironment(env)){await stableSheetBridge(env,"outbound","append_values",{sheet,range,values});return;}\n  await requireSheetsCall(env.DB,"WRITE");\n  const full=','OUT_APPEND')

# ---- document audit recovery: no 200-row idle scan ----
p='service/src/document_management.ts'
replace(p,'  try{await emitDocumentHistory(env,auth,auditId,action,targetType,targetId,detail);}catch{}','  try{await emitDocumentHistory(env,auth,auditId,action,targetType,targetId,detail);}catch{await env.DB.prepare("INSERT INTO system_meta(key,value,updated_at) VALUES(\'r5_document_audit_dirty\',\'1\',?1) ON CONFLICT(key) DO UPDATE SET value=\'1\',updated_at=excluded.updated_at").bind(at).run();}','DOC_AUDIT_DIRTY')
replace(p,'export async function flushDocumentAuditHistory(env:Env):Promise<number>{\n  const rows=await env.DB.prepare','export async function flushDocumentAuditHistory(env:Env):Promise<number>{\n  const dirty=await env.DB.prepare("SELECT value FROM system_meta WHERE key=\'r5_document_audit_dirty\'").first<{value:string}>();if(dirty?.value!=="1")return 0;\n  const rows=await env.DB.prepare','DOC_FLUSH_GUARD')
replace(p,'  let emitted=0;\n  for(const row of (rows.results||[]).reverse()){','  let emitted=0,failed=false;\n  for(const row of (rows.results||[]).reverse()){','DOC_FAILED_INIT')
replace(p,'    try{await emitDocumentHistory(env,auth,row.audit_id,row.action,row.target_type,row.target_id,detail);emitted++;}catch{}\n  }\n  return emitted;','    try{await emitDocumentHistory(env,auth,row.audit_id,row.action,row.target_type,row.target_id,detail);emitted++;}catch{failed=true;}\n  }\n  if(!failed)await env.DB.prepare("UPDATE system_meta SET value=\'0\',updated_at=?1 WHERE key=\'r5_document_audit_dirty\'").bind(nowIso()).run();\n  return emitted;','DOC_CLEAR_DIRTY')

# ---- scheduler: catalog poll is lightweight; expensive repair only if dirty ----
p='service/src/entry_product.ts'
replace(p,'import { reconcileBeta47OperationalProjection } from "./beta47_projection";','import { reconcileBeta47OperationalProjection, syncCatalogSource } from "./beta47_projection";','ENTRY_IMPORT')
old='''    try{\n      if(await claimMaintenance(env.DB,"repair-30m",30*60_000)){\n        const r=await reconcileBeta47OperationalProjection(env);\n        if(r.catalog_changed)await broadcastCatalogRevision(env);\n        const historyRows=await backfillAllHistoryAudit(env);\n        console.log(JSON.stringify({level:"info",kind:"beta95_bounded_repair",...r,history_backfill_rows:historyRows}));\n      }\n    }catch(e){console.log(JSON.stringify({level:"error",kind:"beta95_bounded_repair_failed",error:String(e).slice(0,500)}));}'''
new='''    try{\n      if(await claimMaintenance(env.DB,"catalog-source-30m",30*60_000)){\n        const catalog=await syncCatalogSource(env);if(catalog.changed)await broadcastCatalogRevision(env);\n      }\n      const dirty=await env.DB.prepare("SELECT value FROM system_meta WHERE key='r5_operational_repair_dirty'").first<{value:string}>();\n      if(dirty?.value==="1"&&await claimMaintenance(env.DB,"repair-dirty-5m",5*60_000)){\n        const r=await reconcileBeta47OperationalProjection(env);\n        if(r.catalog_changed)await broadcastCatalogRevision(env);\n        const historyRows=await backfillAllHistoryAudit(env);\n        await env.DB.prepare("UPDATE system_meta SET value='0',updated_at=?1 WHERE key='r5_operational_repair_dirty'").bind(nowIso()).run();\n        console.log(JSON.stringify({level:"info",kind:"beta95_dirty_repair",...r,history_backfill_rows:historyRows}));\n      }\n    }catch(e){console.log(JSON.stringify({level:"error",kind:"beta95_bounded_repair_failed",error:String(e).slice(0,500)}));}'''
replace(p,old,new,'ENTRY_DIRTY_REPAIR')

print('R5_QUOTA_CIRCUIT_APPLY_PASS')
